<?php

function nscc_student_portal_menu(){
	//$items['portal'] = array(
	//	'title' => 'Student Portal',
	//	'page callback' => '_nscc_student_portal_redirect',
	//	'access callback'=> TRUE,
	//	'type' => MENU_CALLBACK,
	//);
	$items['portal/%'] = array(
		'title' => 'Student Portal',
		'page callback' => '_nscc_student_portal_page',
		'page arguments'=>array(1),
		'access callback'=> '_nscc_student_portal_access',
		'access arguments' =>array(1),		
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function nscc_student_portal_perm(){
	return array('view all student portals');
}


/**
 * Implementation of hook_user().
 */
function nscc_student_portal_user($type, &$edit, &$user, $category = NULL) {
  switch ($type) {
    case 'login':
			if(is_student($user)){
				watchdog('studport',$user->name . " is a student, redirecting them to their portal");
				//$_REQUEST['destination']='portal/'.$user->name;
				$_REQUEST['destination']='portal';		
			} else {
				watchdog('studport',$user->name . " is not a student, allowing undisturbed login");
			}
		break;
  }
}


function is_student(&$user){
	if($user->ldap_authentified==1){
		$pattern = '/^uid='.$user->name.',ou=Users,dc=instructdom,dc=northseattle,dc=edu$/';
		if ( preg_match($pattern,$user->ldap_dn) ){
			return true;
		}
	}
	return false;
}

function _nscc_student_portal_access($target_username){
	global $user;
	if ($user->name == $user || user_access('view all student portals')){
		return true;
	} else {
		return false;
	}
}

function _nscc_student_portal_redirect(){
	global $user;
	if($user->uid >=1 ){
		if (is_student($user)){
			watchdog('studport',"redirecting to student portal for ".$user->name);
			//drupal_goto('portal/'.$user->name);
			drupal_goto('portal');	
		} else {
			drupal_goto('https://people.northseattle.edu/users/'.$user->name);
		}	
	} else {
		return drupal_get_form('user_login_block');
	}
}

function _nscc_student_portal_page($target_user){
	global $user;
	watchdog('studport',"Displaying student portal for ".$user->name);
	return "The eventual home of the NSCC Student Portal for $target_user.";
}





?>