<?php
// $Id: nscc_qrnode.module$

/**
*	Implementation of hook_menu()
*/
function nscc_qrnode_menu(){
	$items['qr/%'] = array(
		'title' => 'NSCC QRnode translated redirect',
		'description' => 'NSCC QRnode translated redirect',
		'page callback'=>'_nscc_qrnode_redirect',
		'page arguments'=>array(1),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	return $items;
}


function nscc_qrnode_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  switch ($op) {
  	case 'view':
  		if ($node->type=='qrnode'){
  			$node->content['code_gen_url'] = array(
  				'#value' => l('QrCode','http://zxing.org/w/chart?cht=qr&chs=120x120&chld=L&choe=UTF-8&chl=https%3A%2F%2Fnorthseattle.edu%2Fqr%2F'.$node->nid,array('attributes'=>array('target'=>'_new'))),
  			);
      }    
  	break;
	}
}


function _nscc_qrnode_redirect($nid){

	// load node
	if($qrnode = node_load($nid)){
	// ensure node is of type qrnode
		if($qrnode->type=='qrnode'){
			// get target URL
			//watchdog('qrnode', print_r($qrnode,0));
			$qrurl=$qrnode->field_qr_url[0]['url'];
			// emit redirect
			header('Location: ' . $qrurl, TRUE, 302);
			exit();
		} else {
			drupal_not_found();
		}
	} else {
		drupal_not_found();
	}

}