<?php

/**
 * @file
 * This module adds a unique identifier to the news_blog entity.
 *
 */

/*
 *  add a unique identifier if it's not set already in the news_blog
*/
function newscenter_stamper_node_presave(Drupal\Core\Entity\EntityInterface $entity)
{
    if (isset($entity) && (($entity->getType() == 'newscenter_blog_newsmention')
    || ($entity->getType() == 'newscenter_student_story'))) {
        if (empty($entity->get('field_unique_identifier')->get(0))) {
            $unique_identifier = uniqid();
            $entity->field_unique_identifier->value = $unique_identifier;
        }

    }
}
