<?php
// $Id: nscc_running_start.module,v 1.236.2.3 2009/01/12 10:09:19 goba Exp $
$running_start_error_msg = '';

//hook init
function nscc_running_start_init(){
}

//hook_help
function nscc_running_start_help($path,$arg){
	switch($path){
		case 'admin/help#nscc_running_start':
		$output = '<p>'.t('The Running Start module sets up Running Start registration sessions, and provides an interface for prospective students to sign up for them.').'</p>'."\n";
	}
	return $output;
}

//hook_perm
function nscc_running_start_perm(){
	//these permissions are assigned to role:  prod_RS_orientation_manager
	return array('administer Running Start registration sessions','view Running Start registration session rosters');
}

//hook_menu
function nscc_running_start_menu(){
	$items['manage/running_start/session'] = array(
    'title' => 'Running Start Pre-Registration Sessions',
	  'description'=> 'List Running Start Registration Sessions',
    'page callback' => '_nscc_running_start_session_listing',
    'access callback' => 'user_access',
    'access arguments' => array('view Running Start registration session rosters'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['manage/running_start/session/add'] = array(
    'title' => 'Add a Running Start Registration Session',
	  'description'=> 'Add Session Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_nscc_running_start_session_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer Running Start registration sessions'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['manage/running_start/session/%/edit'] = array(
    'title' => 'Edit a Running Start Registration Session',
	  'description'=> 'Edit Session Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_nscc_running_start_session_form',3),
    'access callback' => 'user_access',
    'access arguments' => array('administer Running Start registration sessions'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['manage/running_start/session/%/delete'] = array(
    'title' => 'Delete a Running Start Registration Session',
	  'description'=> 'Delete Session Confirmation Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_nscc_running_start_session_delete_confirm_form',3),
    'access callback' => 'user_access',
    'access arguments' => array('administer Running Start registration sessions'),
    'type' => MENU_NORMAL_ITEM,
	);

	$items['manage/running_start/session/%/view-roster'] = array(
    'title' => 'View Roster',
	  'description'=> 'View a session roster',
    'page callback' => '_nscc_running_start_session_roster',
    'page arguments' => array(3),
    'access callback' => 'user_access',
    'access arguments' => array('view Running Start registration session rosters'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['manage/running_start/session/%/export-roster'] = array(
    'title' => 'Export Roster',
	  'description'=> 'Export a session roster',
    'page callback' => '_nscc_running_start_session_export',
    'page arguments' => array(3),
    'access callback' => 'user_access',
    'access arguments' => array('view Running Start session rosters'),
    'type' => MENU_NORMAL_ITEM,
	);

	$items['manage/running_start/session/%/delete-participant/%'] = array(
    'title' => 'View Roster',
	  'description'=> 'View a session roster',
    'page callback' => '_nscc_running_start_delete_participant',
    'page arguments' => array(3,5),
    'access callback' => 'user_access',
    'access arguments' => array('view Running Start registration session rosters'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['running_start-sessions'] = array(
    'title' => 'List Running Start Registration Sessions',
	  'description'=> 'Published list of Running Start Registration sessions',
    'page callback' => '_nscc_running_start_session_listing_public',
    'access callback' => true,
    'type' => MENU_CALLBACK,
	);
	$items['running_start-sessions/%/signup'] = array(
    'title' => 'Sign up for a Running Start Registration Session',
	  'description'=> 'Sign up for a Running Start Registration Session',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_nscc_running_start_participant_add_form',1),
   	'access callback' => true,
    'type' => MENU_CALLBACK,
	);

	return $items;
}


function nscc_running_start_block($op='list', $delta=0,$edit=array()){
	switch ($op){
		case 'view':
			$block=array();
			switch($delta){
				case 0:
					//RS orientation signup session picker
					$block['subject'] = "Upcoming Running Start Registration Sessions";
					$block['content'] = _nscc_running_start_session_listing_public();
					return $block;
			}
		case 'list':
			$blocks[0]['info'] = t('NSCC RS Registration Session Listing');
			$blocks[0]['cache'] = BLOCK_CACHE_GLOBAL;
			return $blocks;
	}
}


// various form functions


function _nscc_running_start_wts_login($sid,$pin){
	global $running_start_error_msg;
	global $running_start_error_field;
	$running_start_error_field = 'sid';			
	$wts_rq_url = 'https://sccdweb.sccd.ctc.edu/scripts/rq063.exe'; //This is the HTTPS url to your rq.exe server process.

	$request_type='saddrchg';
	$response_patterns = array(
			'tkt' => "/var tkt='(\w+)';/",
			'timeout' => "/var timeout=' (\w+)';/",
			'refresh' => "/var refresh='(\d+)';/",
			'chgEnabled' => "/var chgEnabled='(\d+)';/",
			'str' => "/var str='(.+)';/",
			'cty' => "/var cty='(\w+)';/",
			'ste' => "/var ste='(\w+)';/",
			'zip' => "/var zip='(\w+)';/",
			'dp1' => "/var dp1='(\w+)';/",
			'dp2' => "/var dp2='(\w+)';/",
			'dp3' => "/var dp3='(\w+)';/",
			'ep1' => "/var ep1='(\w+)';/",
			'ep2' => "/var ep2='(\w+)';/",
			'ep3' => "/var ep3='(\w+)';/",
			'email' => "/var eMail='(\S+)';/",
	);
	$parsed_response_fields = array();

	if (_nscc_running_start_wts_validate_sid($sid) && _nscc_running_start_wts_validate_pin($pin)){
		$fields = array(	
						'request'=>$request_type,
						'sid'=>$sid,
						'pin'=>$pin
						);
							
		$response = http_parse_message(http_post_fields($wts_rq_url,$fields));
			//print_r($response->body);
	
		if (! _nscc_running_start_wts_check_https_status($response) ){
			$output_array['success'] = false;
			$output_array['error_msg'] = $running_start_error_msg;
			return $output_array;
		}

		if ( preg_match('/You have entered an incorrect\s+<BR>\s+Student ID or PIN/m',$response->body)){
			//auth failure
			$output_array['success'] = false;
			$output_array['error_field'] = 'pin';			
			$output_array['error_msg'] = "Authentication Failure";			
		} else {

				if(preg_match($response_patterns['tkt'],$response->body)){
					foreach($response_patterns as $name=>$pattern){
						if(preg_match($pattern,$response->body,$match)){
								$parsed_response_fields[$name]=$match[1];
						}
					}
					$output_array['success'] = true;
					$output_array['response_fields'] = $parsed_response_fields;
				} else {
					$output_array['success'] = false;
					$output_array['error_msg'] = "Unknown Error returned from server:\n".print_r($response->body,true);
				}		
		}

	} else {
				$output_array['success'] = false;
				$output_array['error_field'] = $running_start_error_field;			
				$output_array['error_msg'] = "Input Validation Failed: ".$running_start_error_msg;			
	}
	return $output_array;
}


function _nscc_running_start_wts_validate_sid($sid){
	global $running_start_error_msg;
	global $running_start_error_field;
	if(preg_match('/^\d\d\d\d\d\d\d\d\d$/',$sid)){
		return true;
	} else {
		$running_start_error_msg = 'Invalid SID. Your SID is the 9-digit number issued to you when you applied to NSCC.';
		$running_start_error_field = 'pin';
		return false;
	}
}

function _nscc_running_start_wts_validate_pin($pin){
	global $running_start_error_msg;
	global $running_start_error_field;
	if(preg_match('/^\d{4,6}$/',$pin) && $pin > 999){
		return true;
	} else {
		$running_start_error_msg = 'Invalid PIN. Your PIN is a 6-digit number, it usually starts as your birthdate (Though you are encouraged to change it).';
		$running_start_error_field = 'pin';
		return false;
	}
}

function _nscc_running_start_wts_check_https_status(&$response){
	global $running_start_error_msg;
	if ($response->responseCode != 200){
		$running_start_error_msg = "HTTP failure, server returned code ".$response->responseCode;
		return false;	
	}
	if(preg_match("/<TITLE>503 Service Unavailable<\/TITLE>/",$response->body)){
		$running_start_error_msg = "HTTP failure, server returned code 503";
		return false;
	}
	return true;
}



function _nscc_running_start_session_form($questionable_garbage,$session_id=null){

  //drupal_add_css(drupal_get_path('module', 'nscc_running_start') .'/nscc_running_start.css');
	if ($session_id){
		$get_session_sql = "SELECT * FROM {nscc_running_start_session} where session_id = %d;";
		$session_data = db_fetch_object(db_query(db_rewrite_sql($get_session_sql),$session_id));
		$form['session_id']= array(
			'#type'=>'value',
			'#value'=>$session_id,
		);
		$session_yrq_default = $session_data->session_yrq;
		$session_date_default = array(
			'month'=> format_date($session_data->session_datetime, 'custom','n'),
			'day'  => format_date($session_data->session_datetime, 'custom','j'),
			'year' => format_date($session_data->session_datetime, 'custom','Y'),
		);
		$session_time_default = date( 'H:i',$session_data->session_datetime);
		$session_location_default = strtoupper($session_data->session_location);
		$session_cap_default = $session_data->session_cap;
		$add_save_value = "Save";
	} else {
		$session_yrq_default = '';
		$session_date_default = array(
			'month'=>format_date(time(), 'custom','n'),
			'day'=>format_date(time(), 'custom','j'),
			'year'=>format_date(time(), 'custom','Y'),
		);
		$session_time_default = '08:00';
		$session_location_default = '';
		$session_cap_default = '';
		$add_save_value = "Add";
	}
	
	$form['session_yrq'] = array(
		'#title' => t('Year/Quarter'),
		'#type' => 'select',
		'#description' => t('Select the Year/Quarter.'),
		'#required' => true,
		'#default_value'=>$session_yrq_default,
		'#options' => _nscc_running_start_get_yrq_list(),
	);
	$form['session_date'] = array(
		'#title' => t('Date'),
		'#type' => 'date',
		'#description' => t('Indicate the date of this session.'),
		'#default_value'=>$session_date_default,
		'#required' => true,		
	);
	$form['session_time'] = array(
		'#title' => t('time'),
		'#type' => 'select',
		'#description' => t('Select the time.'),
		'#required' => true,
		'#default_value'=>$session_time_default,
		'#options' => array(
			'08:00'=>'08:00',
			'08:30'=>'08:30',
			'09:00'=>'09:00',
			'09:30'=>'09:30',
			'10:00'=>'10:00',
			'10:30'=>'10:30',
			'11:00'=>'11:00',
			'11:30'=>'11:30',
			'12:00'=>'12:00',
			'12:30'=>'12:30',
			'13:00'=>'1:00',
			'13:30'=>'1:30',
			'14:00'=>'2:00',
			'14:30'=>'2:30',
			'15:00'=>'3:00',
			'15:30'=>'3:30',
			'16:00'=>'4:00',
			'16:30'=>'4:30',
			'17:00'=>'5:00',
			'17:30'=>'5:30',
			'18:00'=>'6:00',
			'18:30'=>'6:30',
			'19:00'=>'7:00',
			'19:30'=>'7:30',
		),
	);
	$form['session_location'] = array(
		'#title'=>t('Location'),
		'#type'=>'textfield',
		'#size'=>10,
		'#description'=>t('Room number.'),
		'#required'=>true,
		'#default_value'=>$session_location_default,
	);
	$form['session_cap'] = array(
		'#title'=>t('Cap'),
		'#type'=>'textfield',
		'#size'=>2,
		'#description'=>t('Maximum attendees.'),
		'#required'=>true,
		'#default_value'=>$session_cap_default,
	);
	$form['submit'] = array(
		'#type'=>'submit',
		'#value'=>$add_save_value,
	);
	if($add_save_value=='Save'){
		$form['Delete'] = array(
			'#type'=>'submit',
			'#value'=>'Delete',
			'#submit'=>array('_nscc_running_start_session_form_submit_delete'),
		);
	}
									
	return $form;
}

function _nscc_running_start_session_form_validate($form,&$form_state){
}

function _nscc_running_start_session_form_submit_delete($form,&$form_state){
			$form_state['redirect'] = 'manage/running_start/session/'.$form_state['values']['session_id'].'/delete';
			drupal_set_message("Deleting Session id#".$form_state['values']['session_id']);
}

function _nscc_running_start_session_form_submit($form,&$form_state){
	$session_yrq = $form_state['values']['session_yrq'];
	$datetime_string = $form_state['values']['session_date']['year']."/".$form_state['values']['session_date']['month']."/".$form_state['values']['session_date']['day']." ".$form_state['values']['session_time'].":00";
	$datetime_int = strtotime($datetime_string);
	$session_location = strtoupper($form_state['values']['session_location']);
	$session_cap = $form_state['values']['session_cap'];
	
	$record = new stdClass();
	$record->session_yrq = $session_yrq;
	$record->session_datetime = $datetime_int;
	$record->session_location = $session_location;	
	$record->session_cap = $session_cap;	
	
	if($form_state['values']['session_id']){

		$record->session_id = $form_state['values']['session_id'];
		if (drupal_write_record('nscc_running_start_session',$record,array('session_id')) ){	
			$form_state['redirect'] = 'manage/running_start/session';
			drupal_set_message("Session id#".$record->session_id." Updated. Cap:".$session_cap);
		}	
		
	}else {
	
		if (drupal_write_record('nscc_running_start_session',$record) ){	
			$form_state['redirect'] = 'manage/running_start/session';
			drupal_set_message("Session id#".$record->session_id." Saved.");
		}

	}
	
}

function _nscc_running_start_session_delete_confirm_form($questionable_garbage,$session_id=null){
	$form['session_id'] = array(
		'#type'=>'value',
		'#value'=>$session_id,
	);
	$form['submit'] = array(
		'#type'=>'submit',
		'#value'=>'Delete this session Permanently and Completely',
	);								
	return $form;
}

function _nscc_running_start_session_delete_confirm_form_validate($form,&$form_state){
	if(!$form_state['values']['session_id']){
		form_set_error('submit','A session ID is required.');
	}
}

function _nscc_running_start_session_delete_confirm_form_submit($form,&$form_state){
	//delete all session participants
	$delete_participant_sql = "DELETE FROM {nscc_running_start_participant} WHERE session_id = %d;";
	$result = db_query($delete_participant_sql,$form_state['values']['session_id']);
	//delete the session itself
	$delete_session_sql = "DELETE FROM {nscc_running_start_session} WHERE session_id = %d;";
	$result = db_query($delete_session_sql,$form_state['values']['session_id']);
	//redirect to session listing
	$form_state['redirect'] = 'manage/running_start/session';
	drupal_set_message("Session id#".$form_State['values']['session_id']." [pretend] Deleted.");	
}


function _nscc_running_start_session_listing(){
	
  //drupal_add_css(drupal_get_path('module', 'nscc_running_start') .'/nscc_running_start.css');
	$get_sessions_sql = "SELECT * FROM {nscc_running_start_session} order by session_yrq desc, session_datetime desc;";
	$result = db_query(db_rewrite_sql($get_sessions_sql));
	if($result){
	$output = l('Add New Session','manage/running_start/session/add',array('attributes'=>array('class'=>'add-session-link')));
	$output .= "<table class=\"running_start-sessions-list\">\n";
	$output .="<tr class=\"column-heads\"><td class=\"column-id\">ID</td><td class=\"column-yrq\">Year/Quarter</td><td class=\"column-dtg\">Date/Time</td><td class=\"column-location\">Location</td><td class=\"column-cap\">Cap</td><td class=\"column-controls\">Controls</td></tr>\n";
	$yrq_array = _nscc_running_start_get_yrq_list();
	while ($data = db_fetch_object($result)){
		$row_classes='';
		if($data->session_datetime<time()){
			$row_classes .= ' old';
		}
		$output .="<tr class=\"$row_classes\"><td class=\"column-id\">".$data->session_id."</td><td class=\"column-yrq\">".$yrq_array[$data->session_yrq]."</td><td class=\"column-dtg\"><span class=\"date\">".date('M d, Y',$data->session_datetime)."</span> <span class=\"time\">".date('h:i',$data->session_datetime)."</span></td><td class=\"column-location\">"._nscc_running_start_locator_link(strtoupper($data->session_location))."</td><td class=\"column-cap\">".$data->session_cap."</td>";
		if(user_access('administer Running Start registration sessions')){
			$edit_link = '<a href="/manage/running_start/session/'.$data->session_id.'/edit">Edit</a>';
		}
		if(user_access('view Running Start registration session rosters')){
				$view_roster_link = '<a href="/manage/running_start/session/'.$data->session_id.'/view-roster">View Roster</a>';
		}
		$output .="<td class=\"column-controls\">$edit_link $view_roster_link</td></tr>\n";
	}
	$output .= "</table>\n";
	} else {
		$output = "No Sessions exist.";
		$output .= l('Add New Session','manage/running_start/session/add',array('atttributes'=>array('class'=>'add-session-link')));
	}
	return $output;
}

function _nscc_running_start_session_listing_public(){
	drupal_add_js(drupal_get_path('module', 'nscc_running_start') .'/nscc_running_start.js');
  drupal_add_css(drupal_get_path('module', 'nscc_running_start') .'/nscc_running_start.css');
	$get_sessions_sql = "SELECT * FROM {nscc_running_start_session} WHERE session_datetime > %d ORDER BY session_yrq ASC, session_datetime ASC;";
	$result = db_query(db_rewrite_sql($get_sessions_sql),time());
	if($result){
	$output .= "<table class=\"running_start-sessions-list\">\n";
	$output .="<tr class=\"column-heads\"><td class=\"column-yrq\">Year/Quarter</td><td class=\"column-dtg\">Date/Time</td><td class=\"column-location\">Location</td><td class=\"column-spacea\">Seats Left</td><td class=\"column-controls\">Sign Up</td></tr>\n";
	$yrq_array = _nscc_running_start_get_yrq_list();
	while ($data = db_fetch_object($result)){
		$remaining_seats = _nscc_running_start_get_session_remaining_seats($data->session_id);
		$output .="<tr class=\"\"><td class=\"column-yrq\">".$yrq_array[$data->session_yrq]."</td><td class=\"column-dtg\"><span class=\"date\">".date('M d, Y',$data->session_datetime)."</span> <span class=\"time\">".date('h:iA',$data->session_datetime)."</span></td><td class=\"column-location\">"._nscc_running_start_locator_link(strtoupper($data->session_location))."</td><td class=\"column-spacea\">".$remaining_seats."</td>";
		if ($remaining_seats >0){
			$signup_link = '<a href="/running_start-sessions/'.$data->session_id.'/signup" class=\"signup-link\">Sign Up!</a>';
			$output .="<td class=\"column-controls\">$signup_link</td></tr>\n";
		} else {
			$output.="<td class=\"column-controls\">Full!</td></tr>\n";
		}
	}
	$output .= "</table>\n";
	} else {
		$output = "No Upcoming Sessions";
	}
	return $output;
}


function _nscc_running_start_session_roster($session_id){
	drupal_add_js(drupal_get_path('module', 'nscc_running_start') .'/nscc_running_start.js');
  drupal_add_css(drupal_get_path('module', 'nscc_running_start') .'/nscc_running_start.css');
	if ($session_id){
		$bcclist = array();
		$output = _nscc_running_start_single_session_out($session_id);
		$output .= "<hr>\n";
		$output .="<table class=\"running_start-session-roster\">\n";
		$output .="<thead><tr class=\"column-heads\"><th class=\"column-action\">Action</th><th class=\"column-sid\">SID</th><th class=\"column-name\">Name</th><th class=\"column-type\">Type</th><th class=\"column-dtg\">Signed Up</th><th class=\"column-program\">Program</th><th class=\"column-testscore\">Test Score Plan</th><th class=\"column-email\">E-mail Address</th></tr></thead><tbody>\n";
		$get_roster_sql = "SELECT * FROM {nscc_running_start_participant} WHERE session_id = %d order by participant_name;";
		$result = db_query(db_rewrite_sql($get_roster_sql),$session_id);
		while($participant = db_fetch_object($result)){
			$formatted_test_scores = '';
			if($participant->sid !=''){
				$student_type = _nscc_running_start_get_student_type($participant->sid);
				$biodata = _nscc_running_start_get_input_bioextract($participant->sid);
				//watchdog('orient_test',"<pre>".print_r($biodata,true)."</pre>");
				$participant->participant_name = $biodata->fullname;
				$participant->participant_email = $biodata->email;
				$participant->student_type = $student_type;
				_nscc_running_start_update_participant($participant->sid,$biodata->fullname,$biodata->email);
			}
		
			$output .="<tr class=\"\"><td class=\"column-action\"><a title=\"Remove this participant from this session\" href=\"delete-participant/".$participant->participant_id."\">Delete</a></td><td class=\"column-sid\">".$participant->sid."</td><td class=\"column-name\">".$participant->participant_name."</td><td class=\"column-type\">".$participant->student_type."</td><td class=\"column-dtg\">".date('M d, Y H:m',$participant->signup_datetime)."</td><td class=\"column-program\">".$participant->participant_program."</td><td class=\"column-testscore\">".$participant->test_score_plan."</td><td class=\"column-email\"><a href=\"mailto:".$participant->participant_email."\">".$participant->participant_email."</a></td></tr>\n";
			if(($participant->participant_email) && ( ! in_array(strtolower(trim($participant->participant_email)),$bcclist) ) ){
					$bcclist[]=strtolower(trim($participant->participant_email));					
			}
		}	
		$output .= "</tbody></table>\n";
		if($bcclist){
			$bcc_string = implode(";",$bcclist);
			$output .= '<a href="mailto:chelsea.ackerman@seattlecolleges.edu?subject=Reminder of Upcoming Running Start Registration Session&body=Enter Message Here&bcc='.$bcc_string.'"';
			$output .=">Send an Email to this whole Roster</a><br>\n";
		}
		$output .= l('Export this Roster','manage/running_start/session/'.$session_id.'/export-roster',array('attributes'=>array('class'=>'session-list-link')))."<br>\n";
		$output .= l('Back to Sessions List','manage/running_start/session',array('attributes'=>array('class'=>'session-list-link')));
	} else {
		$output = "No Such Session.";
	}

	return $output;
}

function _nscc_running_start_session_export($session_id){
			drupal_set_header('Content-Type: application/x-msexcel');
    	drupal_set_header("Content-Disposition: attachment; filename=RSO_Roster.xls");
	    if (function_exists('mb_convert_encoding')) {
      	$output = chr(255) . chr(254);
    	}
    	$header_row = '"Checked In"'."\t".'"SID"'."\t".'"Type"'."\t".'"Name"'."\t".'"Program"'."\t".'"Test Plan"'."\t".'"Email"'."\t".'"Signed Up"'."\n";
 		  if (function_exists('mb_convert_encoding')) {
    		$header_row = mb_convert_encoding($header_row, 'UTF-16LE', 'UTF-8');
    	}
			$output .= $header_row;
			$get_roster_sql = "SELECT * FROM {nscc_running_start_participant} WHERE session_id = %d order by participant_name;";
			$result = db_query(db_rewrite_sql($get_roster_sql),$session_id);
			while($participant = db_fetch_object($result)){
				if($participant->sid !=''){
					$student_type = _nscc_running_start_get_student_type($participant->sid);
					$biodata = _nscc_running_start_get_input_bioextract($participant->sid);
					$participant->participant_name = $biodata->fullname;
					$participant->participant_email = $biodata->email;
					$participant->student_type = $student_type;
				}

				$row = '""'."\t".'"'.$participant->sid.'"'."\t".'"'.$participant->student_type.'"'."\t".'"'.$participant->participant_name.'"'."\t".'"'.$participant->participant_program.'"'."\t".'"'.$participant->test_score_plan.'"'."\t".'"'.$participant->participant_email.'"'."\t".'"'.date('M d, Y H:m',$participant->signup_datetime).'"'."\n";
				if (function_exists('mb_convert_encoding')) {
    		  $row = mb_convert_encoding($row, 'UTF-16LE', 'UTF-8');
    		}
				$output .= $row;
		 }
		 print $output;

}
function _nscc_running_start_delete_participant($session_id,$participant_id){
	$delete_participant_sql = "DELETE FROM {nscc_running_start_participant} WHERE session_id=%d and participant_id = %d";
	$result = db_query(db_rewrite_sql($delete_participant_sql),array($session_id,$participant_id));
	if($result){
		drupal_set_message("You've removed participant $participant_id from session $session_id");
	} else {
		drupal_set_message("Error removing participant $participant_id from session $session_id");
	}
	drupal_goto("manage/running_start/session/".$session_id."/view-roster");
}

function _nscc_running_start_update_participant($sid,$name,$email){
	//watchdog('orient_test','Updating participant: '.$sid." ".$name." ".$email);
	$sql = "UPDATE {nscc_running_start_participant} SET participant_name='%s',participant_email='%s' WHERE sid='%s';";
	$result = db_result(db_query(db_rewrite_sql($sql),$name,$email,$sid));
	return true;
}

function _nscc_running_start_participant_add_form($questionable_garbage,$session_id){
	drupal_add_js(drupal_get_path('module', 'nscc_running_start') .'/nscc_running_start.js');
  drupal_add_css(drupal_get_path('module', 'nscc_running_start') .'/nscc_running_start.css');
	if ($session_id){
		$get_session_sql = "SELECT * FROM {nscc_running_start_session} where session_id = %d;";
		$session_data = db_fetch_object(db_query(db_rewrite_sql($get_session_sql),$session_id));
		$yrq_array = _nscc_running_start_get_yrq_list();
		
		$form['session_id']= array(
			'#type'=>'value',
			'#value'=>$session_id,
		);
		$form['session_display'] = array(
			'#type'=>'markup',
			'#value'=>_nscc_running_start_single_session_out($session_id),
		);	
		$form['sid'] = array(
			'#title'=>t('SID'),
			'#type'=>'textfield',
			'#size'=>9,
			'#description'=>t('Your SID'),
			'#required'=>true,
			'#default_value'=>'',
		);
		$form['pin'] = array(
			'#title'=>t('PIN'),
			'#type'=>'password',
			'#size'=>6,
			'#description'=>t('Your PIN'),
			'#required'=>true,
			'#default_value'=>'',
		);
		$form['arrival_message'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="form-item">Please arrive 10-15 minutes early to check in.<br>Please remember to bring:<br><ul><li>Your Enrollment Verification Form, signed by your HS guidance counselor and your parent or guardian.</li><li>Your Schedule Planner</li></ul></div>'."\n",
		);
		$form['contact_message'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="form-item">If you believe you are experiencing technical issues with online registration, please email <a href="mailto:chelsea.ackerman@seattlecolleges.edu">Chelsea.Ackerman@seattlecolleges.edu</a> with your first and last name, student ID number</div>'."\n",
		);
		$form['submit'] = array(
			'#type'=>'submit',
			'#value'=>'Sign Up',
		);								
	}	  
  return $form;
}

function _nscc_running_start_participant_add_form_validate($form,&$form_state){
	if(! $form_state['values']['session_id']){
		form_set_error('submit', 'No such Session');
	}
	$response_array = _nscc_running_start_wts_login($form_state['values']['sid'],$form_state['values']['pin']);
	//watchdog('orient_login',"<pre>".$response_array."</pre>");
	if ($response_array['success']==false){
		form_set_error($response_array['error_field'],$response_array['error_msg']);
	}
}

function _nscc_running_start_participant_add_form_submit($form,&$form_state){
	$student_biodata = _nscc_running_start_get_input_bioextract($form_state['values']['sid']);

	$record = new stdClass();
//	$record->participant_email = $form_state['values']['participant_email'];
	$record->participant_email = $student_biodata->email;
	$record->session_id = $form_state['values']['session_id'];
//	$record->participant_name = $form_state['values']['participant_last_name'].", ".$form_state['values']['participant_first_name'];
	$record->participant_name = $student_biodata->fullname;
	$record->sid = $form_state['values']['sid'];
	$record->signup_datetime = time();

	if (drupal_write_record('nscc_running_start_participant',$record) ){	
			$form_state['redirect'] = '/';
			// *** find where this should go ***
			drupal_set_message("You're all signed up! We look forward to seeing you at the registration session.");
	}
	
	if ($record->participant_email){
		$get_session_sql = "SELECT * FROM {nscc_running_start_session} where session_id = %d;";
		$session_data = db_fetch_object(db_query(db_rewrite_sql($get_session_sql),$form_state['values']['session_id']));
		$email_params['location'] = $session_data->session_location;
		$email_params['date'] = date('F j, Y',$session_data->session_datetime);
		$email_params['time'] = date('g:i',$session_data->session_datetime);
		drupal_mail('nscc_running_start','signup_confirmation',$record->participant_email,language_default(),$email_params,'running_start-robot@northseattle.edu');	
		//watchdog('mail_test','Session: '.print_r($session_data,true));
		//watchdog('mail_test','params: '.print_r($email_params,true));
	}
}

function _nscc_running_start_get_input_bioextract($sid){
	_running_start_checkadd_sm_db();
	db_set_active('sm');
	$sql = "SELECT \"FullName\" as fullname,\"Email\" as email FROM sm.student_orientation_bioextract WHERE \"SID\"='%s';";
	$biodata = db_fetch_object(db_query($sql,$sid));
	db_set_active('default');
	return $biodata;
}

function _nscc_running_start_get_student_type($sid){
	_running_start_checkadd_sm_db();
	db_set_active('sm');
	$sql = "SELECT \"StudentTypeID\" as student_type FROM sm.student_orientation_bioextract WHERE \"SID\"='%s';";
	$student_type = db_result(db_query($sql,$sid));
	db_set_active('default');
	return $student_type;
}


function _nscc_running_start_get_test_scores($sid){
	_running_start_checkadd_sm_db();
	db_set_active('sm');
	$sql = "SELECT * FROM sm.tests_collapsed WHERE sid='%s';";
	$result = db_query($sql,$sid);
	while($score_row = db_fetch_object($result)){
		$formatted_test_scores .= "<tr><td class=\"column-test-scores-cc\">".$score_row->college_code."</td><td class=\"column-test-scores-date\">".$score_row->test_date."</td><td class=\"column-test-scores-english\">".$score_row->english."</td><td class=\"column-test-scores-math\">".$score_row->math."</td></tr>";
	}
	db_set_active('default');
	//watchdog('orient_test','Formatted test scores: '.$formatted_test_scores);
	if ($formatted_test_scores){
		$formatted_test_scores = "<table class=\"table-test-scores\"><thead><tr><th class=\"column-test-scores-cc\">College</th><th class=\"column-test-scores-date\">Date</th><th class=\"column-test-scores-english\">English</th><th class=\"column-test-scores-math\">Math</th></tr></thead>".$formatted_test_scores."</table>";
		return $formatted_test_scores;
	} else {
		return '';
	}
}

function _nscc_running_start_get_yrq_list(){
	/*
	$yrq_array = array(
		'B012'=>'Fall 2010',
		'B013'=>'Winter 2011',
		'B014'=>'Spring 2011',
		'B111'=>'Summer 2011',
		'B112'=>'Fall 2011',
	);
	return $yrq_array;
	*/
	$how_far_to_go = 6;
	$current_yrq = _schedule_get_next_starting_yrq('all');
	$quarter_list = array();
	$quarter_name_list = array();
	for($i = 1; $i <= $how_far_to_go; $i++) {
		$quarter_details = _schedule_get_quarter_details($current_yrq);
		if($quarter_details){
			$quarter_list[$i] = $current_yrq;
			$qtr_name = _schedule_yrq_to_quarter($current_yrq);
			//$qtr_start = date('M j', strtotime($quarter_details->first_day_yrq));
			$qtr_start = date('M j',_schedule_hpdate_to_date($quarter_details->first_day_yrq));
			//$qtr_end = date('M j', strtotime($quarter_details->last_day_yrq));
			$qtr_end = date('M j',_schedule_hpdate_to_date($quarter_details->last_day_yrq));
			//$quarter_name_list[$i] = "$qtr_name ($qtr_start - $qtr_end)";
			$quarter_name_list[$i] = $qtr_name;
		}
		$current_yrq = _schedule_increment_yrq($current_yrq,false);
  }

  return array_combine($quarter_list,$quarter_name_list);
}

function _nscc_running_start_get_program_list(){
	$program_array = array(
		''=>'Please Select a Program of Study',
		'College Transfer'=>array(
			'Transfer_AA'=>'Transfer - AA degree',
			'Transfer_AB'=>'Transfer - AB degree',
			'Transfer_AS'=>'Transfer - AS degree',
			'Transfer_Undecided'=>'Transfer - Undecided',
		),
		'Career Training'=>array(
			'Accounting'=>'Accounting',
			'Arch_Eng_Tech'=>'Architectural Eng. Tech',
			'Business'=>'Business',
			'Communication'=>'Communication',
			'Computing_IT'=>'Computing/Information Tech',
			'Early_Childhood_Education'=>'Early childhood Education',
			'Electronics'=>'Electronics',
			'Health_Medical'=>'Health & Medical',
			'HVAC'=>'Heating, Ventilation, Air Condition (HVAC)',
			'Nanotechnology'=>'Nanotechnology',
			'Real Estate'=>'Real Estate',
			'Career_Undecided'=>'Undecided',
		),
	);
	return $program_array;
}

function _nscc_running_start_single_session_out($session_id){
	$get_session_sql = "SELECT * FROM {nscc_running_start_session} where session_id = %d;";
	$session_data = db_fetch_object(db_query(db_rewrite_sql($get_session_sql),$session_id));
	$session_count = _nscc_running_start_get_session_count($session_id);
	$yrq_array = _nscc_running_start_get_yrq_list();
	$output .= "<table class=\"running_start-sessions-list\">\n";
	$output .="<tr class=\"column-heads\"><td class=\"column-yrq\">Year/Quarter</td><td class=\"column-dtg\">Date/Time</td><td class=\"column-location\">Location</td><td class=\"column-cap\">Cap</td><td class=\"column-count\">Count</td></tr>\n";
	$output .="<tr class=\"\"><td class=\"column-yrq\">".$yrq_array[$session_data->session_yrq]."</td><td class=\"column-dtg\"><span class=\"date\">".date('M d, Y',$session_data->session_datetime)."</span> <span class=\"time\">".date('h:iA',$session_data->session_datetime)."</span></td><td class=\"column-location\">"._nscc_running_start_locator_link(strtoupper($session_data->session_location))."</td><td class=\"column-cap\">".$session_data->session_cap."</td><td class=\"column-count\">".$session_count."</td>";
	$output .="</tr>\n";
	$output .= "</table>\n";
	return $output;
}

function _nscc_running_start_get_session_count($session_id){
	return db_result(db_query(db_rewrite_sql("select count(*) from {nscc_running_start_participant} where session_id=%d;"),$session_id));
}

function _nscc_running_start_get_session_remaining_seats($session_id){
	$session_count = _nscc_running_start_get_session_count($session_id);
	$session_cap = db_result(db_query(db_rewrite_sql("select session_cap from {nscc_running_start_session} where session_id=%d;"),$session_id));
	return $session_cap - $session_count;
}

function _nscc_running_start_locator_link($room){
	return "<span  class=\"location\" title=\"Location\"><a class=\"location\" href=\"http://prod.northseattle.edu/locator/locate/".$room."\">".$room."</a></span>";
}

function nscc_running_start_mail($key, &$message, $params){
	switch($key){
		case 'signup_confirmation':
			$message['subject']='NSCC Running Start Registration Session Confirmation';
			$orientation_date=$params['date'];
			$orientation_time=$params['time'];
			$orientation_location=$params['location'];
			$message['body'] = <<<end_of_message
Dear Running Start Student,

Thank you for signing up for the Running Start Registration Session.

At the session, we will be going over campus resources, looking at the current class schedule, and you will have an opportunity to work with an advisor to plan your schedule.

The session you have signed up for is on $orientation_date at $orientation_time, located on campus in $orientation_location. 

Please arrive 10-15 minutes early to check in.

Please remember to bring:
  -- Your Enrollment Verification Form, signed by your HS guidance counselor and your parent or guardian.
  -- Your Schedule Planner
  
If you need directions to either NSCC or the registration session location, you can access maps & direction information here: http://northseattle.edu/directions. From that website, you can select the "On Campus" tab to access a map of the NSCC campus.

We look forward to seeing you soon!

end_of_message;
		break;
		
		case "reminder":
			$message['subject'] = 'Reminder: NSCC Running Start Registration Session';		
			$orientation_date = $params['date'];
			$orientation_time = $params['time'];
			$orientation_location =$params['location'];
			$message['body'] = <<<end_of_message
Dear Running Start Student,

This is a reminder that you have signed up to attend a Running Start Registration Session at North Seattle Community College on $orientation_date at $orientation_time, located in $orientation_location.
If you need directions to either NSCC or the registration session location, you can access maps & direction information here: http://northseattle.edu/directions. From that website, you can click on the ÒOn CampusÓ tab to access a map of the NSCC campus.
We look forward to seeing you!

Please arrive 10-15 minutes early to check in.

Please remember to bring:
  -- Your (Signed) Enrollment Verification Form
  -- Your Schedule Planner

end_of_message;
		break;
  }
}

function _running_start_checkadd_sm_db() {

	global $db_url;

	// If current $db_url is not an array make it one (and don't forget to insert the default connection)
	if (!is_array($db_url)) {
		$default = $db_url;
		$db_url = array();
		$db_url['default'] = $default;
	}

  // Add the new reference
	if(!$db_url['sm']){
		$db_url['sm'] = 'pgsql://sm_viewer:83jge94gledifl@onering.inf/nscc';
	}
}

