<?php
// $Id: nscc_orientation.module,v 1.236.2.3 2009/01/12 10:09:19 goba Exp $
$orientation_error_msg = '';

//hook init
function nscc_orientation_init(){
}

//hook_help
function nscc_orientation_help($path,$arg){
	switch($path){
		case 'admin/help#nscc_orientation':
		$output = '<p>'.t('The orientation module sets up advising orientation sessions, and provides an interface for prospective students to sign up for them.').'</p>'."\n";
	}
	return $output;
}

//hook_perm
function nscc_orientation_perm(){
	//these permissions are assigned to role:  prod_nss_orientation_manager
	return array('administer orientation sessions','view orientation session rosters');
}

//hook_menu
function nscc_orientation_menu(){
	$items['manage/orientation/session'] = array(
    'title' => 'Orientation Sessions',
	  'description'=> 'List Orientation Sessions',
    'page callback' => '_nscc_orientation_session_listing',
    'access callback' => 'user_access',
    'access arguments' => array('view orientation session rosters'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['manage/orientation/session/add'] = array(
    'title' => 'Add an Orientation Session',
	  'description'=> 'Add Session Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_nscc_orientation_session_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer orientation sessions'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['manage/orientation/session/%/edit'] = array(
    'title' => 'Edit an Orientation Session',
	  'description'=> 'Edit Session Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_nscc_orientation_session_form',3),
    'access callback' => 'user_access',
    'access arguments' => array('administer orientation sessions'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['manage/orientation/session/%/delete'] = array(
    'title' => 'Delete an Orientation Session',
	  'description'=> 'Delete Session Confirmation Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_nscc_orientation_session_delete_confirm_form',3),
    'access callback' => 'user_access',
    'access arguments' => array('administer orientation sessions'),
    'type' => MENU_NORMAL_ITEM,
	);

	$items['manage/orientation/session/%/view-roster'] = array(
    'title' => 'View Roster',
	  'description'=> 'View a session roster',
    'page callback' => '_nscc_orientation_session_roster',
    'page arguments' => array(3),
    'access callback' => 'user_access',
    'access arguments' => array('view orientation session rosters'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['manage/orientation/session/%/export-roster'] = array(
    'title' => 'Export Roster',
	  'description'=> 'Export a session roster',
    'page callback' => '_nscc_orientation_session_export',
    'page arguments' => array(3),
    'access callback' => 'user_access',
    'access arguments' => array('view orientation session rosters'),
    'type' => MENU_NORMAL_ITEM,
	);

	$items['manage/orientation/session/%/delete-participant/%'] = array(
    'title' => 'View Roster',
	  'description'=> 'View a session roster',
    'page callback' => '_nscc_orientation_delete_participant',
    'page arguments' => array(3,5),
    'access callback' => 'user_access',
    'access arguments' => array('view orientation session rosters'),
    'type' => MENU_NORMAL_ITEM,
	);
	$items['orientation-sessions'] = array(
    'title' => 'List Orientation Sessions',
	  'description'=> 'Published list of orientation sessions',
    'page callback' => '_nscc_orientation_session_listing_public',
    'access callback' => true,
    'type' => MENU_CALLBACK,
	);
	$items['orientation-sessions/%/signup'] = array(
    'title' => 'Sign up for an Orientation',
	  'description'=> 'Sign up for an Orientation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_nscc_orientation_participant_add_form',1),
   	'access callback' => true,
    'type' => MENU_CALLBACK,
	);

	return $items;
}

/*
function nscc_orientation_boot(){
	/* Session initializer for storing the orientation victim's SID. Most (if not all)
	 * victims will be required to complete the abomination before 1st registration.
	 * Thus they will not have NetID account and can't authenticate using the standard
	 * site login form.
	 * @see: nscc_orientation_sid_form_submit()
	 *
	 * Note: Caching may interfere with proper loading of session variables depending
	 * on where they are being called. If so, we may need use HOOK_boot() in the .module
	 * to extract/set the value before Drupal's caching is engaged.
	 * (see: http://www.ravelsoft.com/blog/2010/session-variable-drupal)
	 
	if (! isset($_SESSION['multimedia_orientation']) ) {
		$_SESSION['multimedia_orientation'] = array();
	}
}
*/

function nscc_orientation_block($op='list', $delta=0,$edit=array()){
	switch ($op){
		case 'view':
			$block=array();
			switch($delta){
				case 0:
					//orientation survey form
					$block['subject'] = "Upcoming Orientation Sessions";
					$block['content'] = _nscc_orientation_session_listing_public();
					return $block;
				case 1:
					//orientation progress form
					$block['subject'] = "Online Orientation";
					$block['content'] = _nscc_orientation_output_progress_block();
					return $block;
				case 2:
					//orientation quiz form
					$block['subject'] = "Orientation Quiz";
					$block['content'] = _nscc_orientation_output_quiz_block();
					return $block;
				case 3:
					//orientation progress form
					$block['subject'] = "Online Orientation Sign-In";
					$block['content'] = _nscc_orientation_output_signin_block();
					return $block;
			}
		case 'list':
			$blocks[0]['info'] = t('NSCC Orientation Session Listing');
			$blocks[0]['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks[1]['info'] = t('NSCC Orientation Progress Form');
			$blocks[1]['cache'] = BLOCK_NO_CACHE;
			$blocks[2]['info'] = t('NSCC Orientation Quiz Form');
			$blocks[2]['cache'] = BLOCK_NO_CACHE;
			$blocks[3]['info'] = t('NSCC Orientation Sign-in Form');
			$blocks[3]['cache'] = BLOCK_NO_CACHE;
			return $blocks;
	}
}


function _nscc_orientation_output_progress_block(){
	$progress_tabs = _nscc_orientation_fetch_tabs(arg(1));
	return "<div>".drupal_get_form('_nscc_orientation_sid_form')."</div><div class=\"clearfix\">&nbsp;</div><div class=\"tabs progress-tabs\">$progress_tabs</div>\n";
}

function _nscc_orientation_output_signin_block(){
	return "<div>".drupal_get_form('_nscc_orientation_signin_form')."</div>\n";
}


function _nscc_orientation_output_quiz_block(){
	return "<div class=\"quizzer\">".drupal_get_form('_nscc_orientation_quiz_form')."<div class=\"clearfix\">&nbsp;</div></div>\n";
}



// various form functions

/**
 *	SID input form definition handler
 */
function _nscc_orientation_sid_form($form_state) {
//Luv - orientation change
/* 
	$sid_form_class = 'show';
	if($_SESSION['multimedia_orientation']['sid']){
		$form['sid-tracker-leader'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="show">',
		);
		$form['sid-tracking'] = array(
			'#type'=>'markup',
			'#value'=>'<span>Tracking progress for sid <em>'.$_SESSION['multimedia_orientation']['sid'].'</em></span>',
		);
		$form['modify'] = array(
			'#type' => 'submit',
			'#value' => t('Sign Out'),
		);
		$form['sid-tracker-follower'] = array(
			'#type'=>'markup',
			'#value'=>'</div>',
		);
		$sid_form_class = 'no-show';

	}

	$form['sid-form-leader'] = array(
		'#type'=>'markup',
		'#value'=>'<div class="'.$sid_form_class.'">',
	);
	$form['sid-instructions'] = array(
		'#type'=>'markup',
		'#value'=>'<span>You must provide your 9-digit SID number (issued to you when you applied) and PIN (defaults to your birthdate) in order to get credit for completing this online orientation. See the Welcome tab for instructions on how to take this orientation.</span>',
	);
	$form['participant_program'] = array(
			//'#description' => t('Select Your Program.'),
			'#title' => t('Program'),
			'#type' => 'select',
			'#required' => true,
			'#options' => _nscc_orientation_get_program_list(),
		);
	$form['sid'] = array(
		'#type' => 'textfield',
		'#title' => 'SID',
		'#maxlength' => 9,
		'#size' => 9,
		'#required' => false,
		'#default_value'=>$_SESSION['multimedia_orientation']['sid'],
	);
	$form['pin'] = array(
		'#type' => 'password',
		'#title' => 'PIN',
		'#maxlength' => 6,
		'#size' => 6,
		'#required' => false,
		'#default_value'=>'',
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	$form['sid-form-follower'] = array(
		'#type'=>'markup',
		'#value'=>'</div>',
	);
	*/
//Luv - orientation change
	return $form;
}

/**
 *	SID input form definition handler
 */
function _nscc_orientation_signin_form($form_state) {

	if($_SESSION['multimedia_orientation']['sid']){
		$form['signin-form-leader'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="orientation-signin-form logged-in">',
		);
		
		$form['onward-link'] = array(
			'#type'=>'markup',
			'#value'=>'<div><a class="enter-orientation-button" href="/orientation">Continue to the Orientation.</a></div>',
		);

		$form['sid-tracking'] = array(
			'#type'=>'markup',
			'#value'=>'<span class="">Tracking progress for sid <em>'.$_SESSION['multimedia_orientation']['sid'].'</em></span>',
		);
		$form['modify'] = array(
			'#type' => 'submit',
			'#value' => t('Sign Out'),
		);
		$form['signin-form-follower'] = array(
			'#type'=>'markup',
			'#value'=>'</div>',
		);
		
	} else {

		$form['signin-form-leader'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="orientation-signin-form not-logged-in">',
		);
		$form['sid-instructions'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="signin-instructions">You must provide your 9-digit SID number (issued to you when you applied) and PIN (defaults to your birthdate) in order to get credit for completing this online orientation.</div>',
		);
		$form['sid'] = array(
			'#type' => 'textfield',
			'#title' => 'SID',
			'#maxlength' => 9,
			'#size' => 9,
			'#required' => true,
			'#default_value'=>$_SESSION['multimedia_orientation']['sid'],
		);
		$form['pin'] = array(
			'#type' => 'password',
			'#title' => 'PIN',
			'#maxlength' => 6,
			'#size' => 6,
			'#required' => true,
			'#default_value'=>'',
		);
		$form['submit'] = array(
			'#type' => 'submit',
			'#value' => t('Start My Orientation!'),
			
		);
		$form['signin-form-follower'] = array(
			'#type'=>'markup',
			'#value'=>'</div>',
		);
	}
	return $form;
}




function _nscc_orientation_quiz_form($form_state){
	$op_node = node_load(arg(1));
	$answers = array();
	$index = 1;
	$answered_already = _nscc_orientation_check_quiz_answered($_SESSION['multimedia_orientation']['sid'],$op_node->nid);
	$complete_already = _nscc_orientation_is_quiz_complete($_SESSION['multimedia_orientation']['sid']);
	foreach($op_node->field_quiz_answers as $current_answer){
		$answer_text = $current_answer['value'];
		$answers[$index] = $answer_text;
		$index++;
	}
	$form['sid'] = array(
		'#type' => 'value',
		'#value' => $_SESSION['multimedia_orientation']['sid'],
	);
	$form['nid'] = array(
		'#type' => 'value',
		'#value' => $op_node->nid,
	);
	$form['correct'] = array(
		'#type'=>'value',
		'#value'=>$op_node->field_quiz_correct[0]['value'],
	);
	if(! $answered_already){
		$form['quiz_wrapper_leader']=array(
			'#type'=>'markup',
			'#value'=>'<div class="quiz-question">',
		);
		$form['question'] = array(
			'#type'=>'radios',
			'#title'=>t($op_node->field_quiz_question[0]['value']),
			'#options'=>$answers,
			'#description'=>'Select the Correct Answer.',
		);
		if($_SESSION['multimedia_orientation']['sid']){
			$form['submit'] = array(
				'#type' => 'submit',
				'#value' => t('Record My Answer'),
			);
		} else {
			$form['no-credit'] = array(
				'#type'=>'submit',
				'#value' => t('Check My Answer'),
			);
		}
		$form['quiz_wrapper_follower']=array(
			'#type'=>'markup',
			'#value'=>'</div>',
		);
	} else {
		$form['quiz_wrapper_leader']=array(
			'#type'=>'markup',
			'#value'=>'<div class="quiz-question completed">',
		);
		$form['question'] = array(
			'#type'=>'markup',
			'#value'=>"<div class=\"completed-question\">".$op_node->field_quiz_question[0]['value']."</div>\n",
		);
		$correct_index =  $op_node->field_quiz_correct[0]['value'] - 1;
		$form['answer'] = array(
			'#type'=>'markup',
			'#value'=>"<div class=\"completed-answer\">".$op_node->field_quiz_answers[$correct_index]['value']."</div>\n",
		);
		$form['quiz_wrapper_follower']=array(
			'#type'=>'markup',
			'#value'=>'</div>',
		);
	}

	if($complete_already){
		$form['achievement_badge'] = array(
			'#type' => 'markup',
			#'#value' => '<div class="achievement quiz-complete"><p>Congratulations! You have completed the online New Student Orientation. Your next step is to register for classes. If you need a review, refer to the video under “Registration/Plan Your Schedule."</p><p>If you plan to pursue a program in Health and Human Services (including Early Childhood Education), Watch Tech or Basic Skills (ABE, GED, High School Completion or ESL), contact those departments directly for admissions and advising information.</p></div>',
			'#value' => '<div class="achievement quiz-complete">You have completed the orientation quiz.</div>',
		);
	} else {
		$form['achievement_badge'] = array(
			'#type' => 'markup',
			'#value' => '<div class="achievement quiz-incomplete">You have not completed all the orientation quiz questions.</div>',
		);
	}


	return $form;
}




/**
 *	SID input form validation handler
 */
function _nscc_orientation_sid_form_validate($form, &$form_state) {
	if($form_state['values']['op'] != 'Sign Out'){
		$response_array = _nscc_wts_authverify($form_state['values']['sid'],$form_state['values']['pin']);
		watchdog('orient_login',"<pre>".$response_array."</pre>");
		if ($response_array['success']==false){
			form_set_error($response_array['error_field'],$response_array['error_msg']);
		}
	}
}

function _nscc_orientation_signin_form_validate($form, &$form_state) {
	if($form_state['values']['op'] != 'Sign Out'){
		$response_array = _nscc_wts_authverify($form_state['values']['sid'],$form_state['values']['pin']);
		watchdog('orient_login',"<pre>".$response_array."</pre>");
		if ($response_array['success']==false){
			form_set_error($response_array['error_field'],$response_array['error_msg']);
		}
	}
}


function _nscc_orientation_quiz_form_validate($form, &$form_state) {
	if ($form_state['values']['correct'] != $form_state['values']['question']){
		form_set_error('question','Your answer is incorrect. Please review the section information and try agin.');
	} else {
	}
	
}

/**
 *	SID input form submission handler
 */
function _nscc_orientation_sid_form_submit($form, &$form_state) {
	//drupal_set_message('<pre>'.print_r($form_state['values'],true).'</pre>');
	if($form_state['values']['op'] == 'Sign Out'){
		$_SESSION['multimedia_orientation']['sid']='';
	} else {
		$_SESSION['multimedia_orientation']['sid'] = trim($form_state['values']['sid']);
	}
}

function _nscc_orientation_signin_form_submit($form, &$form_state) {
	//drupal_set_message('<pre>'.print_r($form_state['values'],true).'</pre>');
	if($form_state['values']['op'] == 'Sign Out'){
		$_SESSION['multimedia_orientation']['sid']='';
	} else {
		$_SESSION['multimedia_orientation']['sid'] = trim($form_state['values']['sid']);
	}
}



function _nscc_orientation_quiz_form_submit($form, &$form_state) {
   $complete_already = _nscc_orientation_check_quiz_answered($form_state['values']['sid'],$form_state['values']['nid']);
		if($form_state['values']['op']=='Check My Answer'){
			drupal_set_message('Correct! If you\'d given us your sid (above), you\'d have credit for that answer.');
		}

   if( ! $complete_already && $form_state['values']['sid'] != '' ){
   	$result = _nscc_orientation_post_quiz_answer($form_state['values']['sid'],$form_state['values']['nid']);
   	//trap errors here.
   	  	
   	//check for completeness here. Only fires if the question wasn't already answered.
   	if( _nscc_orientation_is_quiz_complete($form_state['values']['sid']) ){
   		//post completion
   		_nscc_orientation_post_quiz_completion($form_state['values']['sid']);
   		drupal_set_message('Congratulations! You have completed the online New Student Orientation.'); 
   		drupal_set_message('Your next step is to register for classes. If you need a review, refer to the video under "Registration/Plan Your Schedule."');
   		drupal_set_message('If you plan to pursue a program in Health and Human Services (including Early Childhood Education), Watch Tech or Basic Skills (ABE, GED, High School Completion or ESL), contact those departments directly for admissions and advising information.');
			drupal_set_message('Please Complete our <a href="https://docs.google.com/forms/d/1gj4TXinHlYYXXbAYj0lC2SceE8qmw_AI4NggkbVwBg4/viewform">Start Survey</a>.');
   	}

   }
}
function _nscc_orientation_post_quiz_completion($sid){
	$sql ="INSERT INTO {nscc_orientation_completions} (victim_sid,presumptive_yrq,dtg_completed) VALUES('%s','%s',now());";
	$presumptive_yrq = _schedule_get_next_starting_yrq('all');
	$result = db_result(db_query(db_rewrite_sql($sql),$sid,$presumptive_yrq));
	return $result;
}

function _nscc_orientation_post_quiz_answer($sid,$nid){
	$sql = "INSERT INTO {nscc_orientation_progress} (victim_sid,question_nid,dtg) values ('%s',%d,now());";
	$result = db_result(db_query(db_rewrite_sql($sql),$sid,$nid));
	return $result;
}

function _nscc_orientation_check_quiz_answered($sid,$nid){
	$sql = "SELECT count(*) FROM {nscc_orientation_progress} WHERE victim_sid='%s' AND question_nid=%d;";
	$count = db_result(db_query(db_rewrite_sql($sql),$sid,$nid));
	if ($count >=1){
		//this sid has already answered this question
		return true;
	} else {
		return false;
	}
}

function _nscc_orientation_mark_questions_sent($sid){
	$sql = "UPDATE {nscc_orientation_progress} SET sent=now() WHERE victim_sid='%s';";
	$result = db_result(db_query(db_rewrite_sql($sql),$sid));
	return $result;
}

function _nscc_orientation_is_quiz_complete($sid){
	$sql = <<<CHECK_SQL
SELECT CASE WHEN count(ops.nid) > 0 THEN 'incomplete' ELSE 'complete' END FROM 
(SELECT n.nid FROM {node} n WHERE n.status = 1 AND n.type = 'orientation_page') AS ops LEFT JOIN 
(SELECT question_nid AS nid,dtg FROM {nscc_orientation_progress} WHERE victim_sid='%s') AS progress USING (nid)
WHERE progress.dtg IS NULL;
CHECK_SQL;
	$count = db_result(db_query(db_rewrite_sql($sql),$sid));
	if ($count == 'incomplete'){
		//there are unanswered quiz questions
		return false;
	} else {
		//all are answered...or there is an error perhaps?
		if ($count == 'complete'){
			return true;
		} else {
		//on error return false	
		 return false;
		}	
	}
	
}

/**
 *	Helper function to retrieve the published orientation_page nodes.
 */
function _nscc_orientation_fetch_tabs($current_nid) {

	$op_sql = <<<OP_SQL
select node.nid, node.title, fields.field_tab_title_value as tab_label, fields.field_tab_order_value as tab_order, alias.src as path, alias.dst as path_alias
from {node} node
join {content_type_orientation_page} fields using (nid, vid)
join {url_alias} alias on ('node/'::text || node.nid) = alias.src::text
where node.status = 1 and type = 'orientation_page'
order by fields.field_tab_order_value asc
OP_SQL;

	$progress_sql = "select question_nid as nid from {nscc_orientation_progress} where victim_sid='%s';";	

	$completed_nids = array();

	$op_result =  db_query(db_rewrite_sql($op_sql));
	if( $_SESSION['multimedia_orientation']['sid'] ){
		$progress_result = db_query(db_rewrite_sql($progress_sql),$_SESSION['multimedia_orientation']['sid']);
		while($current_progress = db_fetch_object($progress_result)){
			$completed_nids[] = $current_progress->nid;
		}
	}
	//watchdog('orient_test','completed: '.print_r($completed_nids,true));
	while($orientation_tab = db_fetch_object($op_result)){
		$classes='';
		if ($current_nid == $orientation_tab->nid){
			$classes = 'active';
		}
		if(in_array($orientation_tab->nid,$completed_nids)){
			$classes .=' completed';
		}
		$tabs .= "<li class=\"$classes\"><a href=\"/".$orientation_tab->path_alias."\"><span class=\"tab\">".$orientation_tab->tab_label."</span></a></li>";
	}
	return "<ul class=\"tabs primary clear-block\">$tabs</ul>\n";	
}


function _nscc_orientation_session_form($questionable_garbage,$session_id=null){
  drupal_add_css(drupal_get_path('module', 'nscc_orientation') .'/nscc_orientation.css');
	if ($session_id){
		$get_session_sql = "SELECT * FROM {nscc_orientation_session} where session_id = %d;";
		$session_data = db_fetch_object(db_query(db_rewrite_sql($get_session_sql),$session_id));
		$form['session_id']= array(
			'#type'=>'value',
			'#value'=>$session_id,
		);
		$session_yrq_default = $session_data->session_yrq;
		$session_date_default = array(
			'month'=> format_date($session_data->session_datetime, 'custom','n'),
			'day'  => format_date($session_data->session_datetime, 'custom','j'),
			'year' => format_date($session_data->session_datetime, 'custom','Y'),
		);
		$session_time_default = date( 'H:i',$session_data->session_datetime);
		$session_location_default = strtoupper($session_data->session_location);
		$session_cap_default = $session_data->session_cap;
		$add_save_value = "Save";
	} else {
		$session_yrq_default = '';
		$session_date_default = array(
			'month'=>format_date(time(), 'custom','n'),
			'day'=>format_date(time(), 'custom','j'),
			'year'=>format_date(time(), 'custom','Y'),
		);
		$session_time_default = '08:00';
		$session_location_default = '';
		$session_cap_default = '';
		$add_save_value = "Add";
	}
	
	$form['session_yrq'] = array(
		'#title' => t('Year/Quarter'),
		'#type' => 'select',
		'#description' => t('Select the Year/Quarter.'),
		'#required' => true,
		'#default_value'=>$session_yrq_default,
		'#options' => _nscc_orientation_get_yrq_list(),
	);
	$form['session_date'] = array(
		'#title' => t('Date'),
		'#type' => 'date',
		'#description' => t('Indicate the date of this session.'),
		'#default_value'=>$session_date_default,
		'#required' => true,		
	);
	$form['session_time'] = array(
		'#title' => t('time'),
		'#type' => 'select',
		'#description' => t('Select the time.'),
		'#required' => true,
		'#default_value'=>$session_time_default,
		'#options' => array(
			'08:00'=>'08:00',
			'08:30'=>'08:30',
			'09:00'=>'09:00',
			'09:30'=>'09:30',
			'10:00'=>'10:00',
			'10:30'=>'10:30',
			'11:00'=>'11:00',
			'11:30'=>'11:30',
			'12:00'=>'12:00',
			'12:30'=>'12:30',
			'13:00'=>'1:00',
			'13:30'=>'1:30',
			'14:00'=>'2:00',
			'14:30'=>'2:30',
			'15:00'=>'3:00',
			'15:30'=>'3:30',
			'16:00'=>'4:00',
			'16:30'=>'4:30',
			'17:00'=>'5:00',
			'17:30'=>'5:30',
			'18:00'=>'6:00',
			'18:30'=>'6:30',
			'19:00'=>'7:00',
			'19:30'=>'7:30',
		),
	);
	$form['session_location'] = array(
		'#title'=>t('Location'),
		'#type'=>'textfield',
		'#size'=>10,
		'#description'=>t('Room number.'),
		'#required'=>true,
		'#default_value'=>$session_location_default,
	);
	$form['session_cap'] = array(
		'#title'=>t('Cap'),
		'#type'=>'textfield',
		'#size'=>2,
		'#description'=>t('Maximum attendees.'),
		'#required'=>true,
		'#default_value'=>$session_cap_default,
	);
	$form['submit'] = array(
		'#type'=>'submit',
		'#value'=>$add_save_value,
	);
	if($add_save_value=='Save'){
		$form['Delete'] = array(
			'#type'=>'submit',
			'#value'=>'Delete',
			'#submit'=>array('_nscc_orientation_session_form_submit_delete'),
		);
	}
									
	return $form;
}

function _nscc_orientation_session_form_validate($form,&$form_state){
}

function _nscc_orientation_session_form_submit_delete($form,&$form_state){
			$form_state['redirect'] = 'manage/orientation/session/'.$form_state['values']['session_id'].'/delete';
			drupal_set_message("Deleting Session id#".$form_state['values']['session_id']);
}

function _nscc_orientation_session_form_submit($form,&$form_state){
	$session_yrq = $form_state['values']['session_yrq'];
	$datetime_string = $form_state['values']['session_date']['year']."/".$form_state['values']['session_date']['month']."/".$form_state['values']['session_date']['day']." ".$form_state['values']['session_time'].":00";
	$datetime_int = strtotime($datetime_string);
	$session_location = strtoupper($form_state['values']['session_location']);
	$session_cap = $form_state['values']['session_cap'];
	
	$record = new stdClass();
	$record->session_yrq = $session_yrq;
	$record->session_datetime = $datetime_int;
	$record->session_location = $session_location;	
	$record->session_cap = $session_cap;	
	
	if($form_state['values']['session_id']){

		$record->session_id = $form_state['values']['session_id'];
		if (drupal_write_record('nscc_orientation_session',$record,array('session_id')) ){	
			$form_state['redirect'] = 'manage/orientation/session';
			drupal_set_message("Session id#".$record->session_id." Updated. Cap:".$session_cap);
		}	
		
	}else {
	
		if (drupal_write_record('nscc_orientation_session',$record) ){	
			$form_state['redirect'] = 'manage/orientation/session';
			drupal_set_message("Session id#".$record->session_id." Saved.");
		}

	}
	
}

function _nscc_orientation_session_delete_confirm_form($questionable_garbage,$session_id=null){
	$form['session_id'] = array(
		'#type'=>'value',
		'#value'=>$session_id,
	);
	$form['submit'] = array(
		'#type'=>'submit',
		'#value'=>'Delete this session Permanently and Completely',
	);								
	return $form;
}

function _nscc_orientation_session_delete_confirm_form_validate($form,&$form_state){
	if(!$form_state['values']['session_id']){
		form_set_error('submit','A session ID is required.');
	}
}

function _nscc_orientation_session_delete_confirm_form_submit($form,&$form_state){
	//delete all session participants
	$delete_participant_sql = "DELETE FROM {nscc_orientation_participant} WHERE session_id = %d;";
	$result = db_query($delete_participant_sql,$form_state['values']['session_id']);
	//delete the session itself
	$delete_session_sql = "DELETE FROM {nscc_orientation_session} WHERE session_id = %d;";
	$result = db_query($delete_session_sql,$form_state['values']['session_id']);
	//redirect to session listing
	$form_state['redirect'] = 'manage/orientation/session';
	drupal_set_message("Session id#".$form_State['values']['session_id']." [pretend] Deleted.");	
}


function _nscc_orientation_session_listing(){
  drupal_add_css(drupal_get_path('module', 'nscc_orientation') .'/nscc_orientation.css');
	$get_sessions_sql = "SELECT * FROM {nscc_orientation_session} order by session_yrq desc, session_datetime desc;";
	$result = db_query(db_rewrite_sql($get_sessions_sql));
	if($result){
	$output = l('Add New Session','manage/orientation/session/add',array('attributes'=>array('class'=>'add-session-link')));
	$output .= "<table class=\"orientation-sessions-list\">\n";
	$output .="<tr class=\"column-heads\"><td class=\"column-id\">ID</td><td class=\"column-yrq\">Year/Quarter</td><td class=\"column-dtg\">Date/Time</td><td class=\"column-location\">Location</td><td class=\"column-cap\">Cap</td><td class=\"column-controls\">Controls</td></tr>\n";
	$yrq_array = _nscc_orientation_get_yrq_list();
	while ($data = db_fetch_object($result)){
		$row_classes='';
		if($data->session_datetime<time()){
			$row_classes .= ' old';
		}
		$output .="<tr class=\"$row_classes\"><td class=\"column-id\">".$data->session_id."</td><td class=\"column-yrq\">".$yrq_array[$data->session_yrq]."</td><td class=\"column-dtg\"><span class=\"date\">".date('M d, Y',$data->session_datetime)."</span> <span class=\"time\">".date('h:i',$data->session_datetime)."</span></td><td class=\"column-location\">"._nscc_orientation_locator_link(strtoupper($data->session_location))."</td><td class=\"column-cap\">".$data->session_cap."</td>";
		if(user_access('administer orientation sessions')){
			$edit_link = '<a href="/manage/orientation/session/'.$data->session_id.'/edit">Edit</a>';
		}
		if(user_access('view orientation session rosters')){
				$view_roster_link = '<a href="/manage/orientation/session/'.$data->session_id.'/view-roster">View Roster</a>';
		}
		$output .="<td class=\"column-controls\">$edit_link $view_roster_link</td></tr>\n";
	}
	$output .= "</table>\n";
	} else {
		$output = "No Sessions exist.";
		$output .= l('Add New Session','manage/orientation/session/add',array('atttributes'=>array('class'=>'add-session-link')));
	}
	return $output;
}

function _nscc_orientation_session_listing_public(){
	drupal_add_js(drupal_get_path('module', 'nscc_orientation') .'/nscc_orientation.js');
  drupal_add_css(drupal_get_path('module', 'nscc_orientation') .'/nscc_orientation.css');
	$get_sessions_sql = "SELECT * FROM {nscc_orientation_session} WHERE session_datetime > %d ORDER BY session_yrq ASC, session_datetime ASC;";
	$result = db_query(db_rewrite_sql($get_sessions_sql),time());
	if($result){
	$output .= "<table class=\"orientation-sessions-list\">\n";
	$output .="<tr class=\"column-heads\"><td class=\"column-yrq\">Year/Quarter</td><td class=\"column-dtg\">Date/Time</td><td class=\"column-location\">Location</td><td class=\"column-spacea\">Seats Left</td><td class=\"column-controls\">Sign Up</td></tr>\n";
	$yrq_array = _nscc_orientation_get_yrq_list();
	while ($data = db_fetch_object($result)){
		$remaining_seats = _nscc_orientation_get_session_remaining_seats($data->session_id);
		$output .="<tr class=\"\"><td class=\"column-yrq\">".$yrq_array[$data->session_yrq]."</td><td class=\"column-dtg\"><span class=\"date\">".date('M d, Y',$data->session_datetime)."</span> <span class=\"time\">".date('h:iA',$data->session_datetime)."</span></td><td class=\"column-location\">"._nscc_orientation_locator_link(strtoupper($data->session_location))."</td><td class=\"column-spacea\">".$remaining_seats."</td>";
		if ($remaining_seats >0){
			$signup_link = '<a href="/orientation-sessions/'.$data->session_id.'/signup" class=\"signup-link\">Sign Up!</a>';
			$output .="<td class=\"column-controls\">$signup_link</td></tr>\n";
		} else {
			$output.="<td class=\"column-controls\">Full!</td></tr>\n";
		}
	}
	$output .= "</table>\n";
	} else {
		$output = "No Upcoming Sessions";
	}
	return $output;
}


function _nscc_orientation_session_roster($session_id){
	drupal_add_js(drupal_get_path('module', 'nscc_orientation') .'/nscc_orientation.js');
  drupal_add_css(drupal_get_path('module', 'nscc_orientation') .'/nscc_orientation.css');
	if ($session_id){
		$bcclist = array();
		$output = _nscc_orientation_single_session_out($session_id);
		$output .= "<hr>\n";
		$output .="<table class=\"orientation-session-roster\">\n";
		$output .="<thead><tr class=\"column-heads\"><th class=\"column-action\">Action</th><th class=\"column-sid\">SID</th><th class=\"column-name\">Name</th><th class=\"column-type\">Type</th><th class=\"column-dtg\">Signed Up</th><th class=\"column-program\">Program</th><th class=\"column-testscore\">Test Score Plan</th><th class=\"column-email\">E-mail Address</th></tr></thead><tbody>\n";
		$get_roster_sql = "SELECT * FROM {nscc_orientation_participant} WHERE session_id = %d order by participant_name;";
		$result = db_query(db_rewrite_sql($get_roster_sql),$session_id);
		while($participant = db_fetch_object($result)){
			$formatted_test_scores = '';
			if($participant->sid !=''){
				$student_type = _nscc_orientation_get_student_type($participant->sid);
				$biodata = _nscc_orientation_get_input_bioextract($participant->sid);
				//watchdog('orient_test',"<pre>".print_r($biodata,true)."</pre>");
				$participant->participant_name = $biodata->fullname;
				$participant->participant_email = $biodata->email;
				$participant->student_type = $student_type;
				_nscc_orientation_update_participant($participant->sid,$biodata->fullname,$biodata->email);
				$formatted_test_scores = _nscc_orientation_get_test_scores($participant->sid);
			}
		
			$output .="<tr class=\"\"><td class=\"column-action\"><a title=\"Remove this participant from this orientation session\" href=\"delete-participant/".$participant->participant_id."\">Delete</a></td><td class=\"column-sid\">".$participant->sid."</td><td class=\"column-name\">".$participant->participant_name."</td><td class=\"column-type\">".$participant->student_type."</td><td class=\"column-dtg\">".date('M d, Y H:m',$participant->signup_datetime)."</td><td class=\"column-program\">".$participant->participant_program."</td><td class=\"column-testscore\">".$participant->test_score_plan."</td><td class=\"column-email\"><a href=\"mailto:".$participant->participant_email."\">".$participant->participant_email."</a></td></tr>\n";
			if($formatted_test_scores){
				$output .="<tr class=\"\"><td class=\"spacer\" colspan=\"5\"></td><td class=\"column-test-scores\" colspan=\"2\">".$formatted_test_scores."</td></tr>\n";
			}
			if(($participant->participant_email) && ( ! in_array(strtolower(trim($participant->participant_email)),$bcclist) ) ){
					$bcclist[]=strtolower(trim($participant->participant_email));					
			}
		}	
		$output .= "</tbody></table>\n";
		if($bcclist){
			$bcc_string = implode(";",$bcclist);
			$output .= '<a href="mailto:advisornorth@seattlecolleges.edu?subject=Reminder of Upcoming Orientation Session&body=Enter Message Here&bcc='.$bcc_string.'"';
			$output .=">Send an Email to this whole Roster</a><br>\n";
		}
		$output .= l('Export this Roster','manage/orientation/session/'.$session_id.'/export-roster',array('attributes'=>array('class'=>'session-list-link')))."<br>\n";
		$output .= l('Back to Sessions List','manage/orientation/session',array('attributes'=>array('class'=>'session-list-link')));
	} else {
		$output = "No Such Session.";
	}

	return $output;
}

function _nscc_orientation_session_export($session_id){
			drupal_set_header('Content-Type: application/x-msexcel');
    	drupal_set_header("Content-Disposition: attachment; filename=NSO_Roster.xls");
	    if (function_exists('mb_convert_encoding')) {
      	$output = chr(255) . chr(254);
    	}
    	$header_row = '"Checked In"'."\t".'"SID"'."\t".'"Type"'."\t".'"Name"'."\t".'"Program"'."\t".'"Test Plan"'."\t".'"Email"'."\t".'"Signed Up"'."\n";
 		  if (function_exists('mb_convert_encoding')) {
    		$header_row = mb_convert_encoding($header_row, 'UTF-16LE', 'UTF-8');
    	}
			$output .= $header_row;
			$get_roster_sql = "SELECT * FROM {nscc_orientation_participant} WHERE session_id = %d order by participant_name;";
			$result = db_query(db_rewrite_sql($get_roster_sql),$session_id);
			while($participant = db_fetch_object($result)){
				if($participant->sid !=''){
					$student_type = _nscc_orientation_get_student_type($participant->sid);
					$biodata = _nscc_orientation_get_input_bioextract($participant->sid);
					$participant->participant_name = $biodata->fullname;
					$participant->participant_email = $biodata->email;
					$participant->student_type = $student_type;
				}

				$row = '""'."\t".'"'.$participant->sid.'"'."\t".'"'.$participant->student_type.'"'."\t".'"'.$participant->participant_name.'"'."\t".'"'.$participant->participant_program.'"'."\t".'"'.$participant->test_score_plan.'"'."\t".'"'.$participant->participant_email.'"'."\t".'"'.date('M d, Y H:m',$participant->signup_datetime).'"'."\n";
				if (function_exists('mb_convert_encoding')) {
    		  $row = mb_convert_encoding($row, 'UTF-16LE', 'UTF-8');
    		}
				$output .= $row;
		 }
		 print $output;

}
function _nscc_orientation_delete_participant($session_id,$participant_id){
	$delete_participant_sql = "DELETE FROM {nscc_orientation_participant} WHERE session_id=%d and participant_id = %d";
	$result = db_query(db_rewrite_sql($delete_participant_sql),array($session_id,$participant_id));
	if($result){
		drupal_set_message("You've removed participant $participant_id from session $session_id");
	} else {
		drupal_set_message("Error removing participant $participant_id from session $session_id");
	}
	drupal_goto("manage/orientation/session/".$session_id."/view-roster");
}

function _nscc_orientation_update_participant($sid,$name,$email){
	//watchdog('orient_test','Updating participant: '.$sid." ".$name." ".$email);
	$sql = "UPDATE {nscc_orientation_participant} SET participant_name='%s',participant_email='%s' WHERE sid='%s';";
	$result = db_result(db_query(db_rewrite_sql($sql),$name,$email,$sid));
	return true;
}

function _nscc_orientation_participant_add_form($questionable_garbage,$session_id){
	drupal_add_js(drupal_get_path('module', 'nscc_orientation') .'/nscc_orientation.js');
  drupal_add_css(drupal_get_path('module', 'nscc_orientation') .'/nscc_orientation.css');
	if ($session_id){
		$get_session_sql = "SELECT * FROM {nscc_orientation_session} where session_id = %d;";
		$session_data = db_fetch_object(db_query(db_rewrite_sql($get_session_sql),$session_id));
		$yrq_array = _nscc_orientation_get_yrq_list();
		
		$form['session_id']= array(
			'#type'=>'value',
			'#value'=>$session_id,
		);
		$form['session_display'] = array(
			'#type'=>'markup',
			'#value'=>_nscc_orientation_single_session_out($session_id),
		);	
		$form['sid'] = array(
			'#title'=>t('SID'),
			'#type'=>'textfield',
			'#size'=>9,
			'#description'=>t('Your SID'),
			'#required'=>true,
			'#default_value'=>'',
		);
		$form['pin'] = array(
			'#title'=>t('PIN'),
			'#type'=>'password',
			'#size'=>6,
			'#description'=>t('Your PIN'),
			'#required'=>true,
			'#default_value'=>'',
		);
		$form['test_score_plan'] = array(
			'#title' => t('Placement Test Scores'),
			'#type' => 'radios',
			'#description' => t('Indicate your plans with respect to Placement Tests'),
			'#required' => true,
			'#options' => array(
											'local score'=>t('I will bring my CURRENT (within the last 2 years for English, 1 year for Math) NSCC test scores to the orientation.'),
											'other score'=>t('I will bring my CURRENT (within the last 2 years for English, 1 year for Math) test scores from some other institution to the orientation'),
											'transcript'=>t('I will bring a transcript showing college-level Math and English courses to the orientation'),
										),
		);
		
		$form['participant_program'] = array(
			'#title' => t('Program'),
			'#type' => 'select',
			'#description' => t('Select Your Program.'),
			'#required' => true,
			'#options' => _nscc_orientation_get_program_list(),
		);
		$form['arrival_message'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="form-item">Please arrive 15-20 minutes early to check in for New Student Orientation.</div>'."\n",
		);
		$form['disability_message'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="form-item">Please contact <a href="mailto:ds@seattlecolleges.edu">ds@seattlecolleges.edu</a> to arrange a sign language interpreter or other accommodations for this session. We request one week&rsquo;s notice to arrange accommodations.</div>'."\n",
		);
		$form['contact_message'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="form-item">If you believe you are experiencing technical issues with online registration, please email <a href="mailto:Jillian.Fisher@seattlecolleges.edu">Jillian.Fisher@seattlecolleges.edu</a> with your first and last name, student ID number, program of study, and placement test score option.</div>'."\n",
		);
		$form['submit'] = array(
			'#type'=>'submit',
			'#value'=>'Sign Up',
		);								
	}	  
  return $form;
}

function _nscc_orientation_participant_add_form_validate($form,&$form_state){
	if(! $form_state['values']['session_id']){
		form_set_error('submit', 'No such Session');
	}
	$response_array = _nscc_wts_authverify($form_state['values']['sid'],$form_state['values']['pin']);
	//watchdog('orient_login',"<pre>".$response_array."</pre>");
	if ($response_array['success']==false){
		form_set_error($response_array['error_field'],$response_array['error_msg']);
	}
}

function _nscc_orientation_participant_add_form_submit($form,&$form_state){
	$student_biodata = _nscc_orientation_get_input_bioextract($form_state['values']['sid']);

	$record = new stdClass();
//	$record->participant_email = $form_state['values']['participant_email'];
	$record->participant_email = $student_biodata->email;
	$record->session_id = $form_state['values']['session_id'];
//	$record->participant_name = $form_state['values']['participant_last_name'].", ".$form_state['values']['participant_first_name'];
	$record->participant_name = $student_biodata->fullname;
	$record->sid = $form_state['values']['sid'];
	$record->test_score_plan = $form_state['values']['test_score_plan'];
	$record->participant_program = $form_state['values']['participant_program'];
	$record->signup_datetime = time();

	if (drupal_write_record('nscc_orientation_participant',$record) ){	
			$form_state['redirect'] = 'advising/new-student-orientation-signup';
			drupal_set_message("You're all signed up! We look forward to seeing you at the orientation.");
	}
	
	if ($record->participant_email){
		$get_session_sql = "SELECT * FROM {nscc_orientation_session} where session_id = %d;";
		$session_data = db_fetch_object(db_query(db_rewrite_sql($get_session_sql),$form_state['values']['session_id']));
		$email_params['location'] = $session_data->session_location;
		$email_params['date'] = date('F j, Y',$session_data->session_datetime);
		$email_params['time'] = date('g:i',$session_data->session_datetime);
		drupal_mail('nscc_orientation','signup_confirmation',$record->participant_email,language_default(),$email_params,'Orientation-robot@northseattle.edu');	
		//watchdog('mail_test','Session: '.print_r($session_data,true));
		//watchdog('mail_test','params: '.print_r($email_params,true));
	}
}

function _nscc_orientation_get_input_bioextract($sid){
	_orientation_checkadd_sm_db();
	db_set_active('sm');
	$sql = "SELECT \"FullName\" as fullname,\"Email\" as email FROM sm.student_orientation_bioextract WHERE \"SID\"='%s';";
	$biodata = db_fetch_object(db_query($sql,$sid));
	db_set_active('default');
	return $biodata;
}

function _nscc_orientation_get_student_type($sid){
	_orientation_checkadd_sm_db();
	db_set_active('sm');
	$sql = "SELECT \"StudentTypeID\" as student_type FROM sm.student_orientation_bioextract WHERE \"SID\"='%s';";
	$student_type = db_result(db_query($sql,$sid));
	db_set_active('default');
	return $student_type;
}


function _nscc_orientation_get_test_scores($sid){
	_orientation_checkadd_sm_db();
	db_set_active('sm');
	$sql = "SELECT * FROM sm.tests_collapsed WHERE sid='%s';";
	$result = db_query($sql,$sid);
	while($score_row = db_fetch_object($result)){
		$formatted_test_scores .= "<tr><td class=\"column-test-scores-cc\">".$score_row->college_code."</td><td class=\"column-test-scores-date\">".$score_row->test_date."</td><td class=\"column-test-scores-english\">".$score_row->english."</td><td class=\"column-test-scores-math\">".$score_row->math."</td></tr>";
	}
	db_set_active('default');
	//watchdog('orient_test','Formatted test scores: '.$formatted_test_scores);
	if ($formatted_test_scores){
		$formatted_test_scores = "<table class=\"table-test-scores\"><thead><tr><th class=\"column-test-scores-cc\">College</th><th class=\"column-test-scores-date\">Date</th><th class=\"column-test-scores-english\">English</th><th class=\"column-test-scores-math\">Math</th></tr></thead>".$formatted_test_scores."</table>";
		return $formatted_test_scores;
	} else {
		return '';
	}
}

function _nscc_orientation_get_yrq_list(){
	/*
	$yrq_array = array(
		'B012'=>'Fall 2010',
		'B013'=>'Winter 2011',
		'B014'=>'Spring 2011',
		'B111'=>'Summer 2011',
		'B112'=>'Fall 2011',
	);
	return $yrq_array;
	*/
	$how_far_to_go = 6;
	$current_yrq = _schedule_get_next_starting_yrq('all');
	$quarter_list = array();
	$quarter_name_list = array();
	for($i = 1; $i <= $how_far_to_go; $i++) {
		$quarter_details = _schedule_get_quarter_details($current_yrq);
		if($quarter_details){
			$quarter_list[$i] = $current_yrq;
			$qtr_name = _schedule_yrq_to_quarter($current_yrq);
			//$qtr_start = date('M j', strtotime($quarter_details->first_day_yrq));
			$qtr_start = date('M j',_schedule_hpdate_to_date($quarter_details->first_day_yrq));
			//$qtr_end = date('M j', strtotime($quarter_details->last_day_yrq));
			$qtr_end = date('M j',_schedule_hpdate_to_date($quarter_details->last_day_yrq));
			//$quarter_name_list[$i] = "$qtr_name ($qtr_start - $qtr_end)";
			$quarter_name_list[$i] = $qtr_name;
		}
		$current_yrq = _schedule_increment_yrq($current_yrq,false);
  }

  return array_combine($quarter_list,$quarter_name_list);
}

function _nscc_orientation_get_program_list(){
	$program_array = array(
		''=>'Please Select a Program of Study',
		'College Transfer'=>array(
			'Transfer_AA'=>'Transfer - AA degree',
			'Transfer_AB'=>'Transfer - AB degree',
			'Transfer_AS'=>'Transfer - AS degree',
			'Transfer_Undecided'=>'Transfer - Undecided',
		),
		'Career Training (Non-Transfer)'=>array(
			'Accounting'=>'Accounting',
			'Arch_Eng_Tech'=>'Architectural Eng. Tech',
			'Business'=>'Business',
			'Communication'=>'Communication',
			'Computing_IT'=>'Computing/Information Tech',
			'Early_Childhood_Education'=>'Early childhood Education',
			'Electronics'=>'Electronics',
			'Emergency Medical Technician'=>'Emergency Medical Technician',
			'HVAC'=>'Heating, Ventilation, Air Condition (HVAC)',
			'Medical Assisting'=>'Medical Assisting',
			'Nanotechnology'=>'Nanotechnology',
			'Nursing (LPN)'=>'Nursing (LPN)',
			'Pharmacy Technician'=>'Pharmacy Technician',
			'Real Estate'=>'Real Estate',
			'Career_Undecided'=>'Undecided',
		),
		'Post_Bach'=>'Post-baccalaureate Coursework',
	);
	return $program_array;
}

function _nscc_orientation_single_session_out($session_id){
	$get_session_sql = "SELECT * FROM {nscc_orientation_session} where session_id = %d;";
	$session_data = db_fetch_object(db_query(db_rewrite_sql($get_session_sql),$session_id));
	$session_count = _nscc_orientation_get_session_count($session_id);
	$yrq_array = _nscc_orientation_get_yrq_list();
	$output .= "<table class=\"orientation-sessions-list\">\n";
	$output .="<tr class=\"column-heads\"><td class=\"column-yrq\">Year/Quarter</td><td class=\"column-dtg\">Date/Time</td><td class=\"column-location\">Location</td><td class=\"column-cap\">Cap</td><td class=\"column-count\">Count</td></tr>\n";
	$output .="<tr class=\"\"><td class=\"column-yrq\">".$yrq_array[$session_data->session_yrq]."</td><td class=\"column-dtg\"><span class=\"date\">".date('M d, Y',$session_data->session_datetime)."</span> <span class=\"time\">".date('h:iA',$session_data->session_datetime)."</span></td><td class=\"column-location\">"._nscc_orientation_locator_link(strtoupper($session_data->session_location))."</td><td class=\"column-cap\">".$session_data->session_cap."</td><td class=\"column-count\">".$session_count."</td>";
	$output .="</tr>\n";
	$output .= "</table>\n";
	return $output;
}

function _nscc_orientation_get_session_count($session_id){
	return db_result(db_query(db_rewrite_sql("select count(*) from {nscc_orientation_participant} where session_id=%d;"),$session_id));
}

function _nscc_orientation_get_session_remaining_seats($session_id){
	$session_count = _nscc_orientation_get_session_count($session_id);
	$session_cap = db_result(db_query(db_rewrite_sql("select session_cap from {nscc_orientation_session} where session_id=%d;"),$session_id));
	return $session_cap - $session_count;
}

function _nscc_orientation_locator_link($room){
	return "<span  class=\"location\" title=\"Location\"><a class=\"location\" href=\"http://prod.northseattle.edu/locator/locate/".$room."\">".$room."</a></span>";
}

function nscc_orientation_mail($key, &$message, $params){
	switch($key){
		case 'signup_confirmation':
			$message['subject']='NSCC Orientation Session Confirmation';
			$orientation_date=$params['date'];
			$orientation_time=$params['time'];
			$orientation_location=$params['location'];
			$message['body'] = <<<end_of_message
Hello,

Thank you so much for signing up for North Seattle College's START New Student Orientation!  We are excited that you have chosen NSC and we look forward to working with you.

Before Orientation: 
	1.	Check your email
		a.	One day prior to the orientation session, you will receive an email with more detailed instructions on what to bring, where to go, a map, and more.
	2.	Complete placement testing if necessary
		a.	You can find more information at https://northseattle.edu/testing
		b.	Test scores and/or previous math courses being used for Math placement must be from within the last year. 
		c.	Test scores being used for English placement must be from within the last 2 years; previous college-level English classes do not expire.
	3.	Make sure your SID and PIN are working
		a.	If you need assistance, go to https://northseattle.edu/online-services/sidpin-information for more information. 

If you have any questions related to START New Student Orientation, please contact Jillian Fisher at jillian.fisher@seattlecolleges.edu

We look forward to seeing you soon!



end_of_message;
		break;
		
		case "reminder":
			$message['subject'] = 'Reminder: NSCC Orientation Session';		
			$orientation_date = $params['date'];
			$orientation_time = $params['time'];
			$orientation_location =$params['location'];
			$message['body'] = <<<end_of_message
Dear New Student,

This is a reminder that you have signed up to attend a New Student Orientation at North Seattle College on $orientation_date at $orientation_time, located in $orientation_location.
If you need directions to either NSC or the orientation room, you can access maps & direction information here: http://northseattle.edu/directions. From that website, you can click on the ÒOn CampusÓ tab to access a map of the NSC campus.
We look forward to seeing you!

Please arrive 15-20 minutes early to check in.

Please remember to bring one of:
 -- SCCD COMPASS scores
 -- Recent COMPASS scores (2 years for English, 1 year for Math) from another institution
 -- A transcript showing college-level English and Math courses.

end_of_message;
		break;
  }
}

function _orientation_checkadd_sm_db() {

	global $db_url;

	// If current $db_url is not an array make it one (and don't forget to insert the default connection)
	if (!is_array($db_url)) {
		$default = $db_url;
		$db_url = array();
		$db_url['default'] = $default;
	}

  // Add the new reference
	if(!$db_url['sm']){
		$db_url['sm'] = 'pgsql://sm_viewer:83jge94gledifl@onering.inf/nscc';
	}
}

