<?php

/**
 * @param array $suggestions
 * @param array $variables
 */
function svi_heros_theme_suggestions_page_alter(array &$suggestions, array $variables)
{
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
        $content_type = $node->bundle();
        if (!empty($content_type)) {
            $tokens = explode('-', trim($content_type));
            $twigName = implode('__', $tokens);
            $suggestions[] = 'page__' . $twigName;
        }
        $node_name = $node->getTitle();
        if (isset($node_name)) {
            $tokens = explode('-', trim($node_name));
            $twigName = implode('__', $tokens);
            $suggestions[] = 'page__' . $twigName;

        }
    }
}


function svi_heros_theme_suggestions_block_alter(array &$suggestions, array $variables)
{
    $content = $variables['elements']['content'];
    if (isset($content['#block_content']) && $content['#block_content'] instanceof \Drupal\block_content\BlockContentInterface) {
        $suggestions[] = 'block__' . $content['#block_content']->bundle();
    }
}


function svi_heros_preprocess_breadcrumb(&$variables)
{
    $request = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    $page_title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
    //this variable will avaliable in twig file.
    $variables['current_page_title'] = $page_title;
}

function svi_heros_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if (isset($form_id) && strcmp($form_id, 'search_form') == 0) {
        $form['#method'] = "get";
    }

}

function svi_heros_page_attachments_alter(array &$attachments)
{
    $request = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    $page_title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
    if ($page_title === 'Directory') {
        $attachments['#attached']['library'][] = 'svi_heros/table-styling';
    }


}

function svi_heros_theme_suggestions_form_alter(array &$suggestions, array $variables)
{
    if ($variables['element']['#form_id']) {
        $suggestions[] = 'form__' . $variables['element']['#form_id'];
    }
}


function svi_heros_form_contact_message_feedback_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{

    // Name
    $form['name']['#prefix'] = '<div class="row"><div class="col-md-6"><div class="form-group">';
    $form['name']['#suffix'] = '</div>';
    $form['name']['#attributes']['placeholder'][] = $form['name']['#title'] . '*';
    $form['name']['#attributes']['class'][] = 'form-control';
    unset($form['name']['#title']);

    // Mail
    $form['mail']['#prefix'] = '<div class="form-group">';
    $form['mail']['#suffix'] = '</div>';
    $form['mail']['#attributes']['placeholder'][] = $form['mail']['#title'] . '*';
    $form['mail']['#attributes']['class'][] = 'form-control';
    unset($form['mail']['#title']);


    // Subject
    $form['subject']['widget'][0]['value']['#attributes']['class'][] = 'form-control';
    $form['subject']['widget'][0]['value']['#attributes']['placeholder'][] = $form['subject']['widget'][0]['#title'] . '*';
    $form['subject']['widget'][0]['#title'] = '';
    unset($form['subject']['widget'][0]['value']['#title']);
    $form['subject']['widget'][0]['#prefix'] = '<div class="form-group">';
    $form['subject']['widget'][0]['#suffix'] = '</div></div>';

    // Message
    $form['message']['widget'][0]['value']['#attributes']['class'][] = 'form-control';
    $form['message']['widget'][0]['value']['#attributes']['placeholder'][] = $form['message']['widget'][0]['#title'] . '*';
    $form['message']['widget'][0]['#title'] = '';
    unset($form['message']['widget'][0]['value']['#title']);
    $form['message']['widget'][0]['#prefix'] = '<div class="col-md-6"><div class="form-group">';
    $form['message']['widget'][0]['#suffix'] = '</div></div></div>';

    // Submit
    $form['actions']['#prefix'] = '<div class="clearfix">';
    $form['actions']['#suffix'] = '</div>';
    $form['actions']['submit']['#attributes']['class'][] = 'btn';
    $form['actions']['submit']['#attributes']['class'][] = 'btn-success';
    $form['actions']['submit']['#attributes']['class'][] = 'pull-right';
    if (strpos($form_id, 'contact_message_') !== FALSE) {
        $form['actions']['preview']['#access'] = FALSE;
    }

}

function svi_heros_preprocess_page_title(&$variables)
{
    $request = \Drupal::request();
    if ($route = $request->attributes->get(\Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
        $title = \Drupal::service('title_resolver')->getTitle($request, $route);
        if (strcmp($title, 'Search') == 0) {
            $variables['title'] = 'Search Seattle Vocational Institute';
        }
    }
}