<?php

//function nscc_disability_services_init(){}
//function nscc_disability_services_help(){}
//function nscc_disability_services_menu(){}

function nscc_disability_services_block($op='list', $delta=0,$edit=array()){
	switch ($op){
		case 'view':
			$block=array();
			switch($delta){
				case 0:
					//Disability services request form
					$block['subject'] = "Disabilities Service Request";
					$block['content'] = _nscc_disability_services_request_block();
					return $block;
			}
		case 'list':
			$blocks[0]['info'] = t('NSCC Disabilities Service Request');
			$blocks[0]['cache'] = BLOCK_CACHE_GLOBAL;
			return $blocks;
	}
}


function _nscc_disability_services_request_block(){
	return drupal_get_form('_nscc_disability_services_request_form');
};


//function nscc_disability_services_perm(){}

//function nscc_disability_services_mail(){}

function _nscc_disability_services_request_form($form_state){
	drupal_add_css(drupal_get_path('module', 'nscc_disability_services') .'/nscc_disability_services.css');
	//if not authenticated, do auth form.
	if($_SESSION['nscc_wts']['status']!='Authenticated'){
		$form=_nscc_wts_get_signin_form_elements("Sign in to request services!");
	} else {
		if($_SESSION['nscc_disability_services']['yrq']==''){
			$form['yrq'] = array(
				'#type'=>'select',
				'#title'=>'Quarter',
				'#options'=>_schedule_get_active_yrqs(),
				'#description'=>'Please indicate which quarter this request is for.', 
			);
			$form['set_yrq'] = array(
				'#type' => 'submit',
				'#value' => t('Submit'),
				'#validate' => array('_nscc_disability_services_yrq_validate'),
				'#submit' => array('_nscc_disability_services_yrq_submit'),
			);
			
		} else {
			$form['yrq']=array(
				'#type'=>'value',
				'#value'=>$_SESSION['nscc_disability_services']['yrq'],
			);
		
			//for right now this just presents a signout button, but this is where the form proper starts
			//first a block of biodata pulled from SM,probably just the name displays
			$biodata = _nscc_disability_services_get_biodata($_SESSION['nscc_wts']['sid']);
			//stash biodata as values fields
			$form['sid']=array(
				'#type'=>'value',
				'#value'=>$biodata->SID,
			);
			$form['firstname']=array(
				'#type'=>'value',
				'#value'=>$biodata->FirstName,
			);
			$form['lastname']=array(
				'#type'=>'value',
				'#value'=>$biodata->LastName,
			);
			$form['mi']=array(
				'#type'=>'value',
				'#value'=>$biodata->MiddleInitial,
			);
			$form['address']=array(
				'#type'=>'value',
				'#value'=>$biodata->Address."\n".$biodata->City.", ".$biodata->State." ".$biodata->Zip
			);
			$form['dayphone']=array(
				'#type'=>'value',
				'#value'=>$biodata->DaytimePhone,
			);
			$form['eveningphone']=array(
				'#type'=>'value',
				'#value'=>$biodata->EveningPhone,
			);
			$form['email']=array(
				'#type'=>'value',
				'#value'=>$biodata->Email,
			);
			
			$form['contact_options'] = array(
				'message'=>array(	
					'#type'=>'markup',
					'#value'=>'<div class="nscc-disability-services-form-instructions">Please choose the best way to contact you:</div>'
				),
				'preferred_contact_method'=>array(
					'#type'=>'radios',
					'#title'=>'',
					'#attributes'=>array('class' => 'nscc-disabilites-services-request-preferred-contact'),
					'#options'=>array(
						$biodata->Email => 'Email: '.$biodata->Email,
						$biodata->DaytimePhone => 'Day Phone: '.$biodata->DaytimePhone,
						$biodata->EveningPhone => 'Night Phone: '.$biodata->EveningPhone,
						'Alt_phone' => 'Alternate Phone: (Specified below)',
					),
					'#description' => '',
					'#default_value' => ''
				),
				'alt_phone'=>array(
					'#type' => 'textfield',
					'#title' => 'Alternate Phone',
					'#attributes'=>array('class' => 'nscc-disabilites-services-request-alt-phone'),
					'#size'=>12,
					'#maxlength'=>10,
					'#description'=>'<div class="nscc-disability-services-form-instructions">If you select Alternate Phone above, please give us the number here.</div>'
				),
				'voicemail_ok'=>array(
					'#type'=>'checkboxes',
					'#attributes'=>array('class' => 'nscc-disabilites-services-request-voicemail-ok'),
					'#options'=>array('ok'=>'It is OK to leave a detailed voice message including the department name and the reason for the call'),
				),
			);
	
			$form['general_accommodations'] = array(
			
				'exam_accommodations' => array(
					'#type'=>'checkboxes',
					'#attributes'=>array('class' => 'nscc-disabilites-services-request-exams'),	
					'#options'=>array('exam'=>'Exam Accommodations'),
					'#description'=>'Checking this box will cause Disability Services to send Letters of Accommodation to your instructors notifying them of this request.  You will have to follow up with your instructor to discuss Testing Center arrangements.'
				),
				'note_taking'=>array(
					'#type'=>'checkboxes',
					'#attributes'=>array('class' => 'nscc-disabilites-services-request-notes'),
					'#options'=>array('notes'=>'Notetaking'),
					'#description'=>'Checking this box will cause Disability Services to send Letters of Accommodation to your instructors notifying them of this request.  You will have to follow up with your instructors, asking that they make a notetaking announcement to the class.'
				),
				'interpreting'=>array(
					'#type'=>'checkboxes',
					'#title'=>'Interpreting',
					'#attributes'=>array('class' => 'nscc-disabilites-services-request-interpreting'),
					'#options'=>array('ASL'=>'ASL','PSE'=>'PSE','SEE'=>'SEE','Oral'=>'Oral','CART'=>'CART','TypeWell'=>'TypeWell'),
					'#description'=>'Please check all Interpreters you request.',
				),
				'alternative_format'=>array(
					'#type'=>'checkboxes',
					'#attributes'=>array('class' => 'nscc-disabilites-services-request-alt-format'),
					'#options'=>array('alt_format'=>'Alternative Format Textbooks'),
					'#description'=>'If you require your textbooks in an alternate format, come meet with us in the Disability Services office.'
				),
			);
			$items = _nscc_disability_services_get_items($biodata->SID,$_SESSION['nscc_disability_services']['yrq']);
			if($items){
			$form['class_accomodations'] = array('#tree'=>true,);
			//$form['class_accomodations']
				foreach($items as $item){
					$item_rows = _nscc_disability_services_get_item_rows($item,$_SESSION['nscc_disability_services']['yrq']);
					if($item_rows){
						$form['class_accomodations']['start_'.$item]=array(
							'#type'=>'markup',
							'#value'=>'<div class="nscc-disabilities-services-request-item">',
						);
						foreach($item_rows as $item_row){
							$form['class_accomodations'][$item_row->item.'_'.$item_row->loc] = array(
								'class_info'=>array(
									'#type'=>'markup',
									'#value'=> '<span class="nscc-disabilities-services-request-course">'.$item_row->course.'</span><br><span class="nscc-disabilities-services-request-loc">Room: '.$item_row->loc.'</span> | <span class="nscc-disabilities-services-request-days">Days: '.$item_row->days.'</span> | <span class="nscc-disabilities-services-request-times">Times: '.$item_row->times.'</span>',
								),
								'item'=>array(
									'#type'=>'value',
									'#value'=>$item_row->item,
								),
								'room'=>array(
									'#type'=>'value',
									'#value'=>$item_row->loc,
								),
								'days'=>array(
									'#type'=>'value',
									'#value'=>$item_row->days,
								),
								'times'=>array(
									'#type'=>'value',
									'#value'=>$item_row->times,
								),
								'equipment' => array(
									'#type'=>'checkboxes',
									'#attributes'=>array('class' => 'nscc-disabilites-services-request-class-equipment form-checkboxes'),
									'#options'=>array('Table'=>'Table','Chair'=>'Chair','Recorder'=>'Recorder','Keyboard'=>'Keyboard','Mouse'=>'Mouse'),
								),
								'other_accommodation_css_clear'=>array(
									'#type'=>'markup',
									'#value'=>'<div class="nscc-disabilites-services-request-class-equipment-float-clear"></div>'
								),	
								'other_accomodation'=>array(
									'#type' => 'textarea',
									'#attributes'=>array('class' => 'nscc-disabilites-services-request-class-other'),
									'#title' => 'Other',
								),
							);	
						}
						if (preg_match('/^Also Meets/',$item_row->course) ){
							$form['class_accomodations'][$item_row->item.'_'.$item_row->loc]['class_info']['#value'] = '<span class="nscc-disabilities-services-request-course-ami"> </span><span class="nscc-disabilities-services-request-loc item-float">Room: '.$item_row->loc.'</span> | <span class="nscc-disabilities-services-request-days item-margin-left item-float">Days: '.$item_row->days.'</span> | <span class="nscc-disabilities-services-request-times item-float">Times: '.$item_row->times.'</span>';
						}
					
						$form['class_accomodations']['end_'.$item]=array(
							'#type'=>'markup',
							'#value'=>'</div>',
						);
					
					}
				}
			}
			//submit button			
			$form['submit'] = array(
				'#type' => 'submit',
				'#value' => t('Send Request'),
				'#attributes'=>array('class'=>'item-float'),
				'#validate' => array('_nscc_disability_services_yrq_submit'),
				'#submit' => array('_nscc_disability_services_request_form_submit'),

			);
			//$_SESSION['nscc_disability_services']['yrq'] = $form_state['values']['yrq'];			
		}			
	}
	return $form;
}

function _nscc_disability_services_yrq_validate($form,&$form_state){

		$_SESSION['nscc_disability_services']['yrq'] = $form_state['values']['yrq'];
}

function _nscc_disability_services_yrq_submit($form,&$form_state){
	//bogus function here to prevent a regular submit at the earlier stage of the form.
}

function _nscc_disability_services_request_form_validate($form, &$form_state){
	watchdog('nds','validated request form. Session:<pre>'.print_r($_SESSION,true).'</pre>');
}

function _nscc_disability_services_request_form_submit($form, &$form_state){
	//clear wts credentials from session	
	//_nscc_wts_signout_form_elements_submit($form,&$form_state);
	//clear our settings from session
	$_SESSION['nscc_wts']['sid'] = '';
	$_SESSION['nscc_wts']['status'] = 'Unauthenticated';
	$_SESSION['nscc_disability_services']='';
	$_SESSION['nscc_wts']='';
	$destination_email = "DS@seattlecolleges.edu";
	$body_params = $form_state['values'];
	drupal_mail('nscc_disability_services','service_request',$destination_email,language_default(),$body_params,'sam.bayne@seattlecolleges.edu');
	drupal_set_message('Your request has been submitted. Thank you.');
}


function nscc_disability_services_mail($key, &$message, $params){
	switch($key){
		case 'service_request':
			$message['subject'] = 'Disability Services Request for '.$params['firstname'].' '.$params['lastname'];
			//$message['headers']['Reply-to'] = $params['email'];
			$message['body']  = "\n\n";
			$message['body']  .= "Client: {$params['firstname']} {$params['mi']} {$params['lastname']} -- {$params['sid']}\n";
			if($params['preferred_contact_method'] == 'Alt_phone'){
				$message['body']  .= "Preferred Contact: {$params['alt_phone']}\n";
			} else {
				$message['body']  .= "Preferred Contact: {$params['preferred_contact_method']}\n";
			}
			$message['body']  .= (strcmp($params['voicemail_ok']['ok'],'ok')==0) ? "Voicemail: OK\n":"Voicemail: No\n";
			
			$message['body']  .= "General Accommodations Requested for quarter {$params['yrq']}:\n";		
			$message['body']  .= (strcmp($params['exam_accommodations']['exam'],'exam')==0) ? "\tExam Accomodations\n":"";
			$message['body']  .= (strcmp($params['note_taking']['notes'],'notes')==0) ? "\tNote Taking Assistance\n":"";
			$message['body']  .= (strcmp($params['alternative_format']['alt_format'],'alt_format')==0) ? "\tAlternate Format Texts\n":"";
			$message['body']  .= "\tInterpreters Requested:\n";		
			$message['body']  .= (strcmp($params['interpreting']['ASL'],'ASL')==0) ? "\t\tASL\n":"";
			$message['body']  .= (strcmp($params['interpreting']['PSE'],'PSE')==0) ? "\t\tPSE\n":"";
			$message['body']  .= (strcmp($params['interpreting']['SEE'],'SEE')==0) ? "\t\tSEE\n":"";
			$message['body']  .= (strcmp($params['interpreting']['Oral'],'Oral')==0) ? "\t\tOral\n":"";
			$message['body']  .= (strcmp($params['interpreting']['CART'],'CART')==0) ? "\t\tCART\n":"";
			$message['body']  .= (strcmp($params['interpreting']['TypeWell'],'TypeWell')==0) ? "\t\t{$params['interpreting']['TypeWell']}\n":"";
			$message['body']  .= "Per-Class Accommodations Requested for quarter {$params['yrq']}:\n";		
			foreach($params['class_accomodations'] as $item_id=>$item_array){
				$message['body'] .="\tItem:{$item_array['item']} in {$item_array['room']} on ".trim($item_array['days'])." at {$item_array['times']}:\n";
				$message['body']  .= (strcmp($item_array['equipment']['Desk'],'Desk')==0) ? "\t\tDesk\n":"";
				$message['body']  .= (strcmp($item_array['equipment']['Chair'],'Chair')==0) ? "\t\tChair\n":"";
				$message['body']  .= (strcmp($item_array['equipment']['Recorder'],'Recorder')==0) ? "\t\tRecorder\n":"";
				$message['body']  .= (strcmp($item_array['equipment']['Keyboard'],'Keyboard')==0) ? "\t\tKeyboard\n":"";
				$message['body']  .= (strcmp($item_array['equipment']['Mouse'],'Mouse')==0) ? "\t\tMouse\n":"";
				$message['body']  .= (strcmp($item_array['other_accomodation'],"")!=0) ? "\t\tOther: {$item_array['other_accomodation']}\n":"";
			}
			//$message['body']  .= print_r($params,true);
			
			$message['body']  .= "\n";
			//$message['body'] .= 'line 3: '.$params['line_3']."\n";
		break;
	}
}


function _nscc_disability_services_get_biodata($sid){
	_nscc_disability_services_checkadd_db();
	db_set_active('sm');
	$sql = "SELECT * FROM sm.student_orientation_bioextract WHERE \"SID\"='%s';";
	$biodata = db_fetch_object(db_query($sql,$sid));
	db_set_active('default');
	return $biodata;
	
}

function _nscc_disability_services_get_items($sid,$yrq){
	$output_array = array();
	_nscc_disability_services_checkadd_db();
	db_set_active('sm');
	$sql = "SELECT item FROM sm.roster WHERE sid='%s' and yrq='%s';";
	$result = db_query($sql,$sid,$yrq);
	while($record=db_fetch_object($result)){
		$output_array[] = $record->item;
	}
	db_set_active('default');
	return $output_array;
}

function _nscc_disability_services_get_item_rows($item,$yrq){
	$output_array="";
	_nscc_disability_services_checkadd_db();
	db_set_active('class_schedule');
	$sql = "select * from (select 'C' as rtype, item, course||'.'||section as course,loc,days,start_time||'-'::text||end_time as times from class_details where item='%s' and yrq='%s') as cd union (select 'A' as rtype,item,'Also Meets' as course,loc,days,times from also_meets_in where item='%s' and yrq='%s') order by rtype desc;";
	$result=db_query($sql,$item,$yrq,$item,$yrq);
	while ($record = db_fetch_object($result)){	
		$output_array[] = $record;
	}
	db_set_active('default');
	return $output_array;
}


function _nscc_disability_services_checkadd_db() {

	global $db_url;

	// If current $db_url is not an array make it one (and don't forget to insert the default connection)
	if (!is_array($db_url)) {
		$default = $db_url;
		$db_url = array();
		$db_url['default'] = $default;
	}

  // Add the new reference
	if(!$db_url['sm']){
		$db_url['sm'] = 'pgsql://sm_viewer:83jge94gledifl@onering.inf/nscc';
	}
  // Add the new reference
	if(!$db_url['class_schedule']){
		$db_url['class_schedule'] = 'pgsql://schedule_viewer:ty87rcg5@onering.inf/nscc';
	}	
}
