<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */
function fifty_years_scc_theme_suggestions_views_view_alter(array &$suggestions, array $variables)
{
    if (isset($variables['view']->element['#view_id'])) {
        $suggestions[] = 'views_view__' . $variables['view']->element['#view_id'];
    }
}

function fifty_years_scc_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables)
{
    if (isset($variables['view']->element['#view_id'])) {
        $suggestions[] = 'views_view_unformatted__' . $variables['view']->element['#view_id'];
    }
}

function fifty_years_scc_theme_suggestions_container_alter(array &$suggestions, array $variables)
{
    if (isset($variables['element']['#name'])) {
        $suggestions[] = 'container__' . $variables['element']['#name'];
    }
}

function fifty_years_scc_theme_suggestions_form_alter(array &$suggestions, array $variables)
{
    if ($variables['element']['#form_id']) {
        $suggestions[] = 'form__' . $variables['element']['#form_id'];
    }
}


/**
 * @param array $suggestions
 * @param array $variables
 */
function fifty_years_scc_theme_suggestions_page_alter(array &$suggestions, array $variables)
{
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
        $content_type = $node->bundle();
        if(!empty($content_type)){
            $tokens = explode('-', trim($content_type));
            $twigName = implode('__', $tokens);
            $suggestions[] = 'page__' . $twigName;
        }
        $node_name = $node->getTitle();
        if (isset($node_name)) {
            $tokens = explode('-', trim($node_name));
            $twigName = implode('__', $tokens);
            $suggestions[] = 'page__' . $twigName;

        }
    }
}

function fifty_years_scc_preprocess_block(&$variables)
{
    try {
        $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
        $variables['base_path'] = base_path();
    } catch (Exception $e) {
        $variables['is_front'] = FALSE;
    }
}

function fifty_years_scc_preprocess_menu(&$variables, $hook) {
    try {
        $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
    } catch (Exception $e) {
        $variables['is_front'] = false;
    }
}

