<?php

//Strategic Plan Module
//tokenizing the report index field makes it available for URL aliases --part 1
function nscc_stratplan_token_values($type, $object = NULL, $options = array()) {
    $values = array();

    switch($type) {
        case 'node' :
            $node = $object;

            $values['Report Index'] = $node->field_report_index[0]['value'];
            break;
    };

    return $values;
};


//tokenizing the report index field makes it available for URL aliases --part 2
function nscc_stratplan_token_list($type = 'all'){

    if ($type == 'node' || $type == 'all'){

        $tokens['node']['Report Index'] = t('The value of the Report Index field');

    };

    return $tokens;
};
