<?php
$wts_error_msg='';
define("WTS_RQ_URL",'https://wts.seattlecolleges.edu/scripts/rq063.exe'); //This is the HTTPS url to your rq.exe server process.


function _nscc_wts_get_signin_form_elements($submit_text='Sign in'){
		$form['sid-instructions'] = array(
			'#type'=>'markup',
			'#value'=>'<div class="signin-instructions">You must provide your 9-digit SID number (issued to you when you applied) and PIN (defaults to your birthdate) to proceed.</div>',
		);
		$form['sid'] = array(
			'#type' => 'textfield',
			'#title' => 'SID',
			'#maxlength' => 9,
			'#size' => 9,
			'#required' => true,
			'#default_value'=>$_SESSION['nscc_wts']['sid'],
		);
		$form['pin'] = array(
			'#type' => 'password',
			'#title' => 'PIN',
			'#maxlength' => 6,
			'#size' => 6,
			'#required' => true,
			'#default_value'=>'',
		);
		$form['submit'] = array(
			'#type' => 'submit',
			'#value' => t($submit_text),
			'#validate' => array('_nscc_wts_signin_form_elements_validate'),
			'#submit' => array('_nscc_wts_signin_form_elements_submit'),
		);
		return $form;
}

function _nscc_wts_signin_form_elements_validate($form,&$form_state){
	$response_array = _nscc_wts_authverify($form_state['values']['sid'],$form_state['values']['pin']);
	//watchdog('wts_login',"<pre>".print_r($response_array,true)."</pre>");
	if ($response_array['success']!=1){
			form_set_error($response_array['error_field'],$response_array['error_msg']);
			$_SESSION['nscc_wts']['status'] = 'Unauthenticated';
	} else {
		$_SESSION['nscc_wts']['sid'] = trim($form_state['values']['sid']);
		$_SESSION['nscc_wts']['status'] = 'Authenticated';			
	} 
	//watchdog('wts_login',"session_end_validate:<pre>".print_r($_SESSION['nscc_wts'],true)."</pre>");
}

function _nscc_wts_signin_form_elements_submit($form,&$form_state){
	//watchdog('wts_login',"session_begin_submit:<pre>".print_r($_SESSION['nscc_wts'],true)."</pre>");
}

function _nscc_wts_get_signout_form_elements($submit_text='Sign Out'){
	$form['signout'] = array(
			'#type' => 'submit',
			'#value' => t($submit_text),
			'#validate' => array('_nscc_wts_signout_form_elements_validate'),
			'#submit' => array('_nscc_wts_signout_form_elements_submit'),
		);
	return $form;
}

function _nscc_wts_signout_form_elements_validate($form,&$form_state){
}

function _nscc_wts_signout_form_elements_submit($form,&$form_state){
			$_SESSION['nscc_wts']['sid'] = '';
			$_SESSION['nscc_wts']['status'] = 'Unauthenticated';
}

function _nscc_wts_authverify($sid,$pin){
	global $wts_error_msg;
	global $wts_error_field;
	
	$wts_error_field = 'sid';			
	$output_array['requested_url'] = WTS_RQ_URL;

	$request_type='saddrchg';
	$response_patterns = array(
			'tkt' => "/var tkt='(\w+)';/",
			'timeout' => "/var timeout=' (\w+)';/",
			'refresh' => "/var refresh='(\d+)';/",
			'chgEnabled' => "/var chgEnabled='(\d+)';/",
			'str' => "/var str='(.+)';/",
			'cty' => "/var cty='(\w+)';/",
			'ste' => "/var ste='(\w+)';/",
			'zip' => "/var zip='(\w+)';/",
			'dp1' => "/var dp1='(\w+)';/",
			'dp2' => "/var dp2='(\w+)';/",
			'dp3' => "/var dp3='(\w+)';/",
			'ep1' => "/var ep1='(\w+)';/",
			'ep2' => "/var ep2='(\w+)';/",
			'ep3' => "/var ep3='(\w+)';/",
			'email' => "/var eMail='(\S+)';/",
	);
	$parsed_response_fields = array();

	if (_nscc_wts_validate_sid($sid) && _nscc_wts_validate_pin($pin)){
		$fields = array(	
						'request'=>$request_type,
						'sid'=>$sid,
						'pin'=>$pin
						);
							
		$response = http_parse_message(http_post_fields(WTS_RQ_URL,$fields));
			//print_r($response->body);
	
		if (! _nscc_wts_check_https_status($response) ){
			$output_array['success'] = 0;
			$output_array['error_field'] = 'pin';			
			$output_array['error_msg'] = $wts_error_msg;
			return $output_array;
		}

		if ( preg_match('/You have entered an incorrect\s+<BR>\s+Student ID or PIN/m',$response->body)){
			//auth failure
			$output_array['success'] = 0;
			$output_array['error_field'] = 'pin';			
			$output_array['error_msg'] = "Authentication Failure";			
		} else {

				if(preg_match($response_patterns['tkt'],$response->body)){
					foreach($response_patterns as $name=>$pattern){
						if(preg_match($pattern,$response->body,$match)){
								$parsed_response_fields[$name]=$match[1];
						}
					}
					$output_array['success'] = 1;
					$output_array['response_fields'] = $parsed_response_fields;
				} else {
					$output_array['success'] = 0;
					$output_array['error_msg'] = "Unknown Error returned from server:\n".print_r($response->body,true);
				}		
		}

	} else {
				$output_array['success'] = 0;
				$output_array['error_field'] = $wts_error_field;			
				$output_array['error_msg'] = "Input Validation Failed: ".$wts_error_msg;			
	}
	return $output_array;
}


function _nscc_wts_validate_sid($sid){
	global $wts_error_msg;
	global $wts_error_field;
	if(preg_match('/^\d\d\d\d\d\d\d\d\d$/',$sid)){
		return true;
	} else {
		$wts_error_msg = 'Invalid SID. Your SID is the 9-digit number issued to you when you applied to NSCC.';
		$wts_error_field = 'SID';
		return false;
	}
}

function _nscc_wts_validate_pin($pin){
	global $wts_error_msg;
	global $wts_error_field;
	if(preg_match('/^\d{4,6}$/',$pin) && $pin > 999){
		return true;
	} else {
		$wts_error_msg = 'Invalid PIN. Your PIN is a 6-digit number, it usually starts as your birthdate (Though you are encouraged to change it).';
		$wts_error_field = 'pin';
		return false;
	}
}

function _nscc_wts_check_https_status(&$response){
	global $wts_error_msg;
	if ($response->responseCode != 200){
		$wts_error_msg = "HTTP failure, server returned code ".$response->responseCode;
		return false;	
	}
	if(preg_match("/<TITLE>503 Service Unavailable<\/TITLE>/",$response->body)){
		$wts_error_msg = "HTTP failure, server returned code 503";
		return false;
	}
	return true;
}
