<?php
// $Id: nscc_locator.module,v 1.236.2.3 2009/01/12 10:09:19 goba Exp $

/**
*	Implementation of hook_menu()
*/
function nscc_locator_menu() {
	$items['locator'] = array(
		'title' => 'Campus Locations',
		'description' => 'NSCC Locator',
		'page callback'=>'_nscc_locator_page_out',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/locate/%'] = array(
		'title' => 'Locator Search Results',
		'description' => 'NSCC Locator Search by location',
		'page callback'=>'_nscc_locator_locate',
		'page arguments'=>array(2),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/locate'] = array(
		'title' => 'Locator Search Results',
		'description' => 'NSCC Locator Search by location',
		'page callback'=>'_nscc_locator_locate',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/minimap/%'] = array(
		'title' => 'NSCC Locator Search Results',
		'description' => 'NSCC Locator Search by location',
		'page callback'=>'_nscc_locator_ajax_minimap',
		'page arguments'=>array(2),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['minimap/%'] = array(
		'title' => 'NSCC Locator Search Results',
		'description' => 'NSCC Locator Search by location',
		'page callback'=>'_nscc_locator_ajax_minimap',
		'page arguments'=>array(1),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/menu'] = array(
		'title' => 'NSCC Locator Left Menu',
		'description' => 'Files the Locator Menu block',
		'page callback'=>'_nscc_locator_ajax_menu',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/poigroup/%'] = array(
		'title' => 'NSCC Locator POI group dump',
		'description' => 'NSCC Locator POI group coordinate ajax output',
		'page callback'=>'_nscc_locator_ajax_poi_group_dump',
		'page arguments'=>array(2),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/poicategory/%'] = array(
		'title' => 'NSCC Locator POI group dump',
		'description' => 'NSCC Locator POI group coordinate ajax output',
		'page callback'=>'_nscc_locator_ajax_poi_category_dump',
		'page arguments'=>array(2),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/poicategory/poidetails'] = array(
		'title' => 'NSCC Locator POI',
		'description' => 'NSCC Locator POI details ajax output',
		'page callback'=>'_nscc_locator_ajax_poi_cat_details',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/building/details'] = array(
		'title' => 'NSCC Locator POI',
		'description' => 'NSCC Locator building details ajax output',
		'page callback'=>'_nscc_locator_ajax_building_details',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
	$items['locator/parking_kiosks'] = array(
		'title' => 'NSCC Locator Parking Kiosks dump',
		'description' => 'NSCC Locator Parking Kiosks coordinate ajax output',
		'page callback'=>'_nscc_locator_ajax_parking_kiosks_dump',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/parking_kiosks/pkdetails'] = array(
		'title' => 'NSCC Locator Parking Kiosk Details',
		'description' => 'NSCC Locator PK details ajax output',
		'page callback'=>'_nscc_locator_ajax_parking_kiosk_details',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['locator/parking/details'] = array(
		'title' => 'NSCC Locator POI',
		'description' => 'NSCC Locator parking details ajax output',
		'page callback'=>'_nscc_locator_ajax_parking_details',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['directions'] = array(
		'title' => 'Campus Directions',
		'description' => 'Directions to NSCC',
		'page callback'=>'_nscc_locator_directions_page_out',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['print-campus-map'] = array(
		'title' => 'Campus Map',
		'description' => 'Printable map of the NSCC campus',
		'page callback' => '_nscc_locator_print_map',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}


/**
*	Implementation of hook_block()
*/
function nscc_locator_block($op='list', $delta=0,$edit=array()){
	switch($op){

		//actual block output
		case 'view':
			switch($delta){
				case 0:
					$block['subject']  = "Room Finder";
					$block['content']  = "<div id=\"locator-roomfinder\" class=\"locator-roomfinder\">\n";
					$block['content'] .= "<form id=\"roomfinder\" action=\"/locator/locate\" method=\"post\">";
					$block['content'] .= "<input type=\"text\" name=\"target_loc\" size=\"15\" /><input type=\"submit\" value=\"Find!\" />\n";				
					$block['content'] .= "</form>";
					$block['content'] .= "</div>\n";
					return $block;
				case 1:
					$block['subject'] = "Points of Interest";
					$block['content'] = "<div class=\"locator-menu poi-menu\"><ul id=\"locator-poi-menu\"></ul></div>";
					return $block;
				case 2:
					$block['subject'] = "Building Details";
					$block['content'] = "<div class=\"locator-menu building-menu\"><ul id=\"locator-building-menu\"></ul></div>";
					return $block;
				case 3:
					$block['subject']  = "Parking";
					$block['content'] .= "<div class=\"locator-menu parking-menu\"><ul id=\"locator-parking-menu\">";
					$block['content'] .= "<li><h3 class=\"locator-menu-sub-title\">By Type</h3><ul id=\"locator-parking-bytype-menu\"></ul></li>";
					$block['content'] .= "<li><h3 class=\"locator-menu-sub-title\">By Lot</h3><ul id=\"locator-parking-bylot-menu\"></ul></li>";
					$block['content'] .= "</ul></div>";
					return $block;
				case 4:
					$block['subject']  = "Directions";
					$block['content'] .= "<div class=\"locator-directions-form-wrapper\"><form id=\"locator-directions-form\">";
					$block['content'] .= "<div class=\"locator-form-field\"><label for=\"start_point_textbox\">From:</label><br /><input type=\"textbox\" id=\"start_point_textbox\" name=\"start_point_textbox\" size=\"40\" ></div>";
					$block['content'] .= "<div class=\"locator-form-field\"><label for=\"travel_mode_selector\">Travel Mode</label><select id=\"travel_mode_selector\" name=\"travel_mode_selector\"><option value=\"DRIVING\">Driving</option><option value=\"WALKING\">Walking</option><option value=\"BICYCLING\">Bicycling</option></select></div>";
					$block['content'] .= "<div class=\"locator-form-field\"><input id=\"get_directions_button\" name=\"get_directions\" type=\"submit\" value=\"Get Directions!\"></div>";
					$block['content'] .= "</form></div>";
					$block['content'] .= "<div class=\"locator-directions-panel\" id=\"locator-directions-panel\"></div>";
					$block['content'] .= "<div class=\"locator-directions-alternate-routefinders\"><a href=\"http://tripplanner.kingcounty.gov/cgi-bin/itin_page.pl\">Metro Trip Planner</a></div>";
					return $block;
				}
		break;
		
		//administrative interface
		case 'list':
			$blocks[0]['info'] = t('Locator: Find Room');
			$blocks[0]['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks[0]['weight'] = 10;			
			$blocks[1]['info'] = t('Locator: Ajax POI Menu');
			$blocks[1]['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks[1]['weight'] = 50;			
			$blocks[2]['info'] = t('Locator: Ajax Building Menu');
			$blocks[2]['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks[2]['weight'] = 50;			
			$blocks[3]['info'] = t('Locator: Ajax Parking Menu');
			$blocks[3]['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks[3]['weight'] = 50;			
			$blocks[4]['info'] = t('Locator: Directions Origin Form');
			$blocks[4]['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks[4]['weight'] = 50;			

			return $blocks;
		break;
	}
}


//returns json describing the menu items
function _nscc_locator_ajax_menu(){
	//watchdog('loc_test',"ajax_menu requested.");
	$menu_array = array();

	//poi_groups
	$poi_group_sql = "select nid from prod_node where type='locator_poi_group';";
	$result = db_query($poi_group_sql);	
	while($data = db_fetch_object($result)){
		$entry_node = node_load($data->nid);
		$marker_node = node_load($entry_node->field_pg_marker_icon[0]['nid']);
		$menu_array[]=array('type'=>'poi_group','nid'=>$entry_node->nid,'title'=>$entry_node->title,'marker_icon'=>'/'.$marker_node->field_marker_menu_graphic[0]['filepath']);
	}
	
	//poi_categories
	$poi_category_sql = "select distinct field_poi_category_value from prod_content_field_poi_category where field_poi_category_value is not null;";
	$poi_category_icon_nid_sql = "select field_poi_marker_icon_nid from prod_content_type_locator_poi lp join prod_content_field_poi_category pc using (vid,nid) where pc.field_poi_category_value='%s' limit 1;";
	$result = db_query($poi_category_sql);
	while($data = db_fetch_object($result)){
		$icon_nid = db_result(db_query($poi_category_icon_nid_sql,$data->field_poi_category_value));
		$marker_node = node_load($icon_nid);
		$menu_array[]=array('type'=>'poi_category','category'=>preg_replace('/ /','-',$data->field_poi_category_value),'title'=>$data->field_poi_category_value,'marker_icon'=>'/'.$marker_node->field_marker_menu_graphic[0]['filepath']);		
	}	
	//buildings
	$building_details_sql = "select nid from prod_node where type='locator_building_details' order by title;";
	$result = db_query($building_details_sql);
	while($data = db_fetch_object($result)){
		$bd_node = node_load($data->nid);
		$menu_array[]=array('type'=>'building_details','nid'=>$bd_node->nid,'title'=>$bd_node->title,'abbr'=>$bd_node->field_bd_abbr[0]['value'],'purpose'=>$bd_node->field_bd_gpurpose[0]['value'],'photo'=>$bd_node->field_bd_photo[0]['filepath'],'polygon'=>$bd_node->field_bd_polygon[0]['polygon_ajax']);		
	}
	//parking kiosks
	$menu_array[]=array('type'=>'parking_kiosks','title'=>'Payment Kiosks','marker_icon'=>'/sites/all/modules/nscc_locator/imgs/map-labels-pay-parking.png');
	//parking lots
	$parking_sql = "select nid from prod_node where type='locator_parking_zone' order by title;";
	$result = db_query($parking_sql);
	while($data = db_fetch_object($result)){
		$parking_node = node_load($data->nid);
		if($parking_node->field_parking_cat[0]['value']=='Named Lot'){
			$menu_array[]=array('type'=>'parking_lot','nid'=>$parking_node->nid,'title'=>$parking_node->title,'polygon'=>$parking_node->field_parking_polygon[0]['polygon_ajax']);
		}	else {
			$polygon_array=array();
			foreach($parking_node->field_parking_polygon as $parking_poly){
				$polygon_array[] = $parking_poly['polygon_ajax']; 
			}
			$menu_array[]=array('type'=>'parking_cat','nid'=>$parking_node->nid,'title'=>$parking_node->title,'polygon_array'=>$polygon_array);
		}	
	}

	//watchdog('loc_test',"<pre>".print_r($menu_array,true)."</pre>");
	
	print drupal_json($menu_array);
	exit();
}


function _nscc_locator_ajax_poi_group_dump($nid){
	$group_node = node_load($nid);
	$json_array='';
	$marker_node = node_load($group_node->field_pg_marker_icon[0]['nid']);
//	watchdog('loc_test','<pre>'.print_r($group_node->field_pg_points,true).'</pre>');
	foreach($group_node->field_pg_points as $point=>$coordinates_array){
			if($marker_node->field_marker_bg[0]['filepath']){
				$shadow_path= '/'.$marker_node->field_marker_bg[0]['filepath'];
			} else {
				$shadow_path=null;
			}
			$json_array[$nid."_".$point] = array(
				'poi_id'=>$nid."_".$point,
				'name'=>$group_node->title,
				'lat'=>$coordinates_array['latitude'],
				'long'=>$coordinates_array['longitude'],
				'poi_g_nid'=>$nid,
				'description'=>$group_node->description,
				'url'=>'',
				'display_photo'=>'',
				'icon_url'=>'/'.$marker_node->field_marker_graphic[0]['filepath'],
				'shadow_url'=> $shadow_path,
			);
	}	
	print drupal_json($json_array);
	exit();
}


function _nscc_locator_ajax_poi_category_dump($category){
	$json_array='';
	$target_category = preg_replace('/-/',' ',$category);
	$poi_category_sql = "select nid from prod_content_field_poi_category where field_poi_category_value='%s';";
	$result = db_query($poi_category_sql,$target_category);
	while($data = db_fetch_object($result)){
		$point_node = node_load($data->nid);
		$marker_node = node_load($point_node->field_poi_marker_icon[0]['nid']);
		$json_array[] = array(
				'poi_id'=>$point_node->nid,
				'name'=>$point_node->title,
				'lat'=>$point_node->field_poi_point[0]['latitude'],
				'long'=>$point_node->field_poi_point[0]['longitude'],
				'poi_category'=>$category,
				'description'=>$point_node->field_poi_desc[0]['value'],
				'display_photo'=>$point_node->field_poi_photo[0]['filepath'],
				'icon_url'=>'/'.$marker_node->field_marker_graphic[0]['filepath'],
				'shadow_url'=>'/'.$marker_node->field_marker_bg[0]['filepath'],
		);
	}
//	watchdog('loc_cat_test','<pre>'.print_r($json_array,true).'</pre>');
	print drupal_json($json_array);
	exit();
}


function _nscc_locator_ajax_parking_kiosks_dump(){
	$json_array='';
	$pk_sql = "select nid from prod_node where type='locator_pk';";
	$result = db_query($pk_sql);
	while($data = db_fetch_object($result)){
		$point_node = node_load($data->nid);
		$json_array[] = array(
				'pk_id'=>$point_node->nid,
				'category'=>'parking_kiosks',
				'name'=>$point_node->title,
				'lat'=>$point_node->field_poi_point[0]['latitude'],
				'long'=>$point_node->field_poi_point[0]['longitude'],
				'description'=>$point_node->field_poi_desc[0]['value'],
				'display_photo'=>$point_node->field_poi_photo[0]['filepath'],
				'icon_url'=>'/sites/all/modules/nscc_locator/imgs/map-icons-pay-parking.png',
				'shadow_url'=>'/sites/all/modules/nscc_locator/imgs/map-icons-pay-parking.png',
		);
	}
//	watchdog('loc_cat_test','<pre>'.print_r($json_array,true).'</pre>');
	print drupal_json($json_array);
	exit();
}




function _nscc_locator_ajax_poi_cat_details(){
	$poi_id = $_POST['poi_id'];
	$poi = node_load($poi_id);

	$window_details = theme('node',$poi);
	$json_array['window_details'] = $window_details;
  $json_array['window_details_script'] = '$("#locator-poi-photo-'.$poi->nid.'").click(function(){';
  $json_array['window_details_script'] .= '$("#locator-photo-overlay-placeholder").html("<img class=\"locator-photo-overlay-photo\" src=\"/'.$poi->field_poi_photo[0]['filepath'].'\">");';
  $json_array['window_details_script'] .= '$("#locator-photo-overlay-wrapper").fadeIn(\'fast\');';
  $json_array['window_details_script'] .= '$("#locator-photo-overlay-matte").fadeIn(\'fast\');';
  $json_array['window_details_script'] .= '$("#locator-photo-overlay-photo").fadeIn(\'slow\');';
  $json_array['window_details_script'] .= '});';

	
	print drupal_json($json_array);
	exit();
}

function _nscc_locator_ajax_parking_kiosk_details(){
	$poi_id = $_POST['poi_id'];
	$poi = node_load($poi_id);
	$window_details = "<div class=\"locator-poi-details\" style=\"width: 272px;\">\n";
	$window_details .= "<h4 class=\"locator-poi-title\">".$poi->nid.": ".$poi->title."</h4>\n";	
	if($poi->field_poi_location_desc[0]['value']){
  	$window_details .= "<div class=\"locator-poi-loc-description\"><span class=\"locator-poi-field-label\">Located:</span><p>".check_markup($poi->field_poi_location_desc[0]['value'])."</p></div>\n";
  }
  $window_details .= "<div class=\"locator-poi-description\"><p>".check_markup($poi->field_poi_desc[0]['value'])."</p></div>\n";
	if($poi->field_poi_photo[0]['filepath']){
  	$window_details .= "<div class=\"locator-poi-photo\"><img id=\"locator-poi-photo-".$poi->nid."\" class=\"locator-poi-photo-img\" width=\"272\" rel=\"#photo_overlay\" src=\"/".$poi->field_poi_photo[0]['filepath']."\"></div>\n";
  }

	$window_details = theme('node',$poi);
	$json_array['window_details'] = $window_details;
  $json_array['window_details_script'] = '$("#locator-poi-photo-'.$poi->nid.'").click(function(){';
  $json_array['window_details_script'] .= '$("#locator-photo-overlay-placeholder").html("<img class=\"locator-photo-overlay-photo\" src=\"/'.$poi->field_poi_photo[0]['filepath'].'\">");';
  $json_array['window_details_script'] .= '$("#locator-photo-overlay-wrapper").fadeIn(\'fast\');';
  $json_array['window_details_script'] .= '$("#locator-photo-overlay-matte").fadeIn(\'fast\');';
  $json_array['window_details_script'] .= '$("#locator-photo-overlay-photo").fadeIn(\'slow\');';
  $json_array['window_details_script'] .= '});';

	
	print drupal_json($json_array);
	exit();
}






function _nscc_locator_ajax_building_details(){
	$building_node = node_load($_POST['bd_nid']);
	$window_details = "<div class=\"locator-poi-details\" style=\"width: 280px;\">\n";
	$window_details .= "<h4 class=\"locator-poi-title\">".$building_node->title."</h4>\n";	
	$window_details .= "</div>";
	$window_details = theme('node',$building_node);
	$json_array['window_details'] = $window_details;
	print drupal_json($json_array);
	exit();
}

function _nscc_locator_ajax_parking_details(){
	$parking_node = node_load($_POST['pk_nid']);
	$window_details = "<div class=\"locator-poi-details\" style=\"width: 280px;\">\n";
	$window_details .= "<h4 class=\"locator-poi-title\">".$parking_node->title."</h4>\n";	
	$window_details .= "</div>";
	$window_details = theme('node',$parking_node);
	$json_array['window_details'] = $window_details;
	print drupal_json($json_array);
	exit();
}



//returns the minimap image
function _nscc_locator_ajax_minimap($search_term){
	$sector_node = _nscc_locator_get_sector_by_room($search_term);
	$src_url = $sector_node->field_minimap[0]['filepath'];
	$alt_text = $sector_node->field_sector_description[0]['value'];
	print "<img class=\"locator-minimap\" width=\"130\" height=\"154\" src=\"/$src_url\" alt=\"$alt_text\" title=\"$alt_text\">";
}

function _nscc_locator_locate($search_term=false){
	#drupal_set_html_head('<script src="http://maps.google.com/maps/api/js?v=3.1&amp;sensor=false&amp;region=US" type="text/javascript"></script>');
	drupal_set_html_head('<script src="https://maps-api-ssl.google.com/maps/api/js?v=3&amp;sensor=false&amp;region=US" type="text/javascript"></script>');
	drupal_set_html_head('<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />');
	drupal_add_js(drupal_get_path('module', 'nscc_locator') .'/nscc_locator.js');
	drupal_add_css(drupal_get_path('module', 'nscc_locator') .'/nscc_locator.css');	
	if(! $search_term){
		$search_term = check_plain($_POST['target_loc']);
	}  
	$sector_node = _nscc_locator_get_sector_by_room($search_term);
	//$output = "<div>Search Results: $search_term Title: {$sector_node->title} </div>";
	//$output .="<div>".nscc_locator_get_minimap_by_room($search_term)."\n</div>\n";
	//$output .="<div><pre>".print_r($sector_node,true)."\n</pre></div>\n";									
	$to_map_array = array('type'=>'sector','description'=>$sector_node->field_sector_description[0]['value'],'polygon'=>$sector_node->field_map_overlay[0]['polygon_ajax']);
	$to_map_json = drupal_to_js($to_map_array);	
	//$output .="<form><input type='hidden' name='to_map_json' value='$to_map_json'></form>\n";
	if($sector_node->field_map_overlay[0]['polygon_ajax']){
		$output .="<script> var starting_sector = ".$sector_node->field_map_overlay[0]['polygon_ajax']."; var starting_sector_level = ".$sector_node->field_level[0]['value']."; </script>";
	}
/*
	$output .= "<div class=\"locator-description\"><span class=\"locator-search-term\">$search_term</span> is in or on the ".$sector_node->field_sector_description[0]['value']."</div>\n";
	$output .= "<div id=\"map_canvas\" class='grid-6 alpha omega' style=\"height:500px; border-width: 1px; border-style: solid;\"></div>\n";
	$output .="<div id=\"locator-overlay-wrapper\" class=\"locator-overlay-wrapper\"><div id=\"locator-overlay-matte\" class=\"locator-overlay-matte\"></div><div id=\"locator-overlay-placeholder\" class=\"locator-overlay-placeholder\"></div></div>\n";
	return $output;
*/
	if (!empty($sector_node->field_sector_description[0]['value'])) {
		$location_message_status = ' status';
		$location_description = "<p><span class=\"locator-search-term\">$search_term</span> is in or on the " . check_plain($sector_node->field_sector_description[0]['value']) . '.</p>';
	} else {
		$location_message_status = ' error';
		$location_description = "<p>Sorry, <span class=\"locator-search-term\">$search_term</span> could not be located.</p>";
	}

	return <<<LOCATOR_LOCATE_OUT
$output
<div id="locator-directions-switcher" class="tabs">
	<ul class="tabs primary clear-block">
		<li class="active"><a href="#"><span class="tab">On Campus</span></a></li>
		<li><a href="/directions"><span class="tab">To Campus</span></a></li>
	</ul>
</div>
<div id="fake-left-sidebar" class="grid-3 alpha">
	<div class="block-nscc_locator room-finder locator-form">
		<h2>Room Finder</h2>
			<form id="roomfinder" action="/locator/locate" method="post">
		<div id="locator-roomfinder" class="locator-roomfinder">
			<label for="target_loc">Room Number</label>
			<input type="text" id="target_loc" name="target_loc" size="16" />
			<input type="submit" id="locator-submit" name="submit" value="Find It" />			
		</div>
			</form>
	</div>
	<div class="block-nscc_locator poi-list">
		<h2>Points of Interest</h2>
		<div class="locator-menu poi-menu"><ul id="locator-poi-menu"><li></li></ul></div>
	</div>
	<div class="block-nscc_locator building-details">
		<h2>Building Details</h2>
		<div class="locator-menu building-menu"><ul id="locator-building-menu"><li></li></ul></div>
	</div>
	<div class="block-nscc_locator parking-details">
		<h2>Parking</h2>
		<div class="locator-menu parking-menu"><ul id="locator-parking-menu">
		<li><h3>By Type</h3><ul id="locator-parking-bytype-menu"><li></li></ul></li>
		<li><h3>By Lot</h3><ul id="locator-parking-bylot-menu"><li></li></ul></li>
		</ul></div>
	</div>	
</div>
<div id="locator-results" class="grid-9 omega">
	<div class="location-description$location_message_status">$location_description</div>
	<div id="map_canvas" style="height:800px;border:solid 1px;"></div>
</div>

LOCATOR_LOCATE_OUT;
}

function nscc_locator_get_minimap_by_room($room){
	$sector_node = _nscc_locator_get_sector_by_room($room);
	$src_url = $sector_node->field_minimap[0]['filepath'];
	$alt_text = $sector_node->field_sector_description[0]['value'];
	return "<img class=\"locator-minimap\" src=\"/$src_url\" alt=\"$alt_text\" title=\"$alt_text\" />";
}


function _nscc_locator_get_sector_by_room($room){

	preg_match('/((\d)(\d)(\d\d))/',$room,$matches);
	$trimmed_room = $matches[1];
	$floor = $matches[2];
	$avenue = $matches[3];
	$door = $matches[4];

	if(preg_match('/OC \d|OC\d|OCEE \d/i',$room)){
	$sql="SELECT nid FROM prod_content_type_locator_sector WHERE field_building_value='%s' and field_level_value=%d and field_avenue_value=%d and field_door_min_value <= %d and field_door_max_value >= %d limit 1;";
		$nid = db_result(db_query($sql,'OC',$floor,$avenue,$door,$door));
		if($nid){
			$sector_node = node_load($nid);
			return $sector_node;
		}	
	} else {
		//watchdog('loc_test',"Arg: $room, Room: $trimmed_room, Floor: $floor, Avenue: $avenue, Door: $door");
		$sql="SELECT nid FROM prod_content_type_locator_sector WHERE field_level_value=%d and field_avenue_value=%d and field_door_min_value <= %d and field_door_max_value >= %d limit 1;";
		$nid = db_result(db_query($sql,$floor,$avenue,$door,$door));
		if($nid){
			$sector_node = node_load($nid);
			return $sector_node;
		}	
	}
  //case insensitive match with removed spaces
  $countsql = "select count(room) from prod_nscc_locator_named_locations where upper(regexp_replace(name,E'\\\s+','','g')) ~* upper(regexp_replace('%s',E'\\\s+','','g'));";
	$room_sql = "select room from prod_nscc_locator_named_locations where upper(regexp_replace(name,E'\\\s+','','g')) ~* upper(regexp_replace('%s',E'\\\s+','','g'));";
	//watchdog('loc_test',"arg: $room query: $room_sql" );
	
	$count_result=db_result(db_query($countsql,$room));
	if($count_result != 1){
		return false;
	} else {
		//watchdog('loc_test',"query: $room, Count: $count_result");
		$room = db_result(db_query($room_sql,$room));
		preg_match('/((\d)(\d)(\d\d))/',$room,$matches);
		$trimmed_room = $matches[1];
		$floor = $matches[2];
		$avenue = $matches[3];
		$door = $matches[4];
		$nid = db_result(db_query($sql,$floor,$avenue,$door,$door));
		if($nid){
			$sector_node = node_load($nid);
			return $sector_node;
		}
		return false;	
  }

}


function _nscc_locator_page_out(){
	drupal_set_html_head('<script src="https://maps-api-ssl.google.com/maps/api/js?v=3&amp;sensor=true&amp;region=US" type="text/javascript"></script>');
	//drupal_set_html_head('<script src="http://maps.google.com/maps/api/js?sensor=false&amp;region=US" type="text/javascript"></script>');
	drupal_set_html_head('<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />');
	drupal_add_js(drupal_get_path('module', 'nscc_locator') .'/nscc_locator.js');
  drupal_add_css(drupal_get_path('module', 'nscc_locator') .'/nscc_locator.css');
	return <<<LOCATOR_PAGE_OUT
<div id="locator-directions-switcher" class="tabs">
	<ul class="tabs primary clear-block">
		<li class="active"><a href="#"><span class="tab">On Campus</span></a></li>
		<li><a href="/directions"><span class="tab">To Campus</span></a></li>
		<li><a href="/print-campus-map"><span class="tab">Print Map</span></a></li>
	</ul>
</div>
<div id="fake-left-sidebar" class="grid-3 alpha">
	<div class="block-nscc_locator room-finder locator-form">
		<h2>Room Finder</h2>
			<form id="roomfinder" action="/locator/locate" method="post">
		<div id="locator-roomfinder" class="locator-roomfinder">
			<label for="target_loc">Room Number</label>
			<input type="text" id="target_loc" name="target_loc" size="16" />
			<input type="submit" id="locator-submit" name="submit" value="Find It" />			
		</div>
			</form>
	</div>
	<div class="block-nscc_locator poi-list">
		<h2>Points of Interest</h2>
		<div class="locator-menu poi-menu"><ul id="locator-poi-menu"></ul></div>
	</div>
	<div class="block-nscc_locator building-details">
		<h2 class="open">Buildings</h2>
		<div class="locator-menu building-menu"><ul id="locator-building-menu"></ul></div>
	</div>
	<div class="block-nscc_locator parking-details">
		<h2>Parking</h2>
		<div class="locator-menu parking-menu">
		<ul id="locator-parking-kiosk-menu"></ul>
		<ul id="locator-parking-menu">
		<li><h3>By Type</h3><ul id="locator-parking-bytype-menu"></ul></li>
		<li><h3>By Lot</h3><ul id="locator-parking-bylot-menu"></ul></li>
		</ul></div>
	</div>	
</div>
<div id="map_canvas" class="grid-9 omega" style="height:800px;border:solid 1px;"></div>

LOCATOR_PAGE_OUT;
}

function _nscc_locator_directions_page_out(){
	drupal_set_html_head('<script src="https://maps-api-ssl.google.com/maps/api/js?v=3&amp;sensor=false&amp;region=US" type="text/javascript"></script>');
//	drupal_set_html_head('<script src="http://maps.google.com/maps/api/js?sensor=false&amp;region=US" type="text/javascript"></script>');
	drupal_set_html_head('<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />');
	drupal_add_js(drupal_get_path('module', 'nscc_locator') .'/nscc_locator_directions.js');
  drupal_add_css(drupal_get_path('module', 'nscc_locator') .'/nscc_locator.css');
/*
	$output ="<div id=\"locator-directions-switcher\"><a class=\"locator-directions-switcher-wish\" href=\"/locator\">On Campus</a><span class=\"locator-directions-switcher-current\">To Campus</span></div>\n";
	$output .= "<div id=\"map_canvas\" class='grid-9 alpha omega' style=\"height:500px; border-width: 1px; border-style: solid;\"></div>\n";
	$output .="<div id=\"locator-overlay-wrapper\" class=\"locator-overlay-wrapper\"><div id=\"locator-overlay-matte\" class=\"locator-overlay-matte\"></div><div id=\"locator-overlay-placeholder\" class=\"locator-overlay-placeholder\"></div></div>\n";

	return $output;
*/
return <<<LOCATOR_DIRECTIONS_PAGE_OUT
<div id="locator-directions-switcher" class="tabs">
	<ul class="tabs primary clear-block">
		<li><a href="/locator"><span class="tab">On Campus</span></a></li>
		<li class="active"><a href="#"><span class="tab">To Campus</span></a></li>
		<li><a href="/print-campus-map"><span class="tab">Print Map</span></a></li>
	</ul>
</div>
<div id="fake-left-sidebar" class="grid-3 alpha">
	<div class="block-nscc_locator directions-form locator-form">
		<h2>Directions</h2>
		<div class="locator-directions-form-wrapper">
			<form id="locator-directions-form" action="_self">
				<div class="locator-form-field directions-input">
					<label for="start_point_textbox">From:</label>
					<input type="text" id="start_point_textbox" name="start_point_textbox" size="26" />
				</div>
				<div class="locator-form-field travel-mode-selector">
					<label for="travel_mode_selector">Travel Mode</label>
					<select id="travel_mode_selector" name="travel_mode_selector">
						<option value="DRIVING">Driving</option>
						<option value="WALKING">Walking</option>
						<option value="BICYCLING">Bicycling</option>
					</select>
				</div>
				<div class="locator-form-field submit-controls">
					<input id="get_directions_button" name="get_directions" type="submit" value="Get Directions!" />
				</div>
			</form>
		</div>
		<div class="locator-directions-alternate-routefinders">
			<a href="http://tripplanner.kingcounty.gov/hiwire?.a=iTripPlanning">Regional Bus Trip Planner</a>
		</div>
		<div class="locator-directions-panel" id="locator-directions-panel"></div>
	</div>
</div>	
<div id="map_canvas" class="grid-9 alpha omega" style="height:700px;border:solid 1px;"></div>
LOCATOR_DIRECTIONS_PAGE_OUT;
}


/**
 *	Printable map page
 */
function _nscc_locator_print_map() {
	drupal_add_js(drupal_get_path('module', 'nscc_locator') .'/nscc_locator.print-map.js');
  drupal_add_css(drupal_get_path('module', 'nscc_locator') .'/nscc_locator.css');
  //$img_url = url(drupal_get_path('module', 'nscc_locator') . '/imgs/map-print-bw.png');
  $img_url = url(drupal_get_path('module', 'nscc_locator') . '/imgs/campus-map-print.png');
  $pdf_url = url(drupal_get_path('module', 'nscc_locator') . '/files/NSC_Campus_Map.pdf');
	return <<<PRINT_MAP_OUT
<div id="locator-directions-switcher" class="tabs">
	<ul class="tabs primary clear-block">
		<li><a href="/locator"><span class="tab">On Campus</span></a></li>
		<li><a href="/directions"><span class="tab">To Campus</span></a></li>
		<li class="active"><a href="/print-campus-map"><span class="tab">Print Map</span></a></li>
	</ul>
</div>
<div id="fake-left-sidebar" class="grid-3 alpha">
	<div class="block-nscc_locator print-notice">
		<p>This is a printer-friendly version of the campus map. This is best <strong>printed</strong> in landscape mode.</p>
	</div>
	<div class="block-nscc_locator pdf-link">
		<p><a href="$pdf_url">Here's the PDF version</a></p>
	</div>
</div>
<div id="map_canvas" class="grid-9 alpha omega">
	<!-- <img src="$img_url" alt="Printable map of the NSC campus" style="display:block;width:475px;height:700px;margin:0 auto;" /> -->
	<!-- <img src="$img_url" alt="Printable map of the NSC campus" style="display:block;width:337px;height:700px;margin:0 auto;" /> -->
	<img src="$img_url" alt="Printable map of the NSC campus" style="display:block;width:100%;margin:10 auto;" /> 
</div>
PRINT_MAP_OUT;
}