<?php
// $Id: nscc_people_tools.module,v 1.236.2.3 2009/01/12 10:09:19 goba Exp $



/**
 * @file
 * Support for people site tools pages.
 */

/**
 * Implementation of hook_menu().
 */
function nscc_people_tools_menu() {
  $items['tools/%'] = array(
		'title'=>'Personalized Tools',
    'page callback' => '_render_tools_page',
		'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access callback'=> true,
  );
	return $items;
}

function nscc_people_tools_block($op = 'list', $delta = 0, $edit = array()) {
	switch($op){
		case 'list':
			$blocks[0]['info']= t('People Tools Menu');
			$blocks[0]['cache'] = BLOCK_CACHE_PER_PAGE | BLOCK_CACHE_PER_ROLE;
			return $blocks;
			break;
		case 'configure':
			break;
		case 'save':
			break;
		case 'view':
			switch($delta){
				case 0:
					//People Tools Menu
					$block['subject'] = '';
					$block['content']=_render_tools_menu();
					return $block;
					break;
			}		
	}

}


function _render_tools_page($username){
	
	$tools_array = _get_tools_array();	
	
	$output = '<div id="personal_tool_palette" class="personal-tool-palette">';
	foreach($tools_array as $tools_group){
		$output .='<h2 class="tool-group-title" id="'.$tools_group['group-id'].'-title">'.$tools_group['group-title'].'</h2>';
		$output .='<ul class="tool-group" id="'.$tools_group['group-id'].'-group">';
		foreach($tools_group['tools'] as $current_tool){
			$output .= _render_tool_details($current_tool);
		}
		$output .='</ul>'."\n";
	}
	$output .='</div>';
	return $output;
}


function _render_tools_menu(){
	drupal_add_js(drupal_get_path('module', 'nscc_people_tools').'/nscc_people_tools.js');
	$tools_array = _get_tools_array();	
	
	$output = '<div class="tools-menu" id="">';
	$output .='<ul class="menu">';
	foreach($tools_array as $tools_group){
		$output .='<li class="leaf tool-group">';
		$output .='<span class="menu-group-title">'.$tools_group['group-title'].'</span>';
		$output .='<ul class="menu" id="menu-tool-group-'.$tools_group['group-id'].'">';
		foreach($tools_group['tools'] as $current_tool){
			$output .='<li class="leaf"><a class="tool-menu-item" href="'.$current_tool['url'].'" title="'.$current_tool['title'].'">'.$current_tool['name'].'</a></li>';
		}
		$output .='</ul></li>';
	}
	$output .='</ul>';
	$output .='</div>';
	return $output;
}



function _render_tool_details($tool_details){
	$tool_classes = 'tool-entry';
	if ($tool_details['local_tool'] ){
		$tool_classes .= ' local-tool';
	}
	$tool_classes .=' auth-'.$tool_details['auth_type'];
	$output .='<li class="'.$tool_classes.'"><a class="tool-link" href="'.$tool_details['url'].'" title="'.$tool_details['title'].'"><img src="'.$tool_details['icon_path'].'" width="" height="">'.$tool_details['name'].'</a></li>';
	return $output;
}

function _get_tools_array(){
	//for right now this is just hardcoded. We will probably shove this into a database there may be permissions involved.

	$tools_array[] = array(
		'group-title'=>'Payroll Tools',
		'group-id'=>'payroll-tools',
		'tools'=>array(
				array(
					'name'=>'Time and Leave Reporting',
					'url'=>'https://apps.seattlecolleges.edu/TLR/login.aspx',
					'title'=>'Time and Leave Reporting',
					'icon_path'=>'',
					'auth_type'=>'sidpin',
					'local_tool'=>false
				),
				array(
					'name'=>'Earning History',
					'url'=>'https://wts.seattlecolleges.edu/seadist6/earnhist/waci400.html',
					'title'=>'Earning History Report',
					'icon_path'=>'',
					'auth_type'=>'sidpin',
					'local_tool'=>false
				),
				array(
					'name'=>'Update Address',
					'url'=>'https://apps.seattlecolleges.edu/AdTool/AddressChange.aspx',
					'title'=>'Update your home address/contact info',
					'icon_path'=>'',
					'auth_type'=>'sidpin',
					'local_tool'=>false
				),
				array(
					'name'=>'Recover Forgotten SID/PIN',
					//'url'=>'https://sccdweb.sccd.ctc.edu/common_files/forgotSIDPIN.asp',
					'url'=>'https://www.seattlecolleges.edu/common_files/forgotSIDPIN.asp',
					'title'=>'Recover your SID or PIN',
					'icon_path'=>'',
					'auth_type'=>'other',
					'local_tool'=>false
				),
		), //end payroll group	

	);
	
	$tools_array[] = array(
		'group-title'=>'Email',
		'group-id'=>'email',
		'tools'=>array(
				array(
					'name'=>'Exchange Webmail',
					'url'=>'https://mail.seattlecolleges.edu/owa/',
					'title'=>'Official District Mail',
					'icon_path'=>'',
					'auth_type'=>'district',
					'local_tool'=>false
				),
				array(
					'name'=>'NSCC NetID Mail',
					'url'=>'http://mail.northseattle.edu',
					'title'=>'NetID Mail, provided by Google',
					'icon_path'=>'',
					'auth_type'=>'netid',
					'local_tool'=>false
				),
		), //end email group	

	);
	
	$tools_array[] = array(
		'group-title'=>'Misc',
		'group-id'=>'misc',
		'tools'=>array(
				array(
					'name'=>'Help',
					'url'=>'https://netid.northseattle.edu/portal/help.php',
					'title'=>'Submit IT/Media Services Help Requests',
					'icon_path'=>'',
					'auth_type'=>'netid',
					'local_tool'=>false
				),
				array(
					'name'=>'Change Your NetID Password',
					'url'=>'https://netid.northseattle.edu/faculty/passchange.php',
					'title'=>'Change Your NetID Password',
					'icon_path'=>'',
					'auth_type'=>'netid',
					'local_tool'=>false
				),
				array(
					'name'=>'EnGoogleate!',
					'url'=>'https://netid.northseattle.edu/engooglate.php',
					'title'=>'Add Google Apps to your NetID',
					'icon_path'=>'',
					'auth_type'=>'netid',
					'local_tool'=>false
				),
				array(
					'name'=>'NSCC NetID Apps',
					'url'=>'http://docs.northseattle.edu',
					'title'=>'NetID Apps, provided by Google',
					'icon_path'=>'',
					'auth_type'=>'netid',
					'local_tool'=>false
				),
				array(
					'name'=>'Facilities Work Request',
					'url'=>'http://facops.northseattle.edu',
					'title'=>'Submit Work Requests to Facilities/Plant Operations Department',
					'icon_path'=>'',
					'auth_type'=>'other',
					'local_tool'=>false
				),
				array(
					'name'=>'AD Tool',
					'url'=>'https://apps.seattlecolleges.edu/AdTool/user/Welcome.aspx',
					'title'=>'Manage your Exchange account',
					'icon_path'=>'',
					'auth_type'=>'district',
					'local_tool'=>false
				),
				array(
					'name'=>'Instructor Briefcase',
					'url'=>'https://wts.seattlecolleges.edu/seanor/ibc/',
					'title'=>'The Instructor Briefcase',
					'icon_path'=>'',
					'auth_type'=>'sidpin',
					'local_tool'=>false
				),
				array(
					'name'=>'Inside Seattle Colleges',
					'url'=>'https://inside.seattlecolleges.edu',
					'title'=>'District Intranet',
					'icon_path'=>'',
					'auth_type'=>'district',
					'local_tool'=>false
				),
				
		), //end email group	

	);

	return $tools_array;
}
