<?php
// $Id: nscc_profile.module,v 1.236.2.3 2009/01/12 10:09:19 goba Exp $

/**
 * @file
 * Adds admin interface for Etutoring accounts
 */

/**
*	implementation of hook_help
*/
function nscc_etutoring_help($path,$arg){
  switch ($path) {
    case 'admin/help#nscc_etutoring':
      $output = '<p>'. t('The etutoring registration module maintains a linkage between sid and anonomized etutoring accounts.') .'</p>';
      return $output;
  }
}

/**
 * Implementation of hook_perm().
 */
function nscc_etutoring_perm(){
	return array('administer etutoring','associate etutoring account with self','administrate etutoring associations','view existing etutoring associations','import etutoring account dump');
}


/**
 * Implementation of hook_menu().
*/ 
function nscc_etutoring_menu() {
  $items['nscc_etutoring'] = array(
    'title' => 'Set up an etutoring account',
    'page callback' => 'nscc_etutoring_associate',
    'access arguments' => array('associate etutoring account with self'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nscc_etutoring.pages.inc',
  );
  $items['nscc_etutoring/done'] = array(
    'title' => 'Finished!',
    'page callback' => 'nscc_etutoring_done',
    'access arguments' => array('associate etutoring account with self'),
    'type' => MENU_CALLBACK,
    'file' => 'nscc_etutoring.pages.inc',
  );

  $items['manage/nscc_etutoring'] = array(
    'title' => 'etutoring administration',
    'page callback' => 'nscc_etutoring_admin',
    'access arguments' => array('administrate etutoring associations'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nscc_etutoring.manage.pages.inc',
  );
  $items['manage/nscc_etutoring/show'] = array(
    'title' => 'View existing association',
    'page callback' => 'nscc_etutoring_view_assoc',
    'access arguments' => array('view existing etutoring associations'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nscc_etutoring.manage.pages.inc',
  );
  $items['manage/nscc_etutoring/addbatch'] = array(
    'title' => 'import new batch from upload',
    'page callback' => 'nscc_etutoring_addbatch',
    'access arguments' => array('import etutoring account dump'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nscc_etutoring.manage.pages.inc',
  );

  $items['admin/settings/nscc_etutoring'] = array(
    'title' => 'NSCC E-Tutoring',
	'description'=> 'Manipulate settings for the NSCC E-tutoring online registration system.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nscc_etutoring_admin_settings'),
    'access arguments' => array('administer etutoring'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nscc_etutoring.admin.pages.inc',
  );

  return $items;
  
 }


/**
 * Implementation of hook_cron().
 */
function nscc_etutoring_cron(){
	$get_next_sql = "SELECT 'nscc' || max(cast(replace(et_uname,'nscc','') as int8))+1 AS starting_uname FROM {nscc_etutoring_accounts};";
	$remaining_empty_sql = "SELECT count(*) AS remaining_unallocated FROM {nscc_etutoring_accounts} WHERE sid IS NULL;";
	$remaining_accounts = db_result(db_query($remaining_empty_sql));
	if ($remaining_accounts < 10){
		$next_et_uname = db_result(db_query($get_next_sql));
		$params = array(
			'next_uname'=>$next_et_uname,
			'remaining_accounts'=>$remaining_accounts
		);
		drupal_mail('nscc_etutoring','newbatch',variable_get('nscc_etutoring_manager_email','sbayne@northseattle.edu'),language_default(),$params);
	   	error_log("\n--------------------------------------------\n",3,"/var/tmp/etutlog.txt");
	  	error_log("Down to $remaining_accounts etutoring accounts left.\n",3,"/var/tmp/etutlog.txt");
	  	error_log("Start the next batch with a username of $next_et_uname\n",3,"/var/tmp/etutlog.txt");	
	}
}


/**
* Implementation of hook_mail().
*/
function nscc_etutoring_mail($key, &$message, $params){
	switch($key){
		case 'newbatch':
			$message['subject'] = 'Etutoring Account Registration alert!';
			$message['body'][]  = 'We are down to only '.$params['remaining_accounts'].' left to hand out to students for etutoring.';
			$message['body'][]  = 'Please create and upload a new batch of accounts, starting at a username of '.$params['next_uname'].'.';
			$message['body'][]  = '';
			$message['body'][]  = 'You can download the template file from: https://itservices.northseattle.edu/manage/nscc_etutoring/addbatch';
		break;
	}		
}

/**
 * Implementation of hook_block().

function nscc_etutoring_block($op = 'list', $delta = 0, $edit = array()) {
}
*/
?>