<?php
// $Id: nscc_utf_request.module,v 1.236.2.3 2009/01/12 10:09:19 goba Exp $

//hook_help
function nscc_utf_request_help($path,$arg){
	switch($path){
		case 'admin/help#nscc_utf_request':
		$output = '<p>'.t('The UTF request module collects and exports UTF committee requests.').'</p>'."\n";
	}
	return $output;
}

//hook_perm
function nscc_utf_request_perm(){
	return array('administer utf requests','submit utf requests');
}

//hook_menu
function nscc_utf_request_menu(){
  $items['nscc_utf_request'] = array(
    'title' => 'UTF Requests',
		'description'=> 'List UTF funding requests',
    'page callback' => '_nscc_utf_request_list_requests',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );	

  $items['nscc_utf_request_nopage'] = array(
    'title' => 'UTF Requests',
		'description'=> 'List UTF funding requests',
    'page callback' => '_nscc_utf_request_list_requests',
    'page arguments' => array(TRUE),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );	

  $items['nscc_utf_request/%'] = array(
    'title' => 'View a UTF Request',
		'description'=> 'Views an existing UTF Request',
    'page callback' => '_nscc_utf_request_view',
    'page arguments'=>array(1),
		'access callback'=>TRUE,
    'type' => MENU_NORMAL_ITEM,
  );	

  $items['nscc_utf_request_nopage/%'] = array(
    'title' => 'View a UTF Request',
		'description'=> 'Views an existing UTF Request',
    'page callback' => '_nscc_utf_request_view',
    'page arguments'=>array(1,TRUE),
		'access callback'=>TRUE,
    'type' => MENU_CALLBACK,
  );	

  $items['nscc_utf_request/%/edit'] = array(
    'title' => 'Edit a UTF Request',
		'description'=> 'Edits an existing UTF Request',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('nscc_utf_request_baserequestform',1),
		'access callback'=>'_nscc_utf_request_edit_access_callback',
    'access arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
  );	
  $items['nscc_utf_request/%/edit_line_items'] = array(
    'title' => 'UTF Request Edit Line Items',
		'description'=> 'Edits Line Items for an existing UTF Request',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('nscc_utf_request_edit_line_itemsform',1),
		'access callback'=>'_nscc_utf_request_edit_access_callback',
		'access arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
  );	
  $items['nscc_utf_request/%/line_item/%/edit'] = array(
    'title' => 'Edit a Line Item',
		'description'=> 'Edits a single existing Line Item',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('nscc_utf_request_edit_line_itemsform',1,3),
		'access callback'=>'_nscc_utf_request_edit_access_callback',
    'access arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
  );	
  $items['nscc_utf_request/%/line_item/%/delete'] = array(
    'title' => 'Delete a Line Item',
		'description'=> 'Edits an existing Line Item',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('nscc_utf_request_delete_line_itemform',1,3),
		'access callback'=>'_nscc_utf_request_edit_access_callback',
    'access arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
  );	

  $items['nscc_utf_request/%/delete'] = array(
    'title' => 'Delete a UTF Request',
		'description'=> 'Deletes an existing UTF Request',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('nscc_utf_request_delete_form',1),
		'access callback'=>'_nscc_utf_request_edit_access_callback',
    'access arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
  );	
  $items['nscc_utf_request/add'] = array(
    'title' => 'Submit a UTF Request',
		'description'=> 'Submit a funding request to the UTF Committee',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nscc_utf_request_baserequestform'),
    'access arguments' => array('submit utf requests'),
    'type' => MENU_NORMAL_ITEM,
  );	

  $items['admin/settings/nscc_utf_request'] = array(
    'title' => 'NSCC UTF Request',
		'description'=> 'Manipulate settings for the NSCC UTF Request online submission system.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nscc_utf_request_admin_settings'),
    'access arguments' => array('administer utf requests'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/settings/nscc_utf_request/export/%'] = array(
    'title' => 'NSCC UTF Request',
		'description'=> 'Export from the NSCC UTF Request online submission system.',
    'page callback' => '_nscc_utf_request_export',
    'page arguments'=> array(4),
    'access arguments' => array('administer utf requests'),
    'type' => MENU_CALLBACK,
  );
  $items['manage/nscc_utf_request'] = array(
    'title' => 'NSCC UTF Request',
		'description'=> 'Manipulate settings for the NSCC UTF Request online submission system.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nscc_utf_request_admin_settings'),
    'access arguments' => array('administer utf requests'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['manage/nscc_utf_request/export/%'] = array(
    'title' => 'NSCC UTF Request',
		'description'=> 'Export from the NSCC UTF Request online submission system.',
    'page callback' => '_nscc_utf_request_export',
    'page arguments'=> array(3),
    'access arguments' => array('administer utf requests'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function _nscc_utf_request_export($export_type){
	watchdog('nscc_utf_request','Export of type '.$export_type.' attempted');

	switch($export_type){
		case 'line_items':
			drupal_set_header('Content-Type: application/x-msexcel');
    	drupal_set_header("Content-Disposition: attachment; filename=UTF_line_item_export.xls");
	    if (function_exists('mb_convert_encoding')) {
      	$output = chr(255) . chr(254);
    	}

			$export_sql = "SELECT request_id,line_item_id,description,location,unit_price,quantity FROM {nscc_utf_request_line_item} ORDER BY request_id,weight ASC;";
			$result = db_query(db_rewrite_sql($export_sql));
			$header_row = '"Request Id"'."\t".'"Item Id"'."\t".'"Description"'."\t".'"Location"'."\t".'"Unit Price"'."\t".'"Quantity"'."\n";			
 		  if (function_exists('mb_convert_encoding')) {
    		$header_row = mb_convert_encoding($header_row, 'UTF-16LE', 'UTF-8');
    	}
			$output .= $header_row;
			while($current_request = db_fetch_array($result)){
			
					foreach($current_request as $key=>$value){
						// Escape inner quotes and wrap all contents in new quotes.
      			$current_request[$key] = '"'. str_replace('"', '""', $value) .'"';
 					}
    			$row = implode("\t", $current_request) ."\n";

 		   		if (function_exists('mb_convert_encoding')) {
    		  	$row = mb_convert_encoding($row, 'UTF-16LE', 'UTF-8');
    			}
					$output .= $row;
			}			
			print $output;
			break;
			
		case 'request_summary':
			drupal_set_header('Content-Type: application/x-msexcel');
    	drupal_set_header("Content-Disposition: attachment; filename=UTF_export.xls");
	    if (function_exists('mb_convert_encoding')) {
      	$output = chr(255) . chr(254);
    	}

			$export_sql = "SELECT request_id,requestor_name,requestor_email,requestor_phone,intended_location,description,benefits,estimated_shipping FROM {nscc_utf_request} ORDER BY changed ASC;";
			$result = db_query(db_rewrite_sql($export_sql));
			$header_row = '"Request Id"'."\t".'"Name"'."\t".'"Email"'."\t".'"Phone"'."\t".'"Intended Location"'."\t".'"Description"'."\t".'"Benefit"'."\t".'"Estimated Shipping"'."\n";			
 		  if (function_exists('mb_convert_encoding')) {
    		$header_row = mb_convert_encoding($header_row, 'UTF-16LE', 'UTF-8');
    	}
			$output .= $header_row;
			while($current_request = db_fetch_array($result)){
			
					foreach($current_request as $key=>$value){
						// Escape inner quotes and wrap all contents in new quotes.
      			$current_request[$key] = '"'. str_replace('"', '""', $value) .'"';
 					}
    			$row = implode("\t", $current_request) ."\n";

 		   		if (function_exists('mb_convert_encoding')) {
    		  	$row = mb_convert_encoding($row, 'UTF-16LE', 'UTF-8');
    			}
					$output .= $row;
			}			
			print $output;
			break;
	}
}

function _nscc_utf_request_edit_access_callback($request_id){
	global $user;
	//watchdog('nscc_utf_request','access callback called with a request_id of: %request',array('%request'=>$request_id));
	if (user_access('administer utf requests')){
		return true;
	} else {
		//check deadline
		$due_date_array = variable_get('nscc_utf_request_due_date','');
		$due_date = strtotime($due_date_array['month']."/".$due_date_array['day']."/".$due_date_array['year'].' 18:00');	// [mv] Added time to mitigate confusion about deadline and last-minute submission activity.
		if($due_date <= time()){
			watchdog('nscc_utf_request','past due');
			return false;
		} else {
			if($request_id == 'add'){
				watchdog('nscc_utf_request','add request');
				return true;
			}else {
				//check 'ownership'
				$sql = 'SELECT * FROM {nscc_utf_request} WHERE request_id=%d';
				$result = db_query(db_rewrite_sql($sql),$request_id);
				//watchdog('nscc_utf_request','access callback pre query -- request_id: %request, user_uid: %uid',array('%request'=>$request_id,'%uid'=> $user->uid));				
				if($retrieved_request = db_fetch_object($result)){
					//watchdog('nscc_utf_request','access callback postquery -- request_id: %request_id, user_uid: %uid,requestor_id = %requestor',array('%request_id'=>$request_id,'%uid'=> $user->uid,'%requestor'=>$retrieved_request->requestor_uid));				
					if ($user->uid == $retrieved_request->requestor_uid){
						return true;
					}
				}
				return false;
			}
		}
	}
}

function nscc_utf_request_admin_settings(){
	$form['nscc_utf_request_year'] = array(
		'#type' => 'textfield',
		'#title'=>t('Request Year'),
		'#size'=> 4,
		'#description' => 'This is the year for which the requests will be made.',
		'#default_value'=> variable_get('nscc_utf_request_year','')
	);
	$form['nscc_utf_request_due_date'] = array(
		'#type' => 'date',
		'#title'=>t('Request Due Date'),
		'#description' => 'This is the deadline for submissions',
		'#default_value'=> variable_get('nscc_utf_request_due_date',''),				
	);
	$form['exports'] = array(
		'#type'=>'markup',
		'#prefix'=>'<div>',
		'#value'=>'<ul><li><a href="/manage/nscc_utf_request/export/request_summary">Export the Request Summaries</a></li><li><a href="/manage/nscc_utf_request/export/line_items">Export the Line Items</a></li></ul>',
		'#suffix'=> '</div>',
	);
	return system_settings_form($form);
}


function _nscc_utf_request_list_requests($nopage=false){
	global $user;
	$sql = 'SELECT * FROM {nscc_utf_request} ORDER BY changed ASC;';
	$result = db_query(db_rewrite_sql($sql));
	$output = '<h2>Requests for the '.variable_get('nscc_utf_request_year','')." UTF Committee</h2>\n";
	$due_date_array = variable_get('nscc_utf_request_due_date','');
	$due_date_string = $due_date_array['month'].'/'.$due_date_array['day'].'/'.$due_date_array['year'];
	$output .="<div>Request Deadline: <b>$due_date_string</b></div>\n<hr>\n";
	$output .= "<table>\n";
	$output .= "\t<tr>";
	$output .= "<td>Request #</td>";
	$output .= "<td>Requestor</td>";
	$output .= "<td>Submitted</td>";
	$output .= "<td>Location/Department</td>";
	$output .= "<td colspan=\"2\">Description</td>";
	$output .= "</tr>\n";
	while($current_request = db_fetch_object($result)){
		$output .= "\t<tr>";
		$output .= "<td>{$current_request->request_id}</td>";
		$output .= "<td>{$current_request->requestor_name}</td>";
		$output .= "<td>".date('M j, Y H:i:s',$current_request->changed)."</td>";
		$output .= "<td>{$current_request->intended_location}</td>";
		if($user->uid == $current_request->requestor_uid || user_access('administer utf requests')){
			$output .= "<td>".substr($current_request->description,0,15)."...</td>";
			$output .= "<td><a href=\"/nscc_utf_request/{$current_request->request_id}\">[view]</a><a href=\"/nscc_utf_request/{$current_request->request_id}/edit\">[edit]</a> <a href=\"/nscc_utf_request/{$current_request->request_id}/delete\">[delete]</a></td>";
		} else {
			$output .= "<td>".substr($current_request->description,0,15)."...</td>";
			$output .= "<td><a href=\"/nscc_utf_request/{$current_request->request_id}\">[view]</a></td>";
		}
		$output .= "</tr>\n";
	}
	$output .= "</table>\n";
	if(! $nopage){
		if($user->uid > 0){
			$output .= "<a href=\"nscc_utf_request/add\">Submit a New Request</a>\n";
		} else {
      // Fancy UI enhancements.
//			$output .= "Login (upper right) to make a request.\n";
			$output .= "<a href=\"/user/login\">Login</a> to make a request.\n";
			drupal_add_js(drupal_get_path('module','nscc_utf_request').'/utf-ui.js','theme');
		}
		$output .= "<p>All requests must comply with the UTF submission guidelines.</p>\n";
	}
	
	if($nopage){
		print preg_replace('/utf_request/','utf_request_nopage',$output);
	} else {
		return $output;
	}
}


function _nscc_utf_request_view($request_id,$nopage=false){
	$sql = 'SELECT * FROM {nscc_utf_request} WHERE request_id=%d';
	$result = db_query(db_rewrite_sql($sql),$request_id);
	if($retrieved_request = db_fetch_object($result)){
			$output .='<div id="requestor"><b>Requested by:</b> '.$retrieved_request->requestor_name."</div>\n";
			$output .='<div id="intended_location"><b>Requested for:</b> '.$retrieved_request->intended_location."</div>\n";
			$output .='<div id="description"><b>Description:</b> '.$retrieved_request->description."</div>\n";
			$output .='<div id="benefit"><b>Expected Benefit:</b> '.$retrieved_request->benefits."</div>\n";

			$sql = 'SELECT r.requestor_uid,li.* FROM {nscc_utf_request_line_item} as li join {nscc_utf_request} as r using (request_id) WHERE li.request_id = %d ORDER BY li.changed ASC;';
			$line_item_result = db_query(db_rewrite_sql($sql),$request_id);
			$output .='<div id="financials"><b>Details:</b><br>'."\n";
			$output .= "<table>\n";
			$output .= "\t<tr>";
			$output .= "<td>line_item #</td>";
			$output .= "<td>Description</td>";
			$output .= "<td>Location</td>";
			$output .= "<td>Unit Price</td>";
			$output .= "<td>Quantity</td>";
			$output .= "<td>Total</td>";
			$output .= "</tr>\n";
			while($current_line_item = db_fetch_object($line_item_result)){
				$output .= "\t<tr>";
				$output .= "<td>{$current_line_item->line_item_id}</td>";
				$output .= "<td>{$current_line_item->description}</td>";
				$output .= "<td>{$current_line_item->location}</td>";
				$output .= "<td>$".$current_line_item->unit_price."</td>";
				$output .= "<td>{$current_line_item->quantity}</td>";
				$output .= "<td>$".$current_line_item->unit_price * $current_line_item->quantity."</td>";
				$output .= "</tr>\n";
			}
			$output .='<tr id="subtotal"><td colspan="4"></td><td>Subtotal:</td><td>$'._nscc_utf_request_total_line_items($request_id)."</td></tr>\n";
			$output .='<tr id="estimatedshipping"><td colspan="4"></td><td>Estimated Shipping:</td><td>$'.$retrieved_request->estimated_shipping."</td></tr>\n";
			$output .='<tr id="salestax"><td colspan="4"></td><td>Estimated Sales Tax:</td><td>$'.round((_nscc_utf_request_total_line_items($request_id) + $retrieved_request->estimated_shipping) * .095,2)."</td></tr>\n";
			$output .='<tr id="grandtotal"><td colspan="4"></td><td>Total Requested Funds:</td><td><b>$'.round((_nscc_utf_request_total_line_items($request_id) + $retrieved_request->estimated_shipping) * 1.095,2)."</b></td></tr>\n";
			$output .= "</table>\n</div>\n";
			$output .='<div><a href="/nscc_utf_request">Back</a> to the UTF Request Listing</div>'."\n";
	} else {
		$output = 'Error';
	}
	if($nopage){
		print preg_replace('/utf_request/','utf_request_nopage',$output);
	} else {
		return $output;
	}

}


function nscc_utf_request_delete_form($questionable_garbage,$request_id){
	$form['request_id'] = array(
								'#type'=>'value',
								'#value'=>$request_id,
								);
	$form['submit'] = array(
								'#type'=>'submit',
								'#value'=>'Irrevocably Delete This UTF Request ('.$request_id.')',
								'#description'=>'( This cannot be undone. )',
	);
	return $form;
}

function nscc_utf_request_delete_form_submit($form, &$form_state){
	$delete_line_items_sql='DELETE FROM {nscc_utf_request_line_item} WHERE request_id=%d';
	$delete_request_sql='DELETE FROM {nscc_utf_request} WHERE request_id=%d';
	if( db_query(db_rewrite_sql($delete_line_items_sql),$form_state['values']['request_id']) && db_query(db_rewrite_sql($delete_request_sql),$form_state['values']['request_id'])){
			$form_state['redirect'] = 'nscc_utf_request';
			drupal_set_message(t('UTF Request # %request_id (and all related line items) Deleted.',array('%request_id'=>$form_state['values']['request_id'])));
	} else {
			drupal_set_message(t('There was a problem Deleting UTF Request # %request_id (and all related line items).',array('%request_id'=>$form_state['values']['request_id'])));
	}	
}

function nscc_utf_request_baserequestform($questionable_garbage=null,$request_id=null){
	global $user;
	$requestor_user = user_load($user->uid);
	if($request_id){
		$sql = 'SELECT * FROM {nscc_utf_request} WHERE request_id=%d';
		$result = db_query(db_rewrite_sql($sql),$request_id);
		if($retrieved_request = db_fetch_object($result)){
			$default_requestor_name = $retrieved_request->requestor_name;
			$default_requestor_email = $retrieved_request->requestor_email;
			$default_requestor_phone = $retrieved_request->requestor_phone;
			$default_intended_location = $retrieved_request->intended_location;
			$default_description = $retrieved_request->description;
			$default_benefits = $retrieved_request->benefits;
			$default_estimated_shipping = $retrieved_request->estimated_shipping;
		}
		$submit_value = 'Update Request'; 
	} else {
		$default_requestor_name = $requestor_user->nscc_profile_first_name.' '.$requestor_user->nscc_profile_last_name;
		$default_requestor_email = $requestor_user->nscc_profile_email_address;
		$default_requestor_phone = $requestor_user->nscc_profile_phone;
		$default_intended_location = '';
		$default_description = '';
		$default_benefits = '';
		$default_estimated_shipping = 0.00;
		$submit_value = 'Add Line Items'; 
	}
	$form['request_id'] = array(
								'#type'=>'value',
								'#value'=>$request_id,
								);
	$form['requestor'] = array(
								'#title'=>t('Requestor Info'),
								'#type'=>'fieldset',
								'#collapsible'=> TRUE,									
								);
	$form['requestor']['requestor_name'] = array(
								'#title'=>t('Requestor Name'),
								'#type'=>'textfield',
								'#description'=>t('Enter your name.'),
								'#required'=>TRUE,
								'#maxlength'=>200,
								'#default_value'=>$default_requestor_name,
								);														
	$form['requestor']['requestor_email'] = array(
								'#title'=>t('Email Address'),
								'#type'=>'textfield',
								'#description'=>t('Enter the email address you wish the UTF committee to contact you with if there are questions about your request.'),
								'#required'=>TRUE,
								'#maxlength'=>200,
								'#default_value'=>$default_requestor_email,
								);
	$form['requestor']['requestor_phone'] = array(
								'#title'=>t('Phone Number'),
								'#type'=>'textfield',
								'#description'=>t('Enter the local phone number you wish the UTF committee to contact you with if there are questions about your request.'),
								'#maxlength'=>15,
								'#required'=>TRUE,
								'#default_value'=>$default_requestor_phone,
								);
	$form['request'] = array(
								'#title'=>t('Request Overview'),
								'#type'=>'fieldset',
								'#collapsible'=> TRUE,									
								);							
	$form['request']['intended_location'] = array(
								'#title'=>t('Intended Location'),
								'#type'=>'textfield',
								'#size'=>20,
								'#description'=>t('Enter the location or department for whom you wish to purchase this technology.'),
								'#required'=>TRUE,
								'#default_value'=>$default_intended_location,
								);
	$form['request']['description'] = array(
								'#title'=>t('Description'),
								'#type'=>'textarea',
								'#description'=>t('Please describe the technology you are requesting.'),
								'#required'=>TRUE,
								'#default_value'=>$default_description,
								);
	$form['request']['benefits'] = array(
								'#title'=>t('Expected Benefits'),
								'#type'=>'textarea',
								'#description'=>t('Please explain how the requested technology will benefit students.'),
								'#required'=>TRUE,
								'#default_value'=>$default_benefits,
								);
	if(!$request_id){
		//save out the new request, move on to line items
  	$form['approvals'] = array(
								'#title'=>t('Request Approvals'),
								'#type'=>'fieldset',
								'#collapsible'=> TRUE,									
								);							
		
		$form['approvals']['dean_approval']=array(
			'#title'=>t('Dean\'s Approval'),
			'#type'=>'checkboxes',
			'#options'=>array('Dean Approves'=>'The Dean or Department Head has approved this request.'),
			'#required'=>TRUE,
		);
		$form['approvals']['vp_approval']=array(
			'#title'=>t('VP\'s Approval'),
			'#type'=>'checkboxes',
			'#options'=>array('VP Approves'=>'The Vice President has approved this request.'),
			'#required'=>TRUE,
		);
		$form['submit'] = array(
								'#type'=>'submit',
								'#value'=>$submit_value,
							);															
	} else {
		$form['details'] = array(
									'#title'=>t('Request Details'),
									'#type'=>'fieldset',
									'#collapsible'=> TRUE,									
								);							

		$form['details']['line_items'] = array(
									'#prefix'=>'<div id="line_items">',
									'#value'=>_nscc_utf_request_list_line_items($request_id),
									'#suffix'=>'</div>',
								);
		$form['details']['subtotal'] = array(
									'#prefix'=>'<div id="subtotal">',
									'#value'=>'Subtotal: '._nscc_utf_request_total_line_items($request_id),
									'#suffix'=>'</div>',
									);
		$form['details']['estimated_shipping'] = array(
									'#title'=>t('Estimated Shipping Cost'),
									'#type'=>'textfield',
									'#field_prefix'=>'$',
									'#size'=>7,
									'#description'=>t('Put in your best guess as to the shipping cost of your complete request. It is better to err high.'),
									'#required'=>TRUE,
									'#default_value'=>$default_estimated_shipping,
									);
		$form['details']['salestax'] = array(
									'#prefix'=>'<div id="salestax">',
									'#value'=>'Estimated Sales Tax: '.round((_nscc_utf_request_total_line_items($request_id) + $default_estimated_shipping) * .095,2),
									'#suffix'=>'</div>',
									);
		$form['details']['grand_total'] = array(
									'#prefix'=>'<div id="grandtotal">',
									'#value'=>'Total Requested Funds: '.round((_nscc_utf_request_total_line_items($request_id) + $default_estimated_shipping) * 1.095,2),
									'#suffix'=>'</div>',
									);
		$form['submit'] = array(
								'#type'=>'submit',
								'#value'=>$submit_value,
							);								
	}
	return $form;
}

function nscc_utf_request_baserequestform_validate($form, &$form_state){
	if ($form_state['values']['estimated_shipping'] < 0){
		form_set_error('estimated_shipping','Estimated shipping must be a positive value');
	}
	if(!valid_email_address($form_state['values']['requestor_email'])){
		form_set_error('requestor_email','You must enter a valid email address.');
	}
}

function nscc_utf_request_baserequestform_submit($form, &$form_state){
		global $user;
		$utf_request = new stdClass();
		$utf_request->requestor_uid = $user->uid;
		$utf_request->requestor_name = $form_state['values']['requestor_name'];
		$utf_request->requestor_email = $form_state['values']['requestor_email'];
		$utf_request->requestor_phone = $form_state['values']['requestor_phone'];
		$utf_request->intended_location = $form_state['values']['intended_location'];
		$utf_request->description = $form_state['values']['description'];
		$utf_request->benefits = $form_state['values']['benefits'];
		if($form_state['values']['submit'] == 'Add Line Items'){
			$utf_request->created = time();
			$utf_request->changed = time();
			$utf_request->estimated_shipping = 0.00;
			drupal_write_record('nscc_utf_request',$utf_request);	
			$form_state['redirect'] = 'nscc_utf_request/'.$utf_request->request_id.'/edit_line_items';
					} else {
			if($form_state['values']['request_id']){
				$utf_request->estimated_shipping = $form_state['values']['estimated_shipping'];
				$utf_request->request_id = $form_state['values']['request_id'];
				$utf_request->changed = time();
				drupal_write_record('nscc_utf_request',$utf_request,'request_id');	
				$form_state['redirect'] = 'nscc_utf_request';
				drupal_set_message(t('UTF request # %request_id Updated.',array('%request_id'=>$form_state['values']['request_id'])));
			}
		}
		
}


function _nscc_utf_request_list_line_items($request_id){
	global $user;
	$sql = 'SELECT r.requestor_uid,li.* FROM {nscc_utf_request_line_item} as li join {nscc_utf_request} as r using (request_id) WHERE li.request_id = %d ORDER BY li.changed ASC;';
	$result = db_query(db_rewrite_sql($sql),$request_id);
	$output = "<table>\n";
	$output .= "\t<tr>";
	$output .= "<td>line_item #</td>";
	$output .= "<td>Description</td>";
	$output .= "<td>Location</td>";
	$output .= "<td>Unit Price</td>";
	$output .= "<td>Quantity</td>";
	$output .= "<td>Total</td>";
	//$output .= "<td>Actions</td>";
	$output .= "</tr>\n";
	while($current_line_item = db_fetch_object($result)){
		$output .= "\t<tr>";
		$output .= "<td>{$current_line_item->line_item_id}</td>";
		$output .= "<td>{$current_line_item->description}</td>";
		$output .= "<td>{$current_line_item->location}</td>";
		$output .= "<td>$".$current_line_item->unit_price."</td>";
		$output .= "<td>{$current_line_item->quantity}</td>";
		$output .= "<td>$".$current_line_item->unit_price * $current_line_item->quantity."</td>";
		//if($user->uid == $current_line_item->requestor_uid || user_access('administer utf requests')){
		//	$output .="<td>";
		//	$output .="<a href=\"nscc_utf_request/$request_id/line_item/{$current_line_item->line_item_id}/edit\">[edit]</a> <a href=\"nscc_utf_request/$request_id/line_item/{$current_line_item->line_item_id}/delete\">[delete]</a>";
		//	$output .="</td>";
		//}
		$output .= "</tr>\n";
	}
	$output .= "</table>\n";
	$output .= "<a href=\"edit_line_items\">Edit Line Items</a>\n";
	return $output;
}

function _nscc_utf_request_total_line_items($request_id){
	$sql = 'SELECT sum(li.unit_price * li.quantity) as total FROM {nscc_utf_request_line_item} as li WHERE li.request_id = %d;';
	return db_result(db_query(db_rewrite_sql($sql),$request_id));
}

function nscc_utf_request_edit_line_itemsform($questionable_garbage,$request_id,$line_item_id = null){
//displays line items, with links for edit and delete to existing items, and add form for new items
	global $user;
	$sql = 'SELECT r.requestor_uid,li.* FROM {nscc_utf_request_line_item} as li join {nscc_utf_request} as r using (request_id) WHERE li.request_id = %d ORDER BY li.changed ASC;';
	$result = db_query(db_rewrite_sql($sql),$request_id);
	$output = "<table>\n";
	$output .= "\t<tr>";
	$output .= "<td>line_item #</td>";
	$output .= "<td>Description</td>";
	$output .= "<td>Location</td>";
	$output .= "<td>Unit Price</td>";
	$output .= "<td>Quantity</td>";
	$output .= "<td>Total</td>";
	$output .= "<td>Actions</td>";
	$output .= "</tr>\n";
	while($current_line_item = db_fetch_object($result)){
		if($current_line_item->line_item_id != $line_item_id){
			$output .= "\t<tr>";
			$output .= "<td>{$current_line_item->line_item_id}</td>";
			$output .= "<td>{$current_line_item->description}</td>";
			$output .= "<td>{$current_line_item->location}</td>";
			$output .= "<td>$".$current_line_item->unit_price."</td>";
			$output .= "<td>{$current_line_item->quantity}</td>";
			$output .= "<td>$".$current_line_item->unit_price * $current_line_item->quantity."</td>";
			if($user->uid == $current_line_item->requestor_uid || user_access('administer utf requests')){
				$output .="<td>";
				$output .="<a href=\"/nscc_utf_request/$request_id/line_item/{$current_line_item->line_item_id}/edit\">[edit]</a> <a href=\"/nscc_utf_request/$request_id/line_item/{$current_line_item->line_item_id}/delete\">[delete]</a>";
				$output .="</td>";
			}
			$output .= "</tr>\n";
		}
	}
	$output .= "</table>\n<p>";


	$form['request_id'] = array(
								'#type'=>'value',
								'#value'=>$request_id,
								);
	$form['line_items'] = array(
							'#prefix'=>'<div id="line_items">',
							'#value'=>$output,
							'#suffix'=>'</div>',
						);

	if(!$line_item_id){
		$form['new_line_item'] = array(
								'#title'=>t('Add Line Item'),
								'#type'=>'fieldset',
								);
		$form['new_line_item']['description'] = array(
														'#title'=>t('Item Description'),
														'#type'=>'textfield',
														'#description'=>t('Enter a brief description of the item'),
														'#maxlength'=>200,
														'#size'=>50,
														'#required'=>TRUE,
														'#default_value'=>'',
												);							
		$form['new_line_item']['location'] = array(
														'#title'=>t('Location'),
														'#type'=>'textfield',
														'#description'=>t('Enter the intended location of this item'),
														'#maxlength'=>200,
														'#size'=>50,
														'#required'=>FALSE,
														'#default_value'=>'',
												);							
		$form['new_line_item']['unit_price'] = array(
														'#title'=>t('Unit Cost'),
														'#type'=>'textfield',
														'#field_prefix'=>'$',
														'#size'=>7,
														'#description'=>t('The price of one of these items'),
														'#required'=>TRUE,
														'#default_value'=>'',
												);							
		$form['new_line_item']['quantity'] = array(
														'#title'=>t('Quantity'),
														'#type'=>'textfield',
														'#size'=>7,
														'#description'=>t('The number of these items requested'),
														'#required'=>TRUE,
														'#default_value'=>'',
												);							
		$form['new_line_item']['submit_add'] = array(
														'#type'=>'submit',
														'#value'=>'Add This Line Item',
												);							
	} else {
		$sql = 'SELECT li.* FROM {nscc_utf_request_line_item} as li  WHERE li.line_item_id=%d;';
		$current_line_item = db_fetch_object(db_query(db_rewrite_sql($sql),$line_item_id));
		$form['new_line_item'] = array(
								'#title'=>t('Edit Line Item'),
								'#type'=>'fieldset',
								);
		$form['new_line_item']['line_item_id'] = array(
								'#type'=>'value',
								'#value'=>$line_item_id,
								);
								
		$form['new_line_item']['description'] = array(
														'#title'=>t('Item Description'),
														'#type'=>'textfield',
														'#description'=>t('Enter a brief description of the item'),
														'#maxlength'=>200,
														'#size'=>50,
														'#required'=>TRUE,
														'#default_value'=>$current_line_item->description,
												);							
		$form['new_line_item']['location'] = array(
														'#title'=>t('Location'),
														'#type'=>'textfield',
														'#description'=>t('Enter the intended location of this item'),
														'#maxlength'=>200,
														'#size'=>50,
														'#required'=>FALSE,
														'#default_value'=>$current_line_item->location,
												);							
		$form['new_line_item']['unit_price'] = array(
														'#title'=>t('Unit Cost'),
														'#type'=>'textfield',
														'#field_prefix'=>'$',
														'#size'=>7,
														'#description'=>t('The price of one of these items'),
														'#required'=>TRUE,
														'#default_value'=>$current_line_item->unit_price,
												);							
		$form['new_line_item']['quantity'] = array(
														'#title'=>t('Quantity'),
														'#type'=>'textfield',
														'#size'=>7,
														'#description'=>t('The number of these items requested'),
														'#required'=>TRUE,
														'#default_value'=>$current_line_item->quantity,
												);							
		$form['new_line_item']['submit_update'] = array(
														'#type'=>'submit',
														'#value'=>'Update This Line Item',
												);							
	}
	$form['done'] = array(
							'#prefix'=>'<div>',
							'#value'=>'<a href="/nscc_utf_request/'.$request_id.'/edit">DONE Editing Line Items</a>',
							'#suffix'=>'</div>'
						);							
	return $form;
}

function nscc_utf_request_edit_line_itemsform_validate($form, &$form_state){
	return true;
}

function nscc_utf_request_edit_line_itemsform_submit($form, &$form_state){
		$line_item = new stdClass();
		$line_item->description = $form_state['values']['description'];
		$line_item->location = $form_state['values']['location'];
		$line_item->unit_price = $form_state['values']['unit_price'];
		$line_item->quantity = $form_state['values']['quantity'];
		$line_item->weight = 0;
		$line_item->request_id = $form_state['values']['request_id'];
		if(!$form_state['values']['line_item_id']){
			$line_item->weight = 0;
			$line_item->created = time();
			$line_item->changed = time();
			drupal_write_record('nscc_utf_request_line_item',$line_item);	
			drupal_set_message(t('Line Item Added.'));
			$form_state['redirect'] = '/nscc_utf_request/'.$form_state['values']['request_id'].'/edit_line_items';
		} else {
			if($form_state['values']['submit_update']){
				$line_item->line_item_id = $form_state['values']['line_item_id'];
				$line_item->changed = time();
				drupal_set_message(t('Line Item Updated.'));
				drupal_write_record('nscc_utf_request_line_item',$line_item,'line_item_id');	
				$form_state['redirect'] = '/nscc_utf_request/'.$form_state['values']['request_id'].'/edit_line_items';
			} else {
				drupal_set_message(t('Done Updating Line Items.'));
				$form_state['redirect'] = '/nscc_utf_request/'.$form_state['values']['request_id'].'/edit';				
			}
		}
}


function nscc_utf_request_delete_line_itemform($questionable_garbage,$request_id,$line_item_id){
	$form['request_id'] = array(
								'#type'=>'value',
								'#value'=>$request_id,
								);
	$form['line_item_id'] = array(
								'#type'=>'value',
								'#value'=>$line_item_id,
								);
	$form['submit'] = array(
								'#type'=>'submit',
								'#value'=>'Irrevocably Delete This Line Item ('.$line_item_id.')',
								'#description'=>'( This cannot be undone. )',
	);
	return $form;
}

function nscc_utf_request_delete_line_itemform_validate($form, &$form_state){
	return true;
}

function nscc_utf_request_delete_line_itemform_submit($form, &$form_state){
	$delete_line_item_sql='DELETE FROM {nscc_utf_request_line_item} WHERE line_item_id=%d';
	if( db_query(db_rewrite_sql($delete_line_item_sql),$form_state['values']['line_item_id']) ){
			$form_state['redirect'] = '/nscc_utf_request/'.$form_state['values']['request_id'].'/edit_line_items';
			drupal_set_message(t('Line Item Deleted'));
	} else {
			drupal_set_message(t('There was a problem Deleting Line Item # %line_item_id.',array('%line_item_id'=>$form_state['values']['line_item_id'])));
	}	
}

