<?php

/* This is a generated data file for the net price calculator abomination */
function _nscc_ncalc_get_data(){

	$ncalcdata = new stdClass();
        

$ncalcdata->efcDependent = array(); 
$ncalcdata->efcDependent[0] = new stdClass();
$ncalcdata->efcDependent[0]->numberInCollege=1;
$ncalcdata->efcDependent[0]->numberInFamily=2;
$ncalcdata->efcDependent[0]->incomeRanges= array(); 
$ncalcdata->efcDependent[0]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[0]->incomeRanges[1] = 1662;
$ncalcdata->efcDependent[0]->incomeRanges[2] = 3838;
$ncalcdata->efcDependent[0]->incomeRanges[3] = 6233;
$ncalcdata->efcDependent[0]->incomeRanges[4] = 9213;
$ncalcdata->efcDependent[0]->incomeRanges[5] = 12598;
$ncalcdata->efcDependent[0]->incomeRanges[6] = 16073;
$ncalcdata->efcDependent[0]->incomeRanges[7] = 19652;
$ncalcdata->efcDependent[0]->incomeRanges[8] = 31988;

$ncalcdata->efcDependent[1] = new stdClass();
$ncalcdata->efcDependent[1]->numberInCollege=1;
$ncalcdata->efcDependent[1]->numberInFamily=3;
$ncalcdata->efcDependent[1]->incomeRanges= array(); 
$ncalcdata->efcDependent[1]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[1]->incomeRanges[1] = 1148;
$ncalcdata->efcDependent[1]->incomeRanges[2] = 3345;
$ncalcdata->efcDependent[1]->incomeRanges[3] = 5671;
$ncalcdata->efcDependent[1]->incomeRanges[4] = 8505;
$ncalcdata->efcDependent[1]->incomeRanges[5] = 11903;
$ncalcdata->efcDependent[1]->incomeRanges[6] = 15457;
$ncalcdata->efcDependent[1]->incomeRanges[7] = 19000;
$ncalcdata->efcDependent[1]->incomeRanges[8] = 33515;

$ncalcdata->efcDependent[2] = new stdClass();
$ncalcdata->efcDependent[2]->numberInCollege=1;
$ncalcdata->efcDependent[2]->numberInFamily=4;
$ncalcdata->efcDependent[2]->incomeRanges= array(); 
$ncalcdata->efcDependent[2]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[2]->incomeRanges[1] = 322;
$ncalcdata->efcDependent[2]->incomeRanges[2] = 2499;
$ncalcdata->efcDependent[2]->incomeRanges[3] = 4632;
$ncalcdata->efcDependent[2]->incomeRanges[4] = 7038;
$ncalcdata->efcDependent[2]->incomeRanges[5] = 10235;
$ncalcdata->efcDependent[2]->incomeRanges[6] = 13750;
$ncalcdata->efcDependent[2]->incomeRanges[7] = 17322;
$ncalcdata->efcDependent[2]->incomeRanges[8] = 32834;

$ncalcdata->efcDependent[3] = new stdClass();
$ncalcdata->efcDependent[3]->numberInCollege=1;
$ncalcdata->efcDependent[3]->numberInFamily=5;
$ncalcdata->efcDependent[3]->incomeRanges= array(); 
$ncalcdata->efcDependent[3]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[3]->incomeRanges[1] = 0;
$ncalcdata->efcDependent[3]->incomeRanges[2] = 1605;
$ncalcdata->efcDependent[3]->incomeRanges[3] = 3641;
$ncalcdata->efcDependent[3]->incomeRanges[4] = 5871;
$ncalcdata->efcDependent[3]->incomeRanges[5] = 8764;
$ncalcdata->efcDependent[3]->incomeRanges[6] = 12239;
$ncalcdata->efcDependent[3]->incomeRanges[7] = 15864;
$ncalcdata->efcDependent[3]->incomeRanges[8] = 31509;

$ncalcdata->efcDependent[4] = new stdClass();
$ncalcdata->efcDependent[4]->numberInCollege=1;
$ncalcdata->efcDependent[4]->numberInFamily=6;
$ncalcdata->efcDependent[4]->incomeRanges= array(); 
$ncalcdata->efcDependent[4]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[4]->incomeRanges[1] = 0;
$ncalcdata->efcDependent[4]->incomeRanges[2] = 100;
$ncalcdata->efcDependent[4]->incomeRanges[3] = 2208;
$ncalcdata->efcDependent[4]->incomeRanges[4] = 4317;
$ncalcdata->efcDependent[4]->incomeRanges[5] = 6714;
$ncalcdata->efcDependent[4]->incomeRanges[6] = 9983;
$ncalcdata->efcDependent[4]->incomeRanges[7] = 13653;
$ncalcdata->efcDependent[4]->incomeRanges[8] = 28644;

$ncalcdata->efcDependent[5] = new stdClass();
$ncalcdata->efcDependent[5]->numberInCollege=2;
$ncalcdata->efcDependent[5]->numberInFamily=2;
$ncalcdata->efcDependent[5]->incomeRanges= array(); 
$ncalcdata->efcDependent[5]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[5]->incomeRanges[1] = 1233;
$ncalcdata->efcDependent[5]->incomeRanges[2] = 2538;
$ncalcdata->efcDependent[5]->incomeRanges[3] = 3589;
$ncalcdata->efcDependent[5]->incomeRanges[4] = 5014;
$ncalcdata->efcDependent[5]->incomeRanges[5] = 6773;
$ncalcdata->efcDependent[5]->incomeRanges[6] = 13372;
$ncalcdata->efcDependent[5]->incomeRanges[7] = 9297;
$ncalcdata->efcDependent[5]->incomeRanges[8] = 27844;

$ncalcdata->efcDependent[6] = new stdClass();
$ncalcdata->efcDependent[6]->numberInCollege=2;
$ncalcdata->efcDependent[6]->numberInFamily=3;
$ncalcdata->efcDependent[6]->incomeRanges= array(); 
$ncalcdata->efcDependent[6]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[6]->incomeRanges[1] = 839;
$ncalcdata->efcDependent[6]->incomeRanges[2] = 2005;
$ncalcdata->efcDependent[6]->incomeRanges[3] = 3374;
$ncalcdata->efcDependent[6]->incomeRanges[4] = 5085;
$ncalcdata->efcDependent[6]->incomeRanges[5] = 6794;
$ncalcdata->efcDependent[6]->incomeRanges[6] = 8614;
$ncalcdata->efcDependent[6]->incomeRanges[7] = 10326;
$ncalcdata->efcDependent[6]->incomeRanges[8] = 17064;

$ncalcdata->efcDependent[7] = new stdClass();
$ncalcdata->efcDependent[7]->numberInCollege=2;
$ncalcdata->efcDependent[7]->numberInFamily=4;
$ncalcdata->efcDependent[7]->incomeRanges= array(); 
$ncalcdata->efcDependent[7]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[7]->incomeRanges[1] = 549;
$ncalcdata->efcDependent[7]->incomeRanges[2] = 1697;
$ncalcdata->efcDependent[7]->incomeRanges[3] = 2949;
$ncalcdata->efcDependent[7]->incomeRanges[4] = 4526;
$ncalcdata->efcDependent[7]->incomeRanges[5] = 6192;
$ncalcdata->efcDependent[7]->incomeRanges[6] = 7988;
$ncalcdata->efcDependent[7]->incomeRanges[7] = 9775;
$ncalcdata->efcDependent[7]->incomeRanges[8] = 18327;

$ncalcdata->efcDependent[8] = new stdClass();
$ncalcdata->efcDependent[8]->numberInCollege=2;
$ncalcdata->efcDependent[8]->numberInFamily=5;
$ncalcdata->efcDependent[8]->incomeRanges= array(); 
$ncalcdata->efcDependent[8]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[8]->incomeRanges[1] = 83;
$ncalcdata->efcDependent[8]->incomeRanges[2] = 1226;
$ncalcdata->efcDependent[8]->incomeRanges[3] = 2357;
$ncalcdata->efcDependent[8]->incomeRanges[4] = 3728;
$ncalcdata->efcDependent[8]->incomeRanges[5] = 5410;
$ncalcdata->efcDependent[8]->incomeRanges[6] = 7182;
$ncalcdata->efcDependent[8]->incomeRanges[7] = 8974;
$ncalcdata->efcDependent[8]->incomeRanges[8] = 17646;

$ncalcdata->efcDependent[9] = new stdClass();
$ncalcdata->efcDependent[9]->numberInCollege=2;
$ncalcdata->efcDependent[9]->numberInFamily=6;
$ncalcdata->efcDependent[9]->incomeRanges= array(); 
$ncalcdata->efcDependent[9]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[9]->incomeRanges[1] = 0;
$ncalcdata->efcDependent[9]->incomeRanges[2] = 401;
$ncalcdata->efcDependent[9]->incomeRanges[3] = 1567;
$ncalcdata->efcDependent[9]->incomeRanges[4] = 2764;
$ncalcdata->efcDependent[9]->incomeRanges[5] = 4318;
$ncalcdata->efcDependent[9]->incomeRanges[6] = 6054;
$ncalcdata->efcDependent[9]->incomeRanges[7] = 7847;
$ncalcdata->efcDependent[9]->incomeRanges[8] = 16192;

$ncalcdata->efcDependent[10] = new stdClass();
$ncalcdata->efcDependent[10]->numberInCollege=3;
$ncalcdata->efcDependent[10]->numberInFamily=3;
$ncalcdata->efcDependent[10]->incomeRanges= array(); 
$ncalcdata->efcDependent[10]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[10]->incomeRanges[1] = 915;
$ncalcdata->efcDependent[10]->incomeRanges[2] = 1706;
$ncalcdata->efcDependent[10]->incomeRanges[3] = 2358;
$ncalcdata->efcDependent[10]->incomeRanges[4] = 3328;
$ncalcdata->efcDependent[10]->incomeRanges[5] = 5120;
$ncalcdata->efcDependent[10]->incomeRanges[6] = 7358;
$ncalcdata->efcDependent[10]->incomeRanges[7] = 6197;
$ncalcdata->efcDependent[10]->incomeRanges[8] = 10648;

$ncalcdata->efcDependent[11] = new stdClass();
$ncalcdata->efcDependent[11]->numberInCollege=3;
$ncalcdata->efcDependent[11]->numberInFamily=4;
$ncalcdata->efcDependent[11]->incomeRanges= array(); 
$ncalcdata->efcDependent[11]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[11]->incomeRanges[1] = 413;
$ncalcdata->efcDependent[11]->incomeRanges[2] = 1225;
$ncalcdata->efcDependent[11]->incomeRanges[3] = 2124;
$ncalcdata->efcDependent[11]->incomeRanges[4] = 3382;
$ncalcdata->efcDependent[11]->incomeRanges[5] = 4619;
$ncalcdata->efcDependent[11]->incomeRanges[6] = 5770;
$ncalcdata->efcDependent[11]->incomeRanges[7] = 6899;
$ncalcdata->efcDependent[11]->incomeRanges[8] = 11664;

$ncalcdata->efcDependent[12] = new stdClass();
$ncalcdata->efcDependent[12]->numberInCollege=3;
$ncalcdata->efcDependent[12]->numberInFamily=5;
$ncalcdata->efcDependent[12]->incomeRanges= array(); 
$ncalcdata->efcDependent[12]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[12]->incomeRanges[1] = 260;
$ncalcdata->efcDependent[12]->incomeRanges[2] = 1048;
$ncalcdata->efcDependent[12]->incomeRanges[3] = 1891;
$ncalcdata->efcDependent[12]->incomeRanges[4] = 2961;
$ncalcdata->efcDependent[12]->incomeRanges[5] = 4232;
$ncalcdata->efcDependent[12]->incomeRanges[6] = 5416;
$ncalcdata->efcDependent[12]->incomeRanges[7] = 6582;
$ncalcdata->efcDependent[12]->incomeRanges[8] = 12831;

$ncalcdata->efcDependent[13] = new stdClass();
$ncalcdata->efcDependent[13]->numberInCollege=3;
$ncalcdata->efcDependent[13]->numberInFamily=6;
$ncalcdata->efcDependent[13]->incomeRanges= array(); 
$ncalcdata->efcDependent[13]->incomeRanges[0] = 0;
$ncalcdata->efcDependent[13]->incomeRanges[1] = 0;
$ncalcdata->efcDependent[13]->incomeRanges[2] = 462;
$ncalcdata->efcDependent[13]->incomeRanges[3] = 1236;
$ncalcdata->efcDependent[13]->incomeRanges[4] = 2092;
$ncalcdata->efcDependent[13]->incomeRanges[5] = 3207;
$ncalcdata->efcDependent[13]->incomeRanges[6] = 4436;
$ncalcdata->efcDependent[13]->incomeRanges[7] = 5634;
$ncalcdata->efcDependent[13]->incomeRanges[8] = 11372;


$ncalcdata->efcIndWithoutDep = array(); 
$ncalcdata->efcIndWithoutDep[0] = new stdClass();
$ncalcdata->efcIndWithoutDep[0]->numberInCollege=1;
$ncalcdata->efcIndWithoutDep[0]->numberInFamily=1;
$ncalcdata->efcIndWithoutDep[0]->incomeRanges= array(); 
$ncalcdata->efcIndWithoutDep[0]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithoutDep[0]->incomeRanges[1] = 10517;
$ncalcdata->efcIndWithoutDep[0]->incomeRanges[2] = 14250;
$ncalcdata->efcIndWithoutDep[0]->incomeRanges[3] = 18108;
$ncalcdata->efcIndWithoutDep[0]->incomeRanges[4] = 22054;
$ncalcdata->efcIndWithoutDep[0]->incomeRanges[5] = 25903;
$ncalcdata->efcIndWithoutDep[0]->incomeRanges[6] = 29900;
$ncalcdata->efcIndWithoutDep[0]->incomeRanges[7] = 34070.5;
$ncalcdata->efcIndWithoutDep[0]->incomeRanges[8] = 49733;

$ncalcdata->efcIndWithoutDep[1] = new stdClass();
$ncalcdata->efcIndWithoutDep[1]->numberInCollege=1;
$ncalcdata->efcIndWithoutDep[1]->numberInFamily=2;
$ncalcdata->efcIndWithoutDep[1]->incomeRanges= array(); 
$ncalcdata->efcIndWithoutDep[1]->incomeRanges[0] = 672;
$ncalcdata->efcIndWithoutDep[1]->incomeRanges[1] = 8286;
$ncalcdata->efcIndWithoutDep[1]->incomeRanges[2] = 11986;
$ncalcdata->efcIndWithoutDep[1]->incomeRanges[3] = 15852;
$ncalcdata->efcIndWithoutDep[1]->incomeRanges[4] = 19648;
$ncalcdata->efcIndWithoutDep[1]->incomeRanges[5] = 23491;
$ncalcdata->efcIndWithoutDep[1]->incomeRanges[6] = 27325;
$ncalcdata->efcIndWithoutDep[1]->incomeRanges[7] = 31081;
$ncalcdata->efcIndWithoutDep[1]->incomeRanges[8] = 44262;

$ncalcdata->efcIndWithoutDep[2] = new stdClass();
$ncalcdata->efcIndWithoutDep[2]->numberInCollege=2;
$ncalcdata->efcIndWithoutDep[2]->numberInFamily=2;
$ncalcdata->efcIndWithoutDep[2]->incomeRanges= array(); 
$ncalcdata->efcIndWithoutDep[2]->incomeRanges[0] = 1206;
$ncalcdata->efcIndWithoutDep[2]->incomeRanges[1] = 5119;
$ncalcdata->efcIndWithoutDep[2]->incomeRanges[2] = 7005;
$ncalcdata->efcIndWithoutDep[2]->incomeRanges[3] = 8953;
$ncalcdata->efcIndWithoutDep[2]->incomeRanges[4] = 10871;
$ncalcdata->efcIndWithoutDep[2]->incomeRanges[5] = 12767;
$ncalcdata->efcIndWithoutDep[2]->incomeRanges[6] = 14727;
$ncalcdata->efcIndWithoutDep[2]->incomeRanges[7] = 16566;
$ncalcdata->efcIndWithoutDep[2]->incomeRanges[8] = 22169.5;


$ncalcdata->efcIndWithDep = array(); 
$ncalcdata->efcIndWithDep[0] = new stdClass();
$ncalcdata->efcIndWithDep[0]->numberInCollege=1;
$ncalcdata->efcIndWithDep[0]->numberInFamily=2;
$ncalcdata->efcIndWithDep[0]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[0]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[0]->incomeRanges[1] = 1637;
$ncalcdata->efcIndWithDep[0]->incomeRanges[2] = 3443;
$ncalcdata->efcIndWithDep[0]->incomeRanges[3] = 5690;
$ncalcdata->efcIndWithDep[0]->incomeRanges[4] = 8862;
$ncalcdata->efcIndWithDep[0]->incomeRanges[5] = 12472;
$ncalcdata->efcIndWithDep[0]->incomeRanges[6] = 15990;
$ncalcdata->efcIndWithDep[0]->incomeRanges[7] = 19521;
$ncalcdata->efcIndWithDep[0]->incomeRanges[8] = 31434;

$ncalcdata->efcIndWithDep[1] = new stdClass();
$ncalcdata->efcIndWithDep[1]->numberInCollege=1;
$ncalcdata->efcIndWithDep[1]->numberInFamily=3;
$ncalcdata->efcIndWithDep[1]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[1]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[1]->incomeRanges[1] = 1026;
$ncalcdata->efcIndWithDep[1]->incomeRanges[2] = 2879;
$ncalcdata->efcIndWithDep[1]->incomeRanges[3] = 4967;
$ncalcdata->efcIndWithDep[1]->incomeRanges[4] = 7722;
$ncalcdata->efcIndWithDep[1]->incomeRanges[5] = 11301;
$ncalcdata->efcIndWithDep[1]->incomeRanges[6] = 14865;
$ncalcdata->efcIndWithDep[1]->incomeRanges[7] = 18368;
$ncalcdata->efcIndWithDep[1]->incomeRanges[8] = 28063;

$ncalcdata->efcIndWithDep[2] = new stdClass();
$ncalcdata->efcIndWithDep[2]->numberInCollege=1;
$ncalcdata->efcIndWithDep[2]->numberInFamily=4;
$ncalcdata->efcIndWithDep[2]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[2]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[2]->incomeRanges[1] = 143;
$ncalcdata->efcIndWithDep[2]->incomeRanges[2] = 2044.5;
$ncalcdata->efcIndWithDep[2]->incomeRanges[3] = 3933;
$ncalcdata->efcIndWithDep[2]->incomeRanges[4] = 6320;
$ncalcdata->efcIndWithDep[2]->incomeRanges[5] = 9661;
$ncalcdata->efcIndWithDep[2]->incomeRanges[6] = 13299;
$ncalcdata->efcIndWithDep[2]->incomeRanges[7] = 16837;
$ncalcdata->efcIndWithDep[2]->incomeRanges[8] = 26430;

$ncalcdata->efcIndWithDep[3] = new stdClass();
$ncalcdata->efcIndWithDep[3]->numberInCollege=1;
$ncalcdata->efcIndWithDep[3]->numberInFamily=5;
$ncalcdata->efcIndWithDep[3]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[3]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[3]->incomeRanges[1] = 0;
$ncalcdata->efcIndWithDep[3]->incomeRanges[2] = 1072;
$ncalcdata->efcIndWithDep[3]->incomeRanges[3] = 2926;
$ncalcdata->efcIndWithDep[3]->incomeRanges[4] = 5074;
$ncalcdata->efcIndWithDep[3]->incomeRanges[5] = 7911;
$ncalcdata->efcIndWithDep[3]->incomeRanges[6] = 11611;
$ncalcdata->efcIndWithDep[3]->incomeRanges[7] = 15236;
$ncalcdata->efcIndWithDep[3]->incomeRanges[8] = 24769;

$ncalcdata->efcIndWithDep[4] = new stdClass();
$ncalcdata->efcIndWithDep[4]->numberInCollege=1;
$ncalcdata->efcIndWithDep[4]->numberInFamily=6;
$ncalcdata->efcIndWithDep[4]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[4]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[4]->incomeRanges[1] = 0;
$ncalcdata->efcIndWithDep[4]->incomeRanges[2] = 0;
$ncalcdata->efcIndWithDep[4]->incomeRanges[3] = 1513;
$ncalcdata->efcIndWithDep[4]->incomeRanges[4] = 3381;
$ncalcdata->efcIndWithDep[4]->incomeRanges[5] = 5733;
$ncalcdata->efcIndWithDep[4]->incomeRanges[6] = 8928;
$ncalcdata->efcIndWithDep[4]->incomeRanges[7] = 12738;
$ncalcdata->efcIndWithDep[4]->incomeRanges[8] = 22158.5;

$ncalcdata->efcIndWithDep[5] = new stdClass();
$ncalcdata->efcIndWithDep[5]->numberInCollege=2;
$ncalcdata->efcIndWithDep[5]->numberInFamily=2;
$ncalcdata->efcIndWithDep[5]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[5]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[5]->incomeRanges[1] = 1152;
$ncalcdata->efcIndWithDep[5]->incomeRanges[2] = 2093;
$ncalcdata->efcIndWithDep[5]->incomeRanges[3] = 3294;
$ncalcdata->efcIndWithDep[5]->incomeRanges[4] = 5061;
$ncalcdata->efcIndWithDep[5]->incomeRanges[5] = 6666;
$ncalcdata->efcIndWithDep[5]->incomeRanges[6] = 8505.5;
$ncalcdata->efcIndWithDep[5]->incomeRanges[7] = 10170;
$ncalcdata->efcIndWithDep[5]->incomeRanges[8] = 15498;

$ncalcdata->efcIndWithDep[6] = new stdClass();
$ncalcdata->efcIndWithDep[6]->numberInCollege=2;
$ncalcdata->efcIndWithDep[6]->numberInFamily=3;
$ncalcdata->efcIndWithDep[6]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[6]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[6]->incomeRanges[1] = 888;
$ncalcdata->efcIndWithDep[6]->incomeRanges[2] = 1790;
$ncalcdata->efcIndWithDep[6]->incomeRanges[3] = 2934;
$ncalcdata->efcIndWithDep[6]->incomeRanges[4] = 4605;
$ncalcdata->efcIndWithDep[6]->incomeRanges[5] = 6314.5;
$ncalcdata->efcIndWithDep[6]->incomeRanges[6] = 8089;
$ncalcdata->efcIndWithDep[6]->incomeRanges[7] = 9798.5;
$ncalcdata->efcIndWithDep[6]->incomeRanges[8] = 14646.5;

$ncalcdata->efcIndWithDep[7] = new stdClass();
$ncalcdata->efcIndWithDep[7]->numberInCollege=2;
$ncalcdata->efcIndWithDep[7]->numberInFamily=4;
$ncalcdata->efcIndWithDep[7]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[7]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[7]->incomeRanges[1] = 432;
$ncalcdata->efcIndWithDep[7]->incomeRanges[2] = 1313;
$ncalcdata->efcIndWithDep[7]->incomeRanges[3] = 2300;
$ncalcdata->efcIndWithDep[7]->incomeRanges[4] = 3652;
$ncalcdata->efcIndWithDep[7]->incomeRanges[5] = 5347;
$ncalcdata->efcIndWithDep[7]->incomeRanges[6] = 7079;
$ncalcdata->efcIndWithDep[7]->incomeRanges[7] = 8774;
$ncalcdata->efcIndWithDep[7]->incomeRanges[8] = 13030;

$ncalcdata->efcIndWithDep[8] = new stdClass();
$ncalcdata->efcIndWithDep[8]->numberInCollege=2;
$ncalcdata->efcIndWithDep[8]->numberInFamily=5;
$ncalcdata->efcIndWithDep[8]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[8]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[8]->incomeRanges[1] = 0;
$ncalcdata->efcIndWithDep[8]->incomeRanges[2] = 847;
$ncalcdata->efcIndWithDep[8]->incomeRanges[3] = 1728;
$ncalcdata->efcIndWithDep[8]->incomeRanges[4] = 2871;
$ncalcdata->efcIndWithDep[8]->incomeRanges[5] = 4435;
$ncalcdata->efcIndWithDep[8]->incomeRanges[6] = 6139;
$ncalcdata->efcIndWithDep[8]->incomeRanges[7] = 7821;
$ncalcdata->efcIndWithDep[8]->incomeRanges[8] = 11893.5;

$ncalcdata->efcIndWithDep[9] = new stdClass();
$ncalcdata->efcIndWithDep[9]->numberInCollege=2;
$ncalcdata->efcIndWithDep[9]->numberInFamily=6;
$ncalcdata->efcIndWithDep[9]->incomeRanges= array(); 
$ncalcdata->efcIndWithDep[9]->incomeRanges[0] = 0;
$ncalcdata->efcIndWithDep[9]->incomeRanges[1] = 0;
$ncalcdata->efcIndWithDep[9]->incomeRanges[2] = 167;
$ncalcdata->efcIndWithDep[9]->incomeRanges[3] = 985;
$ncalcdata->efcIndWithDep[9]->incomeRanges[4] = 1866;
$ncalcdata->efcIndWithDep[9]->incomeRanges[5] = 2986;
$ncalcdata->efcIndWithDep[9]->incomeRanges[6] = 4546.5;
$ncalcdata->efcIndWithDep[9]->incomeRanges[7] = 6184;
$ncalcdata->efcIndWithDep[9]->incomeRanges[8] = 10154.5;

        
$ncalcdata->poa=new stdClass();
 $ncalcdata->poa->total = array('15845','9749','21073','14977');
$ncalcdata->poa->trf = array('3029','3029','8257','8257');
$ncalcdata->poa->bs = array('972','972','972','972');
$ncalcdata->poa->rb = array('8460','2730','8460','2730');
$ncalcdata->poa->o = array('3384','3018','3384','3018');
$ncalcdata->tga=new stdClass();
 $ncalcdata->tga->_0 = array('2600','2520','0','1783');
$ncalcdata->tga->_1_1000 = array('2680','0','0','0');
$ncalcdata->tga->_1001_2500 = array('0','1886','0','0');
$ncalcdata->tga->_2501_5000 = array('0','1613','0','0');
$ncalcdata->tga->_5001_7500 = array('571','0','0','0');
$ncalcdata->tga->_7501_10000 = array('130','0','0','0');
$ncalcdata->tga->_10001_12500 = array('0','999','0','0');
$ncalcdata->tga->_12501_15000 = array('0','0','0','0');
$ncalcdata->tga->_15001_20000 = array('0','0','0','0');
$ncalcdata->tga->_20001_30000 = array('0','0','0','0');
$ncalcdata->tga->_30001_40000 = array('0','1008','0','0');
$ncalcdata->tga->_40000 = array('0','0','0','0');
$ncalcdata->tga->nfafsa = array('0','885','0','0');


	return $ncalcdata;
}
