<?php
/**
 * Implementation of hook_help().
 */
function seattlecolleges_people_pages_help($path, $arg)
{
    switch ($path) {
        case 'admin/help#seattlecolleges_people_pages':
            $output = '<p>' . t('The profile module allows custom fields (such as country, full name, or age) to be defined and displayed in the <em>My Account</em> section. This permits users of a site to share more information about themselves, and can help community-based sites organize users around specific information.') . '</p>';
            $output .= '<p>' . t('The following types of fields can be added to a user profile:') . '</p>';
            $output .= '<ul><li>' . t('single-line textfield') . '</li>';
            $output .= '<li>' . t('multi-line textfield') . '</li>';
            $output .= '<li>' . t('checkbox') . '</li>';
            $output .= '<li>' . t('list selection') . '</li>';
            $output .= '<li>' . t('freeform list') . '</li>';
            $output .= '<li>' . t('URL') . '</li>';
            $output .= '<li>' . t('date') . '</li></ul>';
            $output .= '<p>' . t('For more information, see the online handbook entry for <a href="@seattlecolleges_people_pages">SeattleColleges People Pages module</a>.', array('@seattlecolleges_people_pages' => 'http://drupal.org/handbook/modules/profile/')) . '</p>';
            return $output;
        case 'admin/user/profile':
            return '<p>' . t("This page displays a list of the existing custom profile fields to be displayed on a user's <em>My Account</em> page. To provide structure, similar or related fields may be placed inside a category. To add a new category (or edit an existing one), edit a profile field and provide a new category name. To change the category of a field or the order of fields within a category, grab a drag-and-drop handle under the Title column and drag the field to a new location in the list. (Grab a handle by clicking and holding the mouse while hovering over a handle icon.) Remember that your changes will not be saved until you click the <em>Save configuration</em> button at the bottom of the page.") . '</p>';
    }
}
