<?php
// $Id: nscc_instructor_tools.module,v 1.236.2.3 2009/01/12 10:09:19 goba Exp $

require_once('schedule_helper_functions.inc');

/**
 * @file
 * Support for class tools for instructors on their tools pages.
 */

/**
 * Implementation of hook_menu().
 */
function nscc_instructor_tools_menu() {
  $items['tools/%/class_tools'] = array(
		'title'=>'Class Tools',
    'page callback' => '_get_instructor_class_picker_page',
		'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access callback'=> true,
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
  );
  $items['tools/%/class_tools/%'] = array(
		'title'=>'Class Tools',
    'page callback' => '_get_instructor_class_picker_page',
		'page arguments' => array(1,3),
    'type' => MENU_CALLBACK,
    'access callback'=> true,
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
  );
	$items['tools/%/enr_trans'] = array(
		'title'=>'Enrollment Transactions',
    'page callback' => '_enrollment_transactions_list',
		'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access arguments'=>array('process enrollment transactions'),
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
	);
	$items['tools/%/enr_trans/process_next'] = array(
		'title'=>'Enrollment Transactions',
    'page callback' => '_enrollment_transactions_process_next',
		'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access arguments'=>array('process enrollment transactions'),
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
	);
	$items['tools/%/enr_trans/report_tid/%'] = array(
		'title'=>'Enrollment Transactions',
    'page callback' => '_enrollment_transactions_report_tid',
		'page arguments' => array(4),
    'type' => MENU_CALLBACK,
    'access arguments'=>array('access enrollment transaction reports'),
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
	);
	$items['tools/%/enr_trans/report_sid/%'] = array(
		'title'=>'Enrollment Transactions',
    'page callback' => '_enrollment_transactions_report_sid',
		'page arguments' => array(4),
    'type' => MENU_CALLBACK,
    'access arguments'=>array('access enrollment transaction reports'),
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
	);
	$items['tools/%/enr_trans/report_pending'] = array(
		'title'=>'Enrollment Transactions',
    'page callback' => '_enrollment_transactions_report_pending',
    'type' => MENU_CALLBACK,
    'access arguments'=>array('access enrollment transaction reports'),
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
	);
	$items['tools/%/enr_trans/report_completed'] = array(
		'title'=>'Enrollment Transactions',
    'page callback' => '_enrollment_transactions_report_completed',
    'type' => MENU_CALLBACK,
    'access arguments'=>array('access enrollment transaction reports'),
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
	);
	$items['tools/%/enr_trans/report_denied'] = array(
		'title'=>'Enrollment Transactions',
    'page callback' => '_enrollment_transactions_report_denied',
    'type' => MENU_CALLBACK,
    'access arguments'=>array('access enrollment transaction reports'),
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
	);
  $items['tools/%/item_details_update/%/%'] = array(
	'title'=>'Update Item Info',
    'title callback' => '_instructor_tools_update_title',
	  'title arguments' => array(3,4),
    'page callback' => '_instructor_tools_schedule_update',
		'page arguments' => array(3,4),
    'access callback' => '_instructor_tools_update_access',
    'access arguments' => array(3,4),
    'type' => MENU_CALLBACK,
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
  );

  $items['ajax/instructor_class_schedule/%/%'] = array(
    'title' => 'Instructor Class Schedule',
    'page callback' => 'nscc_instructor_tools_instructor_class_schedule_handler',
		'page arguments'=>array(2,3),
    'access arguments' => array('access user profiles'),
    'type' => MENU_CALLBACK,
    'file' => 'nscc_instructor_tools.instructor_schedule.inc',
  );

  $items['ajax/instructor_tools/class_picker/%/%'] = array(
    'title' => 'Instructor Class Schedule',
    'page callback' => 'nscc_instructor_tools_instructor_class_picker_handler',
		'page arguments'=>array(3,4),
    'access arguments' => array('access user profiles'),
    'type' => MENU_CALLBACK,
    'file' => 'nscc_instructor_tools.instructor_schedule.admin.inc',
  );

	return $items;
}


/**
 * Implementation of hook_perm().
 */
function nscc_instructor_tools_perm(){
	return array(
		'process enrollment transactions',
		'submit enrollment transactions',
		'access enrollment transaction reports',
	);
}

/**
 * Implementation of hook_block().
 */
function nscc_instructor_tools_block($op = 'list', $delta = 0, $edit = array()) {
	switch($op){
		case 'list':
			$blocks[0]['info']= t('Instructor Tools Menu');
			$blocks[0]['cache'] = BLOCK_CACHE_PER_PAGE | BLOCK_CACHE_PER_ROLE;
			$blocks[1]['info']= t('Instructor Schedule Block');
			$blocks[1]['cache'] = BLOCK_CACHE_PER_PAGE | BLOCK_CACHE_PER_ROLE;
			$blocks[2]['info']= t('Enrollment Transactions Menu');
			$blocks[2]['cache'] = BLOCK_CACHE_PER_PAGE | BLOCK_CACHE_PER_ROLE;
			return $blocks;
			break;
		case 'configure':
			break;
		case 'save':
			break;
		case 'view':
			switch($delta){
				case 0:
					//Instructor Tools Menu
					$block['subject'] = '';
					if( _is_instructor(arg(1)) ){
						$active='';
						if (arg(2)=='class_tools'){
							$active=' active';
						}
						$block['content'] = '<ul class="tools-menu"><li class="tools-leaf'.$active.'"><a  title="Tools for Instructors" href="/tools/'.arg(1).'/class_tools">Class Tools</a></li><li class="tools-leaf"><a title="Instructor Briefcase" href="https://wts.seattlecolleges.edu/seanor/ibc/">Briefcase</a></li></ul>';
					} else {
						$block['content']='';
					}
					return $block;
				break;
					
				case 1:
					//instructor schedule block					
					require_once drupal_get_path('module','nscc_instructor_tools').'/nscc_instructor_tools.instructor_schedule.inc';
					drupal_add_js(drupal_get_path('module', 'nscc_instructor_tools') .'/nscc_instructor_tools.instructor_schedule.js');
					drupal_add_css(drupal_get_path('module', 'nscc_instructor_tools') .'/nscc_instructor_tools.css');
					if(!$_REQUEST['class_instructor']){
						switch(arg(0)){
							case 'node':
								$target_node = node_load(arg(1));
								$instructor_id = $target_node->uid;
								break;
							case 'tools':	
								//watchdog('instructor_tools','Users is arg zero! and '.arg(1).' is arg one.');
								$target_user = user_load(array('name'=>arg(1) ) );
								$instructor_id = $target_user->uid;
								//watchdog('instructor_tools','arg(0):users arg(1):'.arg(1).' target_uid:'.$target_user->uid);
								break;
							default:
								$instructor_id = arg(1);
						}

					} else {
						$instructor_id = $_REQUEST['class_instructor'];
					}
					if (!$_REQUEST['class_yrq']){
						$current_quarter = _get_current_quarter();
					} else {
						$current_quarter = $_REQUEST['class_yrq'];
					}	
					$block['content'] = '<!-- SwishCommand noindex -->' . _get_instructor_schedule_block($instructor_id,$current_quarter) . '<!-- SwishCommand index -->';
					return $block;
				break;	

				case 2:
					//Enrollment Transactions Menu
					$block['subject'] = '';
					$active='';
					if( user_access('process enrollment transactions') || user_access('access enrollment transaction reports') ){
						if (arg(2)=='enr_trans'){
							$active=' active';
						}
						$block['content'] = '<ul class="tools-menu"><li class="tools-leaf'.$active.'"><a title="Process Enrollment Transactions Requests" href="/tools/'.arg(1).'/enr_trans">ETR</a></li></ul>';
					} else {
						$block['content']='';
					}
					return $block;
				break;
				
			}		
	}

}
/**
 * Implementation of hook_mail().
 */
function nscc_instructor_tools_mail($key,&$message,$params){
	switch($key){
		case 'etr_request_initiated':
		$student_confirm_email_message='Once the request has been completed, you will receive a confirmation email.';
		$instructor_confirm_email_message='Once the request has been completed, you will receive a confirmation email. The student has also been notified via email, and will also receive a confirmation email.';
		$arrc_contact_message='If you believe you are receiving this email in error, please contact Admissions Registration Records Credentials (ARRC) at arrc@seattlecolleges.edu.';
		$instructor_contact_message='If you believe you are receiving this email in error, please contact your instructor. For reference, this request is request number '.$params['request_id'].'.';
			switch($params['transaction_type']){
				case 'add':
					switch($params['recipient_role']){
						case 'student':
							$action_message = 'Your instructor has requested that you be added to '.$params['course'].".\n";
							switch($params['reason']){
								case 'overload':
									$reason_message = 'The instructor has permitted this as an Overload.'."\n";
									break;
								case 'permission':
									$reason_message = 'The instructor is granting Instructor Permission for this addition.'."\n";
									break;
								case 'prereq':
									$reason_message = 'The instructor feels you have met the Approved Pre-requisite.'."\n";
									break;
								case 'other':
									$reason_message = 'The instructor\'s stated reason for this addition is:'."\n";
									$reason_message .= $params['reason_other']."\n";
									break;								
							}						
							$message['subject']='NSCC Registration -- Pending Add Request #'.$params['request_id'];
							$message['body'] = "$action_message $reason_message $student_confirm_email_message $instructor_contact_message";
							break;
						case 'instructor':
							$action_message = 'We have received a request that '.$params['student_precis'].' be added to '.$params['course'].".\n";
							switch($params['reason']){
								case 'overload':
									$reason_message = 'This is to be an Overload.'."\n";
									break;
								case 'permission':
									$reason_message = 'This constitutes instructor permission for this addition.'."\n";
									break;
								case 'prereq':
									$reason_message = 'The student has  met the approved pre-requisite.'."\n";
									break;
								case 'other':
									$reason_message = 'The stated reason for this addition is:'."\n";
									$reason_message .= $params['reason_other']."\n";
									break;								
							}						
							$message['subject']='NSCC Enrollment Transaction Add Request #'.$params['request_id'].', for '.$params['student_last'].' is pending';
							$message['body'] = "$action_message $reason_message $instructor_confirm_email_message $arrc_contact_message";
							break;
					}
					break;
				case 'audit':
					switch($params['recipient_role']){
						case 'student':
							$message['subject']='NSCC Registration -- Pending Audit-Status Request #'.$params['request_id'];
							$message['body']='Your instructor has requested that you be changed to Audit status for '.$params['course'].". $student_confirm_email_message $instructor_contact_message";
							break;
						case 'instructor':
							$message['subject']='NSCC Enrollment Transaction Request #'.$params['request_id'].', change to Audit for '.$params['student_last'].' is pending';
							$message['body']='You have requested that '.$params['student_precis'].' be changed to Audit status for '.$params['course'].". $instructor_confirm_email_message $arrc_contact_message";
							break;
					}
					break;
				case 'credit':
					switch($params['recipient_role']){
						case 'student':
							$message['subject']='NSCC Registration -- Pending Credit-Status Request #'.$params['request_id'];
							$message['body']='Your instructor has requested that you be changed to Credit status for '.$params['course'].". $student_confirm_email_message $instructor_contact_message";
							break;
						case 'instructor':
							$message['subject']='NSCC Enrollment Transaction Request #'.$params['request_id'].', change to Credit for '.$params['student_last'].' is pending';
							$message['body']='You have requested that '.$params['student_precis'].' be changed to Credit status for '.$params['course'].". $instructor_confirm_email_message $arrc_contact_message";
							break;
					}
					break;
				case 'drop':
					switch($params['recipient_role']){
						case 'student':
							switch($params['reason']){
								case 'no-show':
									$reason_message = 'You will be dropped for Non-Attendance.'."\n";
									break;
								case 'other':
									$reason_message = 'The stated reason for this drop is:'."\n";
									$reason_message .= $params['reason_other']."\n";
									break;								
							}						
							$message['subject']='NSCC Registration --  Pending Drop Request #'.$params['request_id'];
							$message['body']='Your instructor has requested that you be changed to dropped from '.$params['course'].". $reason_message $student_confirm_email_message $instructor_contact_message";
							break;
						case 'instructor':
							switch($params['reason']){
								case 'no-show':
									$reason_message = 'The student should be dropped for Non-Attendance.'."\n";
									break;
								case 'other':
									$reason_message = 'The stated reason for this drop is:'."\n";
									$reason_message .= $params['reason_other']."\n";
									break;								
							}						
							$message['subject']='NSCC Enrollment Transaction Drop Request #'.$params['request_id'].', for '.$params['student_last'].' is pending';
							$message['body']='You have requested that '.$params['student_precis'].' be dropped from '.$params['course'].". $reason_message $instructor_confirm_email_message $arrc_contact_message";

							break;
					}
					break;
				case 'move':
					switch($params['recipient_role']){
						case 'student':
							switch($params['reason']){
								case 'split':
									$reason_message = 'The class has been split.'."\n";
									break;
								case 'new_section':
									$reason_message = 'A new section has opened up.'."\n";
									break;
								case 'other':
									$reason_message = 'The stated reason for this move is:'."\n";
									$reason_message .= $params['reason_other']."\n";
									break;								
							}						
							$message['subject']='NSCC Registration -- Pending Class Move Request #'.$params['request_id'];
							$message['body']='';
							break;
						case 'instructor':
							switch($params['reason']){
								case 'split':
									$reason_message = 'The class has been split.'."\n";
									break;
								case 'new_section':
									$reason_message = 'A new section has opened up.'."\n";
									break;
								case 'other':
									$reason_message = 'The stated reason for this move is:'."\n";
									$reason_message .= $params['reason_other']."\n";
									break;								
							}						
							$message['subject']='NSCC Enrollment Transaction Move Request #'.$params['request_id'].', for '.$params['student_last'].' is pending';;
							$message['body']='You have requested that '.$params['student_precis'].' be moved from '.$params['course']." to item ".$params['destination'].". $reason_message $instructor_confirm_email_message $arrc_contact_message";
							break;
					}
					break;				
			}
			break;

		case 'etr_request_completed':
		$arrc_contact_message='If you believe you are receiving this email in error, please contact Admissions Registration Records Credentials (ARRC) at arrc@seattlecolleges.edu.';
		$instructor_contact_message='If you believe you are receiving this email in error, please contact your instructor. For reference, this request is request number '.$params['request_id'].'.';
			switch($params['transaction_type']){
				case 'add':
					$payment_information_message = "Please pay your tuition within 24 hours to avoid being dropped or disregard if you have a payment plan scheduled.\n";
					switch($params['recipient_role']){
						case 'student':
							$action_message = 'You have been added to '.$params['course'].".\n";
							$message['subject']='NSCC Registration -- Request #'.$params['request_id'].' completed.';
							$message['body'] = "$action_message $payment_information_message $instructor_contact_message";
							break;
						case 'instructor':
							$action_message = 'Per your request, we have added '.$params['student_precis'].' to '.$params['course'].".\n";
							$message['subject']='NSCC Enrollment Transaction Add Request #'.$params['request_id'].', for '.$params['student_last'].' is completed';
							$message['body'] = "$action_message $arrc_contact_message";
							break;
					}
					break;
				case 'audit':
					switch($params['recipient_role']){
						case 'student':
							$message['subject']='NSCC Registration -- Audit-Status Request #'.$params['request_id'].' completed.';
							$message['body']='You have been changed to Audit status for '.$params['course'].". $instructor_contact_message";
							break;
						case 'instructor':
							$message['subject']='NSCC Enrollment Transaction Request #'.$params['request_id'].', change to Audit for '.$params['student_last'].' is completed';
							$message['body']='As you have requested,'.$params['student_precis'].' has been changed to Audit status for '.$params['course'].". $arrc_contact_message";
							break;
					}
					break;
				case 'credit':
					switch($params['recipient_role']){
						case 'student':
							$message['subject']='NSCC Registration -- Credit-Status Request #'.$params['request_id'].' completed.';
							$message['body']='You have been changed to Credit status for '.$params['course'].". $instructor_contact_message";
							break;
						case 'instructor':
							$message['subject']='NSCC Enrollment Transaction Request #'.$params['request_id'].', change to Credit for '.$params['student_last'].' is completed';
							$message['body']='As you have requested, '.$params['student_precis'].' has been changed to Credit status for '.$params['course'].". $arrc_contact_message";
							break;
					}
					break;
				case 'drop':
					switch($params['recipient_role']){
						case 'student':
							switch($params['reason']){
								case 'no-show':
									$reason_message = ' for Non-Attendance.'."\n";
									break;
								case 'other':
									$reason_message = '.  The stated reason for this drop is:'."\n";
									$reason_message .= $params['reason_other']."\n";
									break;								
							}						
							$message['subject']='NSCC Registration --  Drop Request #'.$params['request_id'].' completed';
							$message['body']='Your instructor has dropped you from '.$params['course']."$reason_message $instructor_contact_message";
							break;
						case 'instructor':
							switch($params['reason']){
								case 'no-show':
									$reason_message = ' for Non-Attendance.'."\n";
									break;
								case 'other':
									$reason_message = '.  The stated reason for this drop is:'."\n";
									$reason_message .= $params['reason_other']."\n";
									break;								
							}						
							$message['subject']='NSCC Enrollment Transaction Drop Request #'.$params['request_id'].', for '.$params['student_last'].' is completed';
							$message['body']='As you requested, '.$params['student_precis'].' has been dropped from '.$params['course']."$reason_message $arrc_contact_message";

							break;
					}
					break;
				case 'move':
					switch($params['recipient_role']){
						case 'student':
							$message['subject']='NSCC Registration -- Class Move Request #'.$params['request_id'].' completed.';
							$message['body']='';
							break;
						case 'instructor':
							$message['subject']='NSCC Enrollment Transaction Move Request #'.$params['request_id'].', for '.$params['student_last'].' is completed';
							$message['body']='As you requested, '.$params['student_precis'].' has been moved from '.$params['course']." to item ".$params['destination'].".  $arrc_contact_message";
							break;
					}
					break;				
			}
			break;

		case 'etr_request_denied':
			$arrc_contact_message='If you believe you are receiving this email in error, please contact Admissions Registration Records Credentials (ARRC) at arrc@seattlecolleges.edu.';
			$instructor_contact_message='If you believe you are receiving this email in error, please contact your instructor. For reference, this request is request number '.$params['request_id'].'.';
			$deny_message = "The reason given for denial is:\n".$params['deny_message']."\n";
			switch($params['transaction_type']){
				case 'add':
					$payment_information_message = "Please pay your tuition within 24 hours to avoid being dropped or disregard if you have a payment plan scheduled.\n";
					switch($params['recipient_role']){
						case 'student':
							$action_message = 'Your instructor\'s request to add you to '.$params['course']." has been denied.\n";
							$message['subject']='NSCC Registration -- Request #'.$params['request_id'].' denied.';
							$message['body'] = "$action_message $reason_message $instructor_contact_message";
							break;
						case 'instructor':
							$action_message = 'Your request to add '.$params['student_precis'].' to '.$params['course']." has been denied\n";
							$message['subject']='NSCC Enrollment Transaction Add Request #'.$params['request_id'].', for '.$params['student_last'].' is denied';
							$message['body'] = "$action_message $deny_message $arrc_contact_message";
							break;
					}
					break;
				case 'audit':
					switch($params['recipient_role']){
						case 'student':
							$message['subject']='NSCC Registration -- Audit-Status Request #'.$params['request_id'].' denied.';
							$message['body']='Your instructor\'s request to change you to Audit status for '.$params['course']." has been denied.\n $instructor_contact_message";
							break;
						case 'instructor':
							$message['subject']='NSCC Enrollment Transaction Request #'.$params['request_id'].', change to Audit for '.$params['student_last'].' is denied';
							$message['body']='Your request to change '.$params['student_precis'].' to Audit status for '.$params['course']." has been denied.\n$deny_message $arrc_contact_message";
							break;
					}
					break;
				case 'credit':
					switch($params['recipient_role']){
						case 'student':
							$message['subject']='NSCC Registration -- Credit-Status Request #'.$params['request_id'].' denied.';
							$message['body']='Your instructor\'s request to change you to Credit status for '.$params['course']." has been denied.\n $instructor_contact_message";
							break;
						case 'instructor':
							$message['subject']='NSCC Enrollment Transaction Request #'.$params['request_id'].', change to Credit for '.$params['student_last'].' is denied';
							$message['body']='Your request to change '.$params['student_precis'].' to Credit status for '.$params['course']." has been denied.\n$deny_message $arrc_contact_message";
							break;
					}
					break;
				case 'drop':
					switch($params['recipient_role']){
						case 'student':
							switch($params['reason']){
								case 'no-show':
									$reason_message = ' for Non-Attendance has been denied.'."\n";
									break;
								case 'other':
									$reason_message = ' has been denied.'."\n";
									$reason_message .= $params['reason_other']."\n";
									break;								
							}						
							$message['subject']='NSCC Registration --  Drop Request #'.$params['request_id'].' denied';
							$message['body']='Your instructor\'s request to drop you from '.$params['course']." has been denied. $reason_message $deny_message $instructor_contact_message";
							break;
						case 'instructor':
							switch($params['reason']){
								case 'no-show':
									$reason_message = ' for Non-Attendance has been denied.'."\n";
									break;
								case 'other':
									$reason_message = ' has been denied.'."\n";
									break;								
							}						
							$message['subject']='NSCC Enrollment Transaction Drop Request #'.$params['request_id'].', for '.$params['student_last'].' is denied';
							$message['body']='Your request to drop '.$params['student_precis'].' from '.$params['course']." has been denied. $reason_message $deny_message $arrc_contact_message";

							break;
					}
					break;
				case 'move':
					switch($params['recipient_role']){
						case 'student':
							$message['subject']='NSCC Registration -- Class Move Request #'.$params['request_id'].' completed.';
							$message['body']='';
							break;
						case 'instructor':
							$message['subject']='NSCC Enrollment Transaction Move Request #'.$params['request_id'].', for '.$params['student_last'].' is completed';
							$message['body']='As you requested, '.$params['student_precis'].' has been moved from '.$params['course']." to item ".$params['destination'].".  $arrc_contact_message";
							break;
					}
					break;				
			}
			break;

		case 'etr_daily':
		break;				
	}
}

function _instructor_tools_update_title($yrq,$item){
	require_once drupal_get_path('module','nscc_instructor_tools').'/schedule_helper_functions.inc';
	$course_array = _get_class_details($yrq,$item);
	return 'Class Tools '.rtrim(_yrq_to_quarter(strtoupper($yrq)))."/".$course_array['courseno']."(Item ".$item.")";
}

function _instructor_tools_update_access($yrq=null,$item=null){
	global $user;
	require_once drupal_get_path('module','nscc_instructor_tools').'/schedule_helper_functions.inc';
	if($user->uid == 1){
		return true;
	}
	return _check_instructor_for_class($yrq,$item,$user->name);
	//return true;
}




